import type { ImageTopic } from "@/personas/types";

export const WILLIAM_G_DANA_IMAGE_TOPICS: ImageTopic[] = [
  {
    key: "identity",
    label: "Captain Dana — who he is",
    buzzwords: [
      "who are you",
      "introduce yourself",
      "captain dana",
      "william goodwin dana",
      "portrait",
      "likeness",
      "biography",
      "myself",
      "i am",
    ],
    imageIds: ["img-portrait"],
  },
  {
    key: "adobe",
    label: "Dana Adobe / casa de Dana",
    buzzwords: [
      "adobe",
      "house",
      "casa de dana",
      "thirteen rooms",
      "nipomo adobe",
      "home",
    ],
    imageIds: ["img-adobe-restored", "img-adobe-1900", "img-adobe-salon", "img-adobe-side"],
  },
  {
    key: "hospitality",
    label: "Hospitality and El Camino Real",
    buzzwords: [
      "hospitality",
      "travelers",
      "el camino real",
      "stopping place",
      "bryant",
      "fremont",
      "halleck",
      "mail",
      "jornada",
    ],
    imageIds: ["img-adobe-salon", "img-adobe-restored"],
  },
  {
    key: "santa-barbara",
    label: "Santa Barbara years and marriage",
    buzzwords: [
      "santa barbara",
      "marriage",
      "carrillo",
      "presidio",
      "store",
      "1828",
      "mission santa barbara",
    ],
    imageIds: ["img-mission-sb"],
  },
  {
    key: "mission-slo",
    label: "Mission San Luis Obispo and the road north",
    buzzwords: [
      "mission san luis obispo",
      "san luis obispo",
      "tolosa",
      "county seat",
      "el camino",
    ],
    imageIds: ["img-mission-slo-front", "img-mission-slo-south"],
  },
  {
    key: "rancho-cattle",
    label: "Rancho, cattle, vaqueros",
    buzzwords: [
      "rancho",
      "cattle",
      "vaquero",
      "horses",
      "hides",
      "tallow",
      "stock",
    ],
    imageIds: ["img-vaqueros"],
  },
  {
    key: "chumash",
    label: "Chumash people and the Nipomo name",
    buzzwords: [
      "chumash",
      "nipomo village",
      "indigenous",
      "la purisima",
      "tomol",
      "pictograph",
    ],
    imageIds: ["img-chumash-tomol", "img-chumash-cave"],
  },
];
