import type { ImageTopic } from "@/personas/types";

export const WILLIAM_G_DANA_IMAGE_TOPICS: ImageTopic[] = [
  {
    key: "identity",
    label: "Captain Dana — who he is",
    buzzwords: [
      "who are you",
      "introduce yourself",
      "captain dana",
      "william goodwin dana",
      "portrait",
      "likeness",
      "biography",
      "myself",
      "i am",
    ],
    imageIds: ["img-portrait"],
  },
  {
    key: "grant-map",
    label: "Rancho Nipomo grant / acreage",
    buzzwords: [
      "acres",
      "acreage",
      "37,887",
      "37887",
      "48,000",
      "diseño",
      "diseno",
      "grant map",
      "plan of the rancho",
      "how many acres",
    ],
    imageIds: ["img-diseno"],
  },
  {
    key: "adobe",
    label: "Dana Adobe / casa de Dana",
    buzzwords: [
      "adobe",
      "casa de dana",
      "thirteen rooms",
      "u-shape",
      "u-shaped",
      "show me the house",
      "picture of the adobe",
    ],
    imageIds: [
      "img-adobe-vineyard",
      "img-adobe-oxcart",
      "img-adobe-1900",
      "img-adobe-1900-porch",
      "img-adobe-restored",
      "img-adobe-salon",
      "img-adobe-side",
    ],
  },
  {
    key: "hospitality",
    label: "Hospitality and El Camino Real",
    buzzwords: [
      "hospitality",
      "travelers",
      "el camino real",
      "stopping place",
      "bryant",
      "fremont",
      "halleck",
      "jornada",
    ],
    imageIds: ["img-adobe-salon", "img-adobe-vineyard"],
  },
  {
    key: "santa-barbara",
    label: "Santa Barbara years and marriage",
    buzzwords: [
      "santa barbara",
      "marriage",
      "carrillo",
      "presidio",
      "store",
      "1828",
      "mission santa barbara",
    ],
    imageIds: ["img-mission-sb"],
  },
  {
    key: "mission-slo",
    label: "Mission San Luis Obispo and the road north",
    buzzwords: [
      "mission san luis obispo",
      "san luis obispo",
      "tolosa",
      "county seat",
    ],
    imageIds: ["img-mission-slo-front", "img-mission-slo-south"],
  },
  {
    key: "rancho-cattle",
    label: "Rancho, cattle, vaqueros",
    buzzwords: [
      "cattle",
      "vaquero",
      "horses",
      "hides",
      "tallow",
      "stock",
      "cows",
    ],
    imageIds: ["img-vaqueros", "img-adobe-oxcart"],
  },
  {
    key: "chumash",
    label: "Chumash people of this coast",
    buzzwords: [
      "chumash people",
      "chumash village",
      "indigenous people",
      "1804",
      "la purisima",
      "la purísima",
    ],
    imageIds: ["img-chumash-cave"],
  },
  {
    key: "tomol",
    label: "Chumash tomol (only if asked)",
    buzzwords: ["tomol", "plank canoe"],
    imageIds: ["img-chumash-tomol"],
  },
];
