import type { SourceChunk } from "@/lib/types";

/**
 * SERVER-ONLY source pack for Capt. William G. Dana.
 *
 * Grounding: Myron Angel, History of San Luis Obispo County (1883) Dana
 * biography; Edwin Bryant, What I Saw in California (1848); California
 * Historical Landmark #1033; Dana Adobe (partner) home, history, family,
 * descendants list, and the Gladys Norton 1956 article they publish.
 * Wikipedia / Find a Grave / Blond Ranchero are not used.
 */

const ANGEL_1883 =
  "https://archive.org/details/historyofsanluis00ange";
const BRYANT_1848 =
  "https://www.gutenberg.org/files/13002/13002-h/13002-h.htm";
const OHP_1033 =
  "https://ohp.parks.ca.gov/ListedResources/Detail/1033";
const DANA_HISTORY = "https://www.danaadobe.org/history/";
const DANA_HOME = "https://www.danaadobe.org/";
const DANA_FAMILY = "https://www.danaadobe.org/family/";
const DANA_NORTON =
  "https://www.danaadobe.org/2021/09/22/looking-back-a-story-by-gladys-norton-in-1956/";
const DANA_DESCENDANTS =
  "https://www.danaadobe.org/wp-content/uploads/2023/11/Dana-Descendants.pdf";

export const williamGDanaSources: SourceChunk[] = [
  {
    id: "bio-identity",
    text: "William Goodwin Dana, known to Americans as Capt. Wm. G. Dana and in Spanish records as Guillermo G. Dana, was a Boston-born sea captain who became ranchero of Rancho Nipomo in what is now San Luis Obispo County. He is not Richard Henry Dana Jr., the author of Two Years Before the Mast — a kinsman of the New England Dana line, not the same man.",
    topics: [
      "biography",
      "who are you",
      "yourself",
      "identity",
      "william goodwin dana",
      "guillermo",
      "richard henry dana",
    ],
    dateRange: "1797-1858",
    sourceType: "biographical",
    citation:
      "Myron Angel, History of San Luis Obispo County, California (Oakland: Thompson & West, 1883), biographical sketch of Capt. Wm. G. Dana.",
    url: ANGEL_1883,
    reliability: "high",
  },
  {
    id: "bio-birth-boston",
    text: "Dana was born in Boston, Massachusetts, on May 5, 1797. His father bore the same given name; his mother, Elizabeth, was a daughter of Gen. Robert Davis of Massachusetts. The New England Dana line traces to Richard Dana, who settled at Cambridge in 1640.",
    topics: [
      "biography",
      "birth",
      "boston",
      "may 5 1797",
      "elizabeth davis",
      "ancestry",
    ],
    dateRange: "1797",
    sourceType: "biographical",
    citation:
      "Angel, History of San Luis Obispo County (1883), Dana biography; Dana Adobe, History page (Boston, 5 May 1797); Dana Adobe, Dana Descendants (updated 2023).",
    url: DANA_HISTORY,
    reliability: "high",
  },
  {
    id: "bio-youth-voyages",
    text: "Dana spent his youth in Boston and received a good education. About age eighteen, just after the War of 1812, he was sent in the service of his uncle, a Boston merchant, to Canton, remaining nearly two years, then to Calcutta for about a year before returning to Boston. He obtained a first-class certificate as a navigator. The Dana Adobe history page notes a circumnavigation on that first voyage at nineteen.",
    topics: [
      "biography",
      "youth",
      "canton",
      "calcutta",
      "china trade",
      "navigator",
      "circumnavigation",
    ],
    dateRange: "c. 1815-1818",
    sourceType: "biographical",
    citation:
      "Angel, History of San Luis Obispo County (1883), Dana youth and early travels; Dana Adobe, History page.",
    url: ANGEL_1883,
    reliability: "high",
  },
  {
    id: "bio-hawaii-waverly",
    text: "Dana's stay in Boston after the India voyage was short. In 1820 he established a commercial business and warehouse at Oahu (Honolulu) in the Sandwich Islands, his headquarters for about five years, with voyages to Canton, Russian America, California, and the South American coast. He is recorded as captain of the brig (sometimes called schooner) Waverly. About 1825 he located a store at Santa Barbara, leaving it in charge of Capt. C. R. Smith while he continued in command of the Waverly.",
    topics: [
      "biography",
      "hawaii",
      "oahu",
      "honolulu",
      "waverly",
      "sandwich islands",
      "santa barbara store",
    ],
    dateRange: "1820-1825",
    sourceType: "biographical",
    citation:
      "Angel, History of San Luis Obispo County (1883), Oahu warehouse and brig Waverly; Dana Adobe, History page (about ten years in Hawaii; Santa Barbara by the mid-1820s).",
    url: ANGEL_1883,
    reliability: "high",
  },
  {
    id: "bio-naturalization-marriage",
    text: "To marry in California, Dana had to become a naturalized Mexican citizen and be married in the Catholic Church. A letter from John B. R. Cooper, Monterey, July 22, 1828, complains of the trouble given Dana over the marriage. Dana petitioned Political Chief José María de Echeandía from Santa Barbara, March 22, 1828, for authorization to marry Doña María Josefa Carrillo, legitimate daughter of Don Carlos Antonio Carrillo of the Santa Barbara presidio. Echeandía replied from San Diego, May 1, 1828, that the application could not yet be acted upon.",
    topics: [
      "marriage",
      "naturalization",
      "catholic",
      "echeandia",
      "cooper",
      "1828",
    ],
    dateRange: "1828",
    sourceType: "primary",
    citation:
      "Angel, History of San Luis Obispo County (1883), quoting Cooper's letter of 22 July 1828 and Dana's petition of 22 March 1828 to Echeandía.",
    url: ANGEL_1883,
    reliability: "high",
  },
  {
    id: "bio-marriage-1828",
    text: "The marriage of Captain Dana and María Josefa Carrillo was solemnized at Santa Barbara on August 20, 1828. She was the eldest daughter of Don Carlos Antonio Carrillo and María Josefa (née Castro) Carrillo. He was thirty-one; she was sixteen (born 29 June 1812). The ages are documented; the sources do not record their private feelings about the match.",
    topics: [
      "marriage",
      "august 20 1828",
      "santa barbara",
      "maria josefa carrillo",
      "age at marriage",
    ],
    dateRange: "20 Aug 1828",
    sourceType: "biographical",
    citation:
      "Angel, History of San Luis Obispo County (1883), 'Marriage and Family of Mrs. Dana'; Dana Adobe, Dana Descendants (m. 20 Aug 1828, Santa Barbara).",
    url: DANA_DESCENDANTS,
    reliability: "high",
  },
  {
    id: "bio-carrillo-family",
    text: "María Josefa's father, Don Carlos Antonio Carrillo, was an Alta California governor and Mexican federal legislator. Her grandfather Don Raymundo Carrillo was among the early commanders of the posts of San Diego and Santa Barbara and founder of the family in California; he married Tomasa Lugo. Angel names five Carrillo daughters who married Americans: María Josefa (Dana), Encarnación (Capt. Thomas M. Robbins), Francisca (Capt. A. B. Thompson), Manuela (John C. Jones, U.S. consul at Honolulu), and María Antonia (Lewis T. Burton).",
    topics: [
      "carrillo",
      "carlos antonio carrillo",
      "raymundo carrillo",
      "santa barbara",
      "sisters",
    ],
    dateRange: "1828-1850",
    sourceType: "biographical",
    citation:
      "Angel, History of San Luis Obispo County (1883), Carrillo family sketch; Dana Adobe, History page (Carrillo's father a governor and legislator).",
    url: ANGEL_1883,
    reliability: "high",
  },
  {
    id: "bio-goleta-schooner",
    text: "In 1828 Captain Dana built a schooner on the Santa Barbara coast; the locality still bears the name Goleta, the Spanish word for schooner, from that fact. Angel reports it claimed as the first sea-going vessel launched in California. She was named Santa Barbara and placed under Capt. Thomas M. Robbins, former mate of the Waverly, who later sold her at Acapulco. Robbins married Encarnación Carrillo, sister of Mrs. Dana.",
    topics: [
      "goleta",
      "schooner",
      "santa barbara",
      "robbins",
      "shipbuilding",
      "1828",
    ],
    dateRange: "1828",
    sourceType: "secondary",
    citation:
      "Angel, History of San Luis Obispo County (1883), 'Captain Dana Builds a Schooner.'",
    url: ANGEL_1883,
    reliability: "medium",
  },
  {
    id: "rancho-grant-1837",
    text: "In 1835, having become a naturalized citizen of the Mexican Republic and thereby entitled to hold land, Dana applied for Rancho Nipomo. Governor Alvarado granted the request on April 6, 1837. Angel and the California landmark give about 38,000 acres (Angel: 37,887.91). Dana Adobe's home page says the rancho was initially more than 48,000 acres. Treat the acreage as contested: prefer ~38,000 from the 1883 county history and the state landmark, and say the partner site uses a larger first figure.",
    topics: [
      "rancho nipomo",
      "land grant",
      "1835",
      "april 6 1837",
      "alvarado",
      "37887",
      "acres",
    ],
    dateRange: "1835-1837",
    sourceType: "biographical",
    citation:
      "Angel, History of San Luis Obispo County (1883); California Historical Landmark #1033; Dana Adobe, History page and Home page (home page: initially more than 48,000 acres).",
    url: DANA_HISTORY,
    reliability: "high",
  },
  {
    id: "rancho-name-nipomo",
    text: "The name Nipomo is derived from a local Indian expression, given by Angel as ne-po-mah, meaning at the foot of the hill or mountain, with the accent on the last syllable. The Dana Adobe history page states that Nipomo meant 'At the Foot of the Hill' in Chumash.",
    topics: [
      "nipomo",
      "place name",
      "chumash",
      "ne-po-mah",
      "foot of the hill",
    ],
    dateRange: "pre-1837",
    sourceType: "secondary",
    citation:
      "Angel, History of San Luis Obispo County (1883), Nipomo name; Dana Adobe, History page (Chumash Era).",
    url: DANA_HISTORY,
    reliability: "high",
  },
  {
    id: "chumash-nipomo-village",
    text: "The Dana Adobe history page states that Chumash people lived along more than 160 miles of the Central Coast from Malibu to Avila Bay, and that indigenous people have lived in the area for about 10,000 years. Nipomo was once a Chumash village. The site notes at least two camps on the Dana Adobe property about 2,000 and 9,000 years old, and that the last Chumash tribal member recorded at the Nipomo village departed in 1804 after being baptized and brought to Mission La Purísima Concepción. If asked whether Chumash people built the 1839 adobe: do not answer yes. A 1956 article Dana Adobe publishes (Gladys Norton) says the residence was built by Indian labor of adobe bricks with walls two feet thick. That article does not name a tribe or a crew. Say Indian labor as the partner article states it, incomplete in detail — not 'the Chumash built my house.'",
    topics: [
      "chumash",
      "nipomo village",
      "la purisima",
      "1804",
      "mission",
      "indigenous",
    ],
    dateRange: "to 1804",
    sourceType: "secondary",
    citation:
      "Dana Adobe, History page, 'Chumash Era'; Dana Adobe, Gladys Norton, 'Looking Back' (1956), on danaadobe.org.",
    url: DANA_HISTORY,
    reliability: "medium",
  },
  {
    id: "rancho-move-1839-adobe",
    text: "After the grant, Dana continued business in Santa Barbara while carrying on the rancho until the fall of 1839, when he moved the family to Nipomo. Dana Adobe's home page and timeline say the family's residence, the Dana Adobe, was built in 1839 (construction begun 1839). Angel describes a large adobe of thirteen rooms on an elevation. A 1956 article Dana Adobe publishes describes a U-shaped house of great adobe bricks, walls two feet thick, a patio with fig trees, kitchen in one wing, storehouse in the other, and an upper-floor dormitory for younger children. Their timeline dates wings and a second storey to 1851 — just after a speaking year of 1850.",
    topics: [
      "1839",
      "adobe",
      "thirteen rooms",
      "casa de dana",
      "move to nipomo",
      "house",
    ],
    dateRange: "1839",
    sourceType: "biographical",
    citation:
      "Angel, History of San Luis Obispo County (1883); Dana Adobe, Home page (built 1839); Dana Adobe, Gladys Norton, 'Looking Back' (1956), and site timeline (begun 1839; wings/second storey 1851).",
    url: DANA_HOME,
    reliability: "high",
  },
  {
    id: "hospitality-el-camino",
    text: "From 1839 until Dana's death in 1858, Rancho Nipomo was known throughout the state as a hospitable stopping place for travelers, including Captain John C. Frémont, Edwin Bryant, and General Henry W. Halleck. For many years it was the first stopping place on El Camino Real south of Mission San Luis Obispo. Angel describes the custom of providing meals, lodging, and a relay of horses without charge, and a guide if needed; the regular jornadas south were Nipomo (about 24 miles from San Luis), then Los Alamos, Santa Ynez Mission, Refugio, and Santa Barbara.",
    topics: [
      "hospitality",
      "el camino real",
      "travelers",
      "fremont",
      "bryant",
      "halleck",
      "jornada",
    ],
    dateRange: "1839-1858",
    sourceType: "secondary",
    citation:
      "California Historical Landmark #1033; Angel, History of San Luis Obispo County (1883), hospitality and jornadas.",
    url: OHP_1033,
    reliability: "high",
  },
  {
    id: "bryant-1846-visit",
    text: "Edwin Bryant, marching with Frémont, wrote on December 18, 1846, that the company encamped about three o'clock near the rancho of Captain Dana, in a large and handsome valley well watered by an arroyo. He described Dana as a native of Massachusetts who had resided in the country about thirty years, 'known and esteemed throughout California for his intelligence and private virtues, and his unbounded generosity and hospitality.' Bryant bought wheat bread there for the men — a luxury they had not had since the march began.",
    topics: [
      "bryant",
      "what i saw in california",
      "december 1846",
      "fremont",
      "hospitality",
      "wheat bread",
    ],
    dateRange: "18 Dec 1846",
    sourceType: "primary",
    citation:
      "Edwin Bryant, What I Saw in California (New York: D. Appleton, 1848), journal 18 December 1846.",
    url: BRYANT_1848,
    reliability: "high",
  },
  {
    id: "mail-route-1847",
    text: "In 1847 the Dana ranch became an exchange point on California's first U.S. mail route. Dana Adobe publishes Gladys Norton's 1956 account of General S. W. Kearny's order of April 19, 1847: mail carried on horseback by two soldiers, starting every other Monday from San Diego and San Francisco, the parties to meet at Captain Dana's ranch the next Sunday to exchange mails. The California landmark text also names the 1847 U.S. mail exchange.",
    topics: ["mail", "1847", "postal", "exchange point", "united states mail"],
    dateRange: "1847",
    sourceType: "reference",
    citation:
      "California Historical Landmark #1033; Dana Adobe, Gladys Norton, 'Looking Back' (1956), quoting Kearny's 19 April 1847 mail order.",
    url: DANA_NORTON,
    reliability: "high",
  },
  {
    id: "edith-wreck-1848",
    text: "In 1848 the United States steamship Edith went ashore between Point Arguello and Point Sal. Angel records that Captain Dana took the officers and crew to his home, entertained them two or three weeks, then provided horses, saddles, and guides to Monterey. Several officers remained some months at the rancho. A 1956 article Dana Adobe publishes (Norton) retells the wreck as 1849 and Point Arguello; prefer Angel's 1848 and say the partner article differs by a year if asked.",
    topics: [
      "edith",
      "shipwreck",
      "1848",
      "hospitality",
      "point sal",
      "monterey",
    ],
    dateRange: "1848",
    sourceType: "secondary",
    citation:
      "Angel, History of San Luis Obispo County (1883), steamship Edith wreck and Dana hospitality.",
    url: ANGEL_1883,
    reliability: "medium",
  },
  {
    id: "manufactures-nipomo",
    text: "Angel records considerable manufacturing at Nipomo: a soap factory, looms for coarse cloths, serapes, and blankets, a turning lathe and furniture shop (including work in sandal and other woods from the Pacific trade), a blacksmith shop, and improved plows that surprised Californios used to the pointed-stick arada. Dana supplied his own people, neighboring ranchos, and the missions of La Purísima and Santa Ynez.",
    topics: [
      "soap",
      "looms",
      "blankets",
      "furniture",
      "blacksmith",
      "plows",
      "manufacturing",
    ],
    dateRange: "1839-1850",
    sourceType: "secondary",
    citation:
      "Angel, History of San Luis Obispo County (1883), manufactures at Nipomo.",
    url: ANGEL_1883,
    reliability: "high",
  },
  {
    id: "civic-prefecto-senate",
    text: "Under Mexican rule Dana served as prefecto of the district, which Angel calls the highest office in the gift of the Governor. At the first election for officers under the California Constitution, in 1849, Angel says Dana received the largest vote for the Senate, but because of informalities the office was accorded to Don Pablo de la Guerra of Santa Barbara. He later declined to run again. Angel also notes he took little part in political controversies, was believed friendly to his father-in-law Carrillo's gubernatorial claim, and that rheumatism limited his activity at the change of flag; friendship with Frémont is cited as evidence he favored the American cause.",
    topics: [
      "prefecto",
      "senate",
      "1849",
      "pablo de la guerra",
      "politics",
      "carrillo governor",
      "public office",
      "offices",
      "alcalde",
      "elected",
    ],
    dateRange: "1830s-1849",
    sourceType: "secondary",
    citation:
      "Angel, History of San Luis Obispo County (1883), Dana civic offices and 1849 senate vote.",
    url: ANGEL_1883,
    reliability: "medium",
  },
  {
    id: "slo-frame-building-1850",
    text: "After gold was discovered in 1848, Dana established business at the new county seat of San Luis Obispo. In 1850 he erected what Angel calls the first frame building in the town or county, fronting the road past the mission to Monterey (later Monterey Street), near the old palm tree. In 1851 he was elected Treasurer of San Luis Obispo County, and he built the adobe 'Casa Grande' in town — a later building, not the Nipomo adobe.",
    topics: [
      "san luis obispo",
      "1850",
      "frame building",
      "monterey street",
      "county treasurer",
      "casa grande slo",
    ],
    dateRange: "1850-1851",
    sourceType: "secondary",
    citation:
      "Angel, History of San Luis Obispo County (1883), first frame building (1850) and Casa Grande (1851).",
    url: ANGEL_1883,
    reliability: "high",
  },
  {
    id: "rheumatism-and-death",
    text: "During many later years Captain Dana suffered severely from rheumatism. Angel says that after his sea years, when he might have enjoyed ease on Nipomo, the disease returned at intervals, grew more painful, and so incapacitated him that he could not take the part in public affairs at the change of flag that he wished. Shortly thereafter he became confined to the house, paralyzed and helpless, until his death on February 12, 1858. He was buried in the Catholic cemetery of San Luis Obispo (Old Mission Cemetery). The Dana Adobe descendants list agrees on 12 February 1858; some later notices differ by a day.",
    topics: [
      "rheumatism",
      "illness",
      "death",
      "february 12 1858",
      "burial",
      "old mission cemetery",
    ],
    dateRange: "1850s-1858",
    sourceType: "biographical",
    citation:
      "Angel, History of San Luis Obispo County (1883), rheumatism and death 12 February 1858; Dana Adobe, Dana Descendants; Landmark #1033 (death 1858).",
    url: ANGEL_1883,
    reliability: "high",
  },
  {
    id: "children-tally",
    text: "Captain and Mrs. Dana were the parents of twenty-one children, of whom eight died in infancy. Angel, writing in 1883, names one adult daughter already dead (Mrs. S. A. Pollard, María Josefa Dana, 1878) and lists living sons and daughters then on the Nipomo estate: Charles W., William C., John F., Henry C., Frank, Edward G., Fred A., Adelina E., David A., Eliseo C., and Samuel A. The Dana Adobe history page states 21 children of whom 13 reached adulthood. That completed tally and the 1883 name-list belong to the later family record, not to a closed count in 1850. Names this pack can use in 1850: William C. Dana (born Santa Barbara 6 May 1836), John Francis Dana (born Santa Barbara 22 June 1837), and a daughter María Josefa Dana already married to Henry Amos Tefft by 1850. Do not recite the full 1883 estate list as the 1850 household.",
    topics: [
      "children",
      "family",
      "twenty-one",
      "thirteen",
      "infancy",
    ],
    dateRange: "1829-1883",
    sourceType: "biographical",
    citation:
      "Angel, History of San Luis Obispo County (1883), twenty-one children; Dana Adobe, History page (21 children / 13 adults).",
    url: DANA_HISTORY,
    reliability: "high",
  },
  {
    id: "john-f-trustee",
    text: "John Francis Dana, born Santa Barbara June 22, 1837, moved with the family to Nipomo in 1839. Upon his father's death he was appointed trustee of the estate and, Angel says, executed the trust for twenty years until the ranch was divided among the family. That trustee period and the later division lie after Captain Dana's lifetime.",
    topics: [
      "john francis dana",
      "trustee",
      "estate",
      "division",
      "1837",
    ],
    dateRange: "1858-c. 1878",
    sourceType: "biographical",
    citation:
      "Angel, History of San Luis Obispo County (1883), sketch of John F. Dana.",
    url: ANGEL_1883,
    reliability: "high",
  },
  {
    id: "landmark-nipomo",
    text: "Rancho Nipomo (Capt. William G. Dana Rancho) is California Historical Landmark #1033, registered August 11, 2000. The landmark text summarizes the 1837 grant of almost 38,000 acres, the El Camino Real stop south of Mission San Luis Obispo, hospitality to Frémont, Bryant, and Halleck from 1839 to 1858, and the 1847 U.S. mail exchange.",
    topics: [
      "landmark",
      "1033",
      "california historical landmark",
      "nipomo",
    ],
    dateRange: "1837-1858",
    sourceType: "reference",
    citation:
      "California Office of Historic Preservation, Listed Resources, Landmark #1033.",
    url: OHP_1033,
    reliability: "high",
  },
  {
    id: "waverly-otter-lading",
    text: "A bill of lading reproduced by Angel, for the brig Waverly, Wm. G. Dana master, lying in the harbour of Santa Barbara and bound for Oahu, lists Spanish dollars, bars of silver, otter skins, fur-seal skins, and a lump of gold. Dana is also recorded, 20 December 1826, as captain (with Thomas M. Robbins as mate) on a document vouching for Jedediah S. Smith.",
    topics: [
      "waverly",
      "otter",
      "hides",
      "bill of lading",
      "jedediah smith",
      "santa barbara",
      "oahu",
    ],
    dateRange: "1826",
    sourceType: "primary",
    citation:
      "Angel, History of San Luis Obispo County (1883), Waverly bill of lading and Jedediah Smith voucher, 20 December 1826.",
    url: ANGEL_1883,
    reliability: "high",
  },
  {
    id: "reynolds-1836-farm",
    text: "Stephen Reynolds wrote Dana from Oahu, 17 March 1836, urging him to send hides and to 'stick to your farm,' glad that Dana's prospects were good for becoming a wealthy farmer. The letter shows Dana already turning from island trade toward the California rancho before the 1837 grant was complete.",
    topics: [
      "reynolds",
      "hides",
      "farm",
      "1836",
      "oahu",
      "sandwich islands",
    ],
    dateRange: "17 Mar 1836",
    sourceType: "primary",
    citation:
      "Angel, History of San Luis Obispo County (1883), quoting Stephen Reynolds to Dana, Oahu, 17 March 1836.",
    url: ANGEL_1883,
    reliability: "high",
  },
  {
    id: "tulare-raids",
    text: "Angel says the adobe was placed on an elevation in part to watch for marauding Indians and to command a view of the valley. He records that Indians from the Tulare Valley frequently raided coast stock ranchos, and that men of the place would arm and ride out. Treat this as Angel's 1883 account of rancho defense, not as a license to invent battles or tribal names he does not give.",
    topics: [
      "tulare",
      "raids",
      "stock",
      "defense",
      "adobe location",
      "indians",
    ],
    dateRange: "1839-1850",
    sourceType: "secondary",
    citation:
      "Angel, History of San Luis Obispo County (1883), siting of the house and Tulare Valley raids.",
    url: ANGEL_1883,
    reliability: "medium",
  },
  {
    id: "partner-landscape",
    text: "Dana Adobe's history page places the house at the eastern edge of ancient sand dunes that stretch six miles from the coast, with adobe clay from the Temetatte Hills washing into Nipomo Creek to the east. Much of the property, they say, is like it was nearly 200 years ago when Captain Dana first arrived in Nipomo. The home page notes an original tallow vat still on the historic park, along with a Mission grape vineyard and gardens — later park features except the vat, which belongs to the hide-and-tallow work of the rancho.",
    topics: [
      "landscape",
      "sand dunes",
      "temetatte",
      "nipomo creek",
      "tallow vat",
      "nature",
    ],
    dateRange: "1839-1858",
    sourceType: "secondary",
    citation:
      "Dana Adobe, History page; Dana Adobe, Home page (tallow vat, vineyard, gardens).",
    url: DANA_HISTORY,
    reliability: "high",
  },
  {
    id: "partner-spanish-mexican",
    text: "Dana Adobe's history page: the first Spanish ship along this coast in 1542; in 1769 Spain established the first of 21 California missions, bringing Catholicism, new animals, disease, and agricultural change that dramatically affected indigenous peoples. Mexico's independence from Spain is dated 1821; under Mexican rule, efforts to increase California's population led to the ranchos. Twelve years after independence, secularization confiscated former mission lands and, from the 1830s, distributed them to select Mexican citizens — the setting for Dana's 1835 application and 1837 grant.",
    topics: [
      "spanish era",
      "1769",
      "missions",
      "mexico",
      "1821",
      "secularization",
      "ranchos",
    ],
    dateRange: "1542-1837",
    sourceType: "secondary",
    citation: "Dana Adobe, History page, Spanish Era and Rancho Era.",
    url: DANA_HISTORY,
    reliability: "high",
  },
  {
    id: "partner-youth-timeline",
    text: "Dana Adobe's published timeline: William G. Dana born Boston 1797; orphaned 1806 and goes to live with uncle and shipmaster William Heath Davis; 1815 sails from Boston to Honolulu with his uncle; 1822 inherits $5,000 from his uncle Davis in Honolulu and buys a ship; 1825 visits Santa Barbara for the first time as master of the Waverly. Angel independently records the $5,000 bequest from William H. Davis (1822 will) and the Santa Barbara / Waverly years.",
    topics: [
      "orphaned",
      "william heath davis",
      "honolulu",
      "1815",
      "1822",
      "inheritance",
      "youth",
    ],
    dateRange: "1806-1825",
    sourceType: "secondary",
    citation:
      "Dana Adobe, Gladys Norton, 'Looking Back' (1956), timeline on danaadobe.org; Angel, History of San Luis Obispo County (1883), Davis will and Waverly.",
    url: DANA_NORTON,
    reliability: "medium",
  },
  {
    id: "partner-sb-offices",
    text: "Dana Adobe's 1956 Norton article, drawing on Bancroft, says that after naturalization in 1835 and while still in Santa Barbara, Dana served as appraiser at La Purísima mission, as Captain of the Port of Santa Barbara, and in 1836 as alcalde. At Nipomo he later held Prefecto (1849) and, after statehood, County Treasurer (1851).",
    topics: [
      "alcalde",
      "1836",
      "santa barbara",
      "port captain",
      "la purisima",
      "prefecto",
      "1849",
      "public office",
      "offices",
    ],
    dateRange: "1835-1851",
    sourceType: "secondary",
    citation:
      "Dana Adobe, Gladys Norton, 'Looking Back' (1956), citing Bancroft, on danaadobe.org.",
    url: DANA_NORTON,
    reliability: "medium",
  },
  {
    id: "partner-1849-polling",
    text: "Dana Adobe publishes that in 1849 Nipomo Rancho was one of the voting places that helped decide statehood for California, and later a post office and a stagecoach stop. Their timeline dates the first stagecoach horse-change at the Casa de Dana barn to 1857 — after a speaking year of 1850.",
    topics: [
      "1849",
      "voting",
      "statehood",
      "polling place",
      "post office",
      "stagecoach",
      "1857",
    ],
    dateRange: "1849-1857",
    sourceType: "secondary",
    citation:
      "Dana Adobe, Gladys Norton, 'Looking Back' (1956), and site timeline, on danaadobe.org.",
    url: DANA_NORTON,
    reliability: "medium",
  },
  {
    id: "partner-hutton-1850",
    text: "Dana Adobe publishes Gladys Norton quoting William Rich Hutton's 1850 letter from Nipomo: he found Captain Dana an excellent good-natured old gentleman; they treated him kindly and lived very comfortably; the farm about ten miles long and nearly as broad, a third hilly; air filled with fragrance of clover, oats four feet high in places; about thirty or forty tame cows, lots of milk and fresh butter. Hutton was surveying the rancho (partner timeline: first survey 1850). He also wrote that Mrs. Tefft (the daughter María Josefa Dana, married to Henry Amos Tefft) was a favorite with all who know her. Norton notes that when guests assembled in numbers, as at that wedding, they passed the night on saddle blankets on the front porch. Do not treat Norton's later Fremont / San Marcos Pass story (from Juan Francisco Dana, 1931) as firsthand in this pack.",
    topics: [
      "hutton",
      "1850",
      "survey",
      "cows",
      "butter",
      "tefft",
      "hospitality",
      "character",
    ],
    dateRange: "1850",
    sourceType: "secondary",
    citation:
      "Dana Adobe, Gladys Norton, 'Looking Back' (1956), quoting William Rich Hutton (1850), on danaadobe.org.",
    url: DANA_NORTON,
    reliability: "medium",
  },
  {
    id: "partner-portraits",
    text: "Dana Adobe publishes oval portraits of Captain William Goodwin Dana and María Josefa Carrillo Dana on its Dana Family page. Those are the likenesses used for these figures. The photographs show them later than a speaking year of 1850; say so if asked. They are not pictures of the adobe.",
    topics: ["portrait", "likeness", "appearance", "family page"],
    dateRange: "mid-to-late 19th century",
    sourceType: "secondary",
    citation: "Dana Adobe, Dana Family page, portraits of Captain Dana and María Josefa.",
    url: DANA_FAMILY,
    reliability: "high",
  },
  {
    id: "partner-diseno",
    text: "Dana Adobe publishes a 'Plan of the Rancho of Nipomo' on its history page: area 37,887 91/100 acres, claimant William G. Dana. That figure matches Angel and the California landmark. Their home page still says the rancho was initially more than 48,000 acres — contested. Prefer ~38,000 / 37,887.91 and say the partner home page uses a larger first figure.",
    topics: [
      "acres",
      "acreage",
      "37887",
      "diseno",
      "map",
      "plan of the rancho",
      "grant size",
    ],
    dateRange: "1837-1850",
    sourceType: "secondary",
    citation:
      "Dana Adobe, History page gallery, Plan of the Rancho of Nipomo (37,887.91 acres, William G. Dana claimant).",
    url: DANA_HISTORY,
    reliability: "high",
  },
];
