import type {
  PersonaSemanticVocab,
  SourceSemanticAnnotations,
} from "@/lib/semantic";

/** Controlled vocabulary for John Muir. */
export const muirVocab: PersonaSemanticVocab = {
  people: [
    {
      id: "john-muir",
      label: "John Muir",
      aliases: ["muir", "john of the mountains"],
    },
    {
      id: "louie-strentzel-muir",
      label: "Louie Wanda Strentzel",
      aliases: ["louie muir", "louie strentzel", "strentzel"],
    },
    {
      id: "theodore-roosevelt",
      label: "Theodore Roosevelt",
      aliases: ["roosevelt", "president roosevelt", "teddy roosevelt"],
    },
    {
      id: "robert-underwood-johnson",
      label: "Robert Underwood Johnson",
      aliases: ["underwood johnson", "r.u. johnson", "robert underwood johnson"],
    },
    {
      id: "josiah-whitney",
      label: "Josiah Dwight Whitney",
      aliases: ["j.d. whitney", "josiah whitney", "state geologist whitney", "josiah dwight whitney"],
    },
    {
      id: "pat-delaney",
      label: "Pat Delaney",
      aliases: ["delaney"],
    },
    {
      id: "billy-herder",
      label: "Billy",
      aliases: ["billy the herder", "herder billy"],
    },
    {
      id: "james-mason-hutchings",
      label: "James Mason Hutchings",
      aliases: ["hutchings"],
    },
    {
      id: "tenaya",
      label: "Tenaya",
      aliases: ["chief tenaya", "ahwahneechee leader tenaya"],
    },
  ],
  places: [
    {
      id: "dunbar",
      label: "Dunbar",
      aliases: ["dunbar scotland", "scotland"],
    },
    {
      id: "wisconsin",
      label: "Wisconsin",
      aliases: [],
    },
    {
      id: "san-francisco",
      label: "San Francisco",
      aliases: ["sf"],
    },
    {
      id: "martinez",
      label: "Martinez",
      aliases: ["alhambra valley", "muir ranch"],
    },
    {
      id: "yosemite-valley",
      label: "Yosemite Valley",
      aliases: ["yosemite", "the valley"],
    },
    {
      id: "sierra-nevada",
      label: "Sierra Nevada",
      aliases: ["sierra", "high sierra", "range of light"],
    },
    {
      id: "yosemite-falls",
      label: "Yosemite Falls",
      aliases: ["yosemite fall", "upper fall", "lower fall"],
    },
    {
      id: "el-capitan",
      label: "El Capitan",
      aliases: [],
    },
    {
      id: "half-dome",
      label: "Half Dome",
      aliases: [],
    },
    {
      id: "bridalveil-fall",
      label: "Bridalveil Fall",
      aliases: ["bridalveil", "pohono", "bridal veil"],
    },
    {
      id: "glacier-point",
      label: "Glacier Point",
      aliases: [],
    },
    {
      id: "hetch-hetchy",
      label: "Hetch Hetchy",
      aliases: ["hetch hetchy valley", "tuolumne yosemite"],
    },
    {
      id: "tuolumne",
      label: "Tuolumne",
      aliases: ["tuolumne river", "tuolumne meadows", "tuolumne basin"],
    },
    {
      id: "mariposa-grove",
      label: "Mariposa Grove",
      aliases: ["mariposa", "grizzly giant"],
    },
    {
      id: "mount-lyell",
      label: "Mount Lyell",
      aliases: ["lyell"],
    },
    {
      id: "merced-river",
      label: "Merced River",
      aliases: ["merced", "merced canyon"],
    },
    {
      id: "vernal-fall",
      label: "Vernal Fall",
      aliases: ["vernal"],
    },
    {
      id: "nevada-fall",
      label: "Nevada Fall",
      aliases: ["nevada"],
    },
    {
      id: "tenaya-lake",
      label: "Tenaya Lake",
      aliases: ["tenaya canyon"],
    },
    {
      id: "yellowstone",
      label: "Yellowstone",
      aliases: ["yellowstone national park"],
    },
    {
      id: "owens-valley",
      label: "Owens Valley",
      aliases: ["lone pine", "owens valley earthquake"],
    },
    {
      id: "coulterville",
      label: "Coulterville",
      aliases: ["coulterville road"],
    },
    {
      id: "big-oak-flat",
      label: "Big Oak Flat",
      aliases: ["big oak flat road"],
    },
    {
      id: "tioga-pass",
      label: "Tioga Pass",
      aliases: ["tioga", "mono"],
    },
    {
      id: "los-angeles",
      label: "Los Angeles",
      aliases: ["la"],
    },
    {
      id: "mist-trail",
      label: "Mist Trail",
      aliases: [],
    },
  ],
  organizations: [
    {
      id: "sierra-club",
      label: "Sierra Club",
      aliases: ["the club"],
    },
    {
      id: "century-magazine",
      label: "The Century Magazine",
      aliases: ["century", "the century"],
    },
    {
      id: "yosemite-national-park",
      label: "Yosemite National Park",
      aliases: ["yosemite park", "the park"],
    },
    {
      id: "california-geological-survey",
      label: "California Geological Survey",
      aliases: ["state geological survey", "whitney survey"],
    },
  ],
  events: [
    {
      id: "first-summer-1869",
      label: "First summer in the Sierra 1869",
      aliases: ["sheep summer", "1869 summer", "my first summer"],
    },
    {
      id: "yosemite-grant-1864",
      label: "Yosemite Grant 1864",
      aliases: ["yosemite grant", "1864 grant"],
    },
    {
      id: "yosemite-national-park-1890",
      label: "Yosemite National Park 1890",
      aliases: ["1890 park", "park establishment", "yosemite park act"],
    },
    {
      id: "glacial-theory-dispute",
      label: "Glacial theory dispute",
      aliases: ["whitney dispute", "catastrophe theory", "glacier controversy"],
    },
    {
      id: "roosevelt-camping-1903",
      label: "Roosevelt camping trip 1903",
      aliases: ["roosevelt 1903", "glacier point camping", "wilderness conference"],
    },
    {
      id: "hetch-hetchy-fight",
      label: "Hetch Hetchy fight",
      aliases: ["hetch hetchy dam", "san francisco water", "dam fight"],
    },
    {
      id: "the-yosemite-book",
      label: "The Yosemite (1912 book)",
      aliases: [
        "the yosemite",
        "published the yosemite",
        "your book the yosemite",
        "yosemite book",
      ],
    },
    {
      id: "california-arrival-1868",
      label: "Arrival in California 1868",
      aliases: [
        "first reach california",
        "reached california",
        "came to california",
        "1868 california",
      ],
    },
    {
      id: "raker-act-1913",
      label: "Raker Act 1913",
      aliases: ["raker act", "1913 dam authorization"],
    },
    {
      id: "earthquake-1872",
      label: "1872 Owens Valley earthquake",
      aliases: ["1872 earthquake", "lone pine earthquake", "yosemite earthquake"],
    },
    {
      id: "sierra-club-founding",
      label: "Sierra Club founding",
      aliases: ["1892", "club founding"],
    },
    {
      id: "hoofed-locusts",
      label: "Hoofed locusts (sheep damage)",
      aliases: ["sheep damage", "meadow damage", "domestic sheep"],
    },
  ],
  periods: [
    {
      id: "boyhood-emigration",
      label: "Boyhood and emigration",
      yearStart: 1838,
      yearEnd: 1867,
      aliases: ["scotland", "wisconsin years", "youth"],
    },
    {
      id: "sierra-discovery",
      label: "Sierra discovery years",
      yearStart: 1868,
      yearEnd: 1879,
      aliases: ["early yosemite", "first sierra years", "glacier study years"],
    },
    {
      id: "conservation-advocacy",
      label: "Conservation advocacy era",
      yearStart: 1880,
      yearEnd: 1901,
      aliases: ["park campaigns", "magazine advocacy", "sierra club years"],
    },
    {
      id: "late-advocacy-1912",
      label: "Late advocacy (speaking year)",
      yearStart: 1902,
      yearEnd: 1912,
      aliases: ["hetch hetchy years", "1912 voice", "elderly muir"],
    },
  ],
};

/** Hand tags for curated John Muir sources. */
export const muirSourceAnnotations: SourceSemanticAnnotations = {
  "bio-birth": {
    people: ["john-muir"],
    places: ["dunbar", "wisconsin"],
    yearStart: 1838,
    yearEnd: 1849,
    period: "boyhood-emigration",
  },
  "bio-california-1868": {
    people: ["john-muir"],
    places: ["san-francisco", "sierra-nevada", "yosemite-valley"],
    events: ["california-arrival-1868"],
    yearStart: 1868,
    yearEnd: 1868,
    period: "sierra-discovery",
  },
  "bio-elderly-1912": {
    people: ["john-muir"],
    places: ["yosemite-valley", "sierra-nevada"],
    organizations: ["sierra-club"],
    yearStart: 1912,
    yearEnd: 1912,
    period: "late-advocacy-1912",
  },
  "bio-death-note": {
    people: ["john-muir"],
    places: ["los-angeles"],
    yearStart: 1914,
    yearEnd: 1914,
  },
  "bio-martinez-brief": {
    people: ["john-muir", "louie-strentzel-muir"],
    places: ["martinez", "sierra-nevada"],
    yearStart: 1880,
    yearEnd: 1909,
    period: "conservation-advocacy",
  },
  "bio-sierra-club": {
    people: ["john-muir"],
    places: ["yosemite-valley", "sierra-nevada"],
    organizations: ["sierra-club"],
    events: ["sierra-club-founding"],
    yearStart: 1892,
    yearEnd: 1912,
    period: "conservation-advocacy",
  },
  "sierra-first-summer-1869": {
    people: ["john-muir"],
    places: ["sierra-nevada", "yosemite-valley"],
    events: ["first-summer-1869"],
    yearStart: 1869,
    yearEnd: 1911,
    period: "sierra-discovery",
  },
  "sierra-sheep-delaney": {
    people: ["john-muir", "pat-delaney", "billy-herder"],
    places: ["sierra-nevada"],
    events: ["first-summer-1869", "hoofed-locusts"],
    yearStart: 1869,
    yearEnd: 1869,
    period: "sierra-discovery",
  },
  "sierra-botany-enthusiasm": {
    people: ["john-muir"],
    places: ["sierra-nevada"],
    events: ["first-summer-1869"],
    yearStart: 1869,
    yearEnd: 1911,
    period: "sierra-discovery",
  },
  "sierra-range-of-light": {
    people: ["john-muir"],
    places: ["sierra-nevada"],
    yearStart: 1894,
    yearEnd: 1894,
    period: "conservation-advocacy",
  },
  "yosemite-first-sight": {
    people: ["john-muir"],
    places: ["yosemite-valley", "merced-river"],
    yearStart: 1868,
    yearEnd: 1912,
    period: "sierra-discovery",
  },
  "yosemite-falls": {
    people: ["john-muir"],
    places: ["yosemite-falls", "yosemite-valley"],
    yearStart: 1868,
    yearEnd: 1912,
    period: "sierra-discovery",
  },
  "yosemite-el-capitan-half-dome": {
    people: ["john-muir"],
    places: ["el-capitan", "half-dome", "yosemite-valley"],
    yearStart: 1868,
    yearEnd: 1912,
    period: "sierra-discovery",
  },
  "yosemite-bridalveil": {
    people: ["john-muir"],
    places: ["bridalveil-fall", "el-capitan", "yosemite-valley"],
    yearStart: 1860,
    yearEnd: 1912,
    period: "sierra-discovery",
  },
  "yosemite-national-park-1890": {
    people: ["john-muir", "robert-underwood-johnson"],
    places: ["yosemite-valley", "mariposa-grove"],
    organizations: ["yosemite-national-park", "century-magazine"],
    events: ["yosemite-grant-1864", "yosemite-national-park-1890"],
    yearStart: 1864,
    yearEnd: 1890,
    period: "conservation-advocacy",
  },
  "glacier-theory": {
    people: ["john-muir"],
    places: ["yosemite-valley", "sierra-nevada"],
    events: ["glacial-theory-dispute"],
    yearStart: 1870,
    yearEnd: 1894,
    period: "sierra-discovery",
  },
  "glacier-whitney-contested": {
    people: ["john-muir", "josiah-whitney"],
    places: ["yosemite-valley"],
    organizations: ["california-geological-survey"],
    events: ["glacial-theory-dispute"],
    yearStart: 1870,
    yearEnd: 1879,
    period: "sierra-discovery",
  },
  "glacier-living-ice": {
    people: ["john-muir"],
    places: ["mount-lyell", "sierra-nevada"],
    yearStart: 1870,
    yearEnd: 1894,
    period: "sierra-discovery",
  },
  "sequoia-mariposa-grove": {
    people: ["john-muir"],
    places: ["mariposa-grove", "sierra-nevada"],
    yearStart: 1868,
    yearEnd: 1912,
    period: "conservation-advocacy",
  },
  "forest-preservation": {
    people: ["john-muir"],
    places: ["sierra-nevada"],
    yearStart: 1890,
    yearEnd: 1912,
    period: "conservation-advocacy",
  },
  "roosevelt-1903": {
    people: ["john-muir", "theodore-roosevelt"],
    places: ["glacier-point", "yosemite-valley"],
    events: ["roosevelt-camping-1903"],
    yearStart: 1903,
    yearEnd: 1903,
    period: "late-advocacy-1912",
  },
  "hetch-hetchy-valley": {
    people: ["john-muir"],
    places: ["hetch-hetchy", "tuolumne", "yosemite-valley"],
    organizations: ["yosemite-national-park"],
    events: ["hetch-hetchy-fight"],
    yearStart: 1900,
    yearEnd: 1912,
    period: "late-advocacy-1912",
  },
  "hetch-hetchy-fight": {
    people: ["john-muir"],
    places: ["hetch-hetchy", "san-francisco"],
    organizations: ["sierra-club", "yosemite-national-park"],
    events: ["hetch-hetchy-fight"],
    yearStart: 1900,
    yearEnd: 1913,
    period: "late-advocacy-1912",
  },
  "hetch-hetchy-outcome-note": {
    people: ["john-muir"],
    places: ["hetch-hetchy"],
    events: ["hetch-hetchy-fight", "raker-act-1913"],
    yearStart: 1913,
    yearEnd: 1913,
  },
  "books-mountains-of-california": {
    people: ["john-muir"],
    places: ["sierra-nevada"],
    yearStart: 1894,
    yearEnd: 1894,
    period: "conservation-advocacy",
  },
  "books-my-first-summer": {
    people: ["john-muir"],
    places: ["sierra-nevada", "yosemite-valley"],
    events: ["first-summer-1869"],
    yearStart: 1911,
    yearEnd: 1911,
    period: "late-advocacy-1912",
  },
  "books-the-yosemite": {
    people: ["john-muir"],
    places: ["yosemite-valley", "hetch-hetchy"],
    events: ["hetch-hetchy-fight", "the-yosemite-book"],
    yearStart: 1912,
    yearEnd: 1912,
    period: "late-advocacy-1912",
  },
  "sierra-geography": {
    people: ["john-muir"],
    places: ["sierra-nevada", "yosemite-valley"],
    period: "sierra-discovery",
  },
  "yosemite-native-peoples": {
    people: ["tenaya"],
    places: ["yosemite-valley", "sierra-nevada"],
  },
  "sierra-passes-travel": {
    people: ["john-muir"],
    places: [
      "yosemite-valley",
      "coulterville",
      "mariposa-grove",
      "big-oak-flat",
    ],
    yearStart: 1860,
    yearEnd: 1899,
    period: "sierra-discovery",
  },
  "books-composite-memory": {
    people: ["john-muir"],
    places: ["sierra-nevada"],
    events: ["first-summer-1869"],
    yearStart: 1869,
    yearEnd: 1911,
    period: "sierra-discovery",
  },
  "sierra-wild-sheep": {
    people: ["john-muir"],
    places: ["sierra-nevada"],
    events: ["hoofed-locusts"],
    yearStart: 1894,
    yearEnd: 1894,
    period: "conservation-advocacy",
  },
  "yosemite-waterfalls-spring": {
    people: ["john-muir"],
    places: ["yosemite-valley", "yosemite-falls"],
    yearStart: 1868,
    yearEnd: 1912,
    period: "sierra-discovery",
  },
  "books-our-national-parks": {
    people: ["john-muir"],
    places: ["yosemite-valley", "yellowstone"],
    organizations: ["century-magazine", "yosemite-national-park"],
    yearStart: 1901,
    yearEnd: 1901,
    period: "conservation-advocacy",
  },
  "yosemite-dedication-johnson": {
    people: ["john-muir", "robert-underwood-johnson"],
    places: ["yosemite-valley"],
    organizations: ["century-magazine", "yosemite-national-park"],
    events: ["yosemite-national-park-1890"],
    yearStart: 1890,
    yearEnd: 1912,
    period: "conservation-advocacy",
  },
  "yosemite-vernal-nevada-falls": {
    people: ["john-muir"],
    places: [
      "vernal-fall",
      "nevada-fall",
      "mist-trail",
      "merced-river",
      "yosemite-valley",
    ],
    yearStart: 1868,
    yearEnd: 1912,
    period: "sierra-discovery",
  },
  "yosemite-tuolumne-meadows": {
    people: ["john-muir"],
    places: ["tuolumne", "sierra-nevada", "hetch-hetchy"],
    yearStart: 1869,
    yearEnd: 1912,
    period: "sierra-discovery",
  },
  "yosemite-tenaya": {
    people: ["john-muir", "tenaya"],
    places: ["tenaya-lake", "sierra-nevada", "yosemite-valley"],
    yearStart: 1869,
    yearEnd: 1912,
    period: "sierra-discovery",
  },
  "sierra-hoofed-locusts": {
    people: ["john-muir"],
    places: ["sierra-nevada"],
    events: ["hoofed-locusts", "first-summer-1869"],
    yearStart: 1869,
    yearEnd: 1901,
    period: "sierra-discovery",
  },
  "yosemite-hutchings-sawmill": {
    people: ["john-muir", "james-mason-hutchings"],
    places: ["yosemite-valley"],
    yearStart: 1869,
    yearEnd: 1879,
    period: "sierra-discovery",
  },
  "yosemite-earthquake-1872": {
    people: ["john-muir"],
    places: ["yosemite-valley", "owens-valley"],
    events: ["earthquake-1872"],
    yearStart: 1872,
    yearEnd: 1872,
    period: "sierra-discovery",
  },
  "yosemite-grant-1864": {
    people: ["john-muir"],
    places: ["yosemite-valley", "mariposa-grove"],
    organizations: ["yosemite-national-park"],
    events: ["yosemite-grant-1864", "yosemite-national-park-1890"],
    yearStart: 1864,
    yearEnd: 1890,
    period: "conservation-advocacy",
  },
  "parks-yellowstone-brief": {
    people: ["john-muir"],
    places: ["yellowstone", "sierra-nevada", "yosemite-valley"],
    yearStart: 1901,
    yearEnd: 1901,
    period: "conservation-advocacy",
  },
  "hetch-hetchy-tuolumne-yosemite": {
    people: ["john-muir"],
    places: ["hetch-hetchy", "tuolumne", "yosemite-valley"],
    organizations: ["yosemite-national-park"],
    events: ["hetch-hetchy-fight"],
    yearStart: 1900,
    yearEnd: 1912,
    period: "late-advocacy-1912",
  },
  "sierra-pass-walker-tioga": {
    people: ["john-muir"],
    places: ["tioga-pass", "sierra-nevada"],
    yearStart: 1870,
    yearEnd: 1912,
    period: "sierra-discovery",
  },
};
