import type { ImageTopic } from "@/personas/types";

export const MARIA_JOSEFA_CARRILLO_IMAGE_TOPICS: ImageTopic[] = [
  {
    key: "identity",
    label: "María Josefa — who she is",
    buzzwords: [
      "who are you",
      "introduce yourself",
      "maria josefa",
      "carrillo",
      "portrait",
      "likeness",
      "biography",
      "myself",
      "i am",
    ],
    imageIds: ["img-portrait"],
  },
  {
    key: "grant-map",
    label: "Rancho Nipomo grant / acreage",
    buzzwords: [
      "acres",
      "acreage",
      "37,887",
      "diseño",
      "diseno",
      "grant map",
      "plan of the rancho",
    ],
    imageIds: ["img-diseno"],
  },
  {
    key: "adobe",
    label: "The Nipomo adobe",
    buzzwords: [
      "adobe",
      "casa de dana",
      "thirteen rooms",
      "u-shape",
      "u-shaped",
      "salon",
      "show me the house",
      "picture of the adobe",
    ],
    imageIds: [
      "img-adobe-vineyard",
      "img-adobe-oxcart",
      "img-adobe-salon",
      "img-adobe-1900",
      "img-adobe-1900-porch",
      "img-adobe-restored",
    ],
  },
  {
    key: "hospitality",
    label: "Hostess on El Camino Real",
    buzzwords: [
      "hospitality",
      "travelers",
      "welcome",
      "el camino real",
      "bryant",
      "hostess",
    ],
    imageIds: ["img-adobe-salon", "img-adobe-vineyard"],
  },
  {
    key: "santa-barbara",
    label: "Santa Barbara and the Carrillos",
    buzzwords: [
      "santa barbara",
      "carrillo",
      "birth",
      "marriage",
      "presidio",
      "mission santa barbara",
      "father",
    ],
    imageIds: ["img-mission-sb"],
  },
  {
    key: "mission-slo",
    label: "Mission San Luis Obispo",
    buzzwords: [
      "mission san luis obispo",
      "san luis obispo",
      "tolosa",
    ],
    imageIds: ["img-mission-slo-front"],
  },
  {
    key: "rancho-cattle",
    label: "Rancho life",
    buzzwords: ["cattle", "vaquero", "horses", "californio"],
    imageIds: ["img-vaqueros", "img-adobe-oxcart"],
  },
  {
    key: "chumash",
    label: "Chumash people of this coast",
    buzzwords: [
      "chumash people",
      "chumash village",
      "indigenous people",
      "1804",
      "la purisima",
      "la purísima",
    ],
    imageIds: ["img-chumash-cave"],
  },
  {
    key: "tomol",
    label: "Chumash tomol (only if asked)",
    buzzwords: ["tomol", "plank canoe"],
    imageIds: ["img-chumash-tomol"],
  },
];
