import type {
  PersonaSemanticVocab,
  SourceSemanticAnnotations,
} from "@/lib/semantic";

/** Controlled vocabulary for Hubert Howe Bancroft. */
export const bancroftVocab: PersonaSemanticVocab = {
  people: [
    {
      id: "hubert-howe-bancroft",
      label: "Hubert Howe Bancroft",
      aliases: [
        "bancroft",
        "h.h. bancroft",
        "h. h. bancroft",
        "hubert bancroft",
      ],
    },
    {
      id: "azariah-ashley-bancroft",
      label: "Azariah Ashley Bancroft",
      aliases: ["azariah bancroft", "ashley bancroft", "father"],
    },
    {
      id: "lucy-howe-bancroft",
      label: "Lucy Howe Bancroft",
      aliases: ["lucy bancroft", "lucy howe", "mother"],
    },
    {
      id: "a-l-bancroft",
      label: "A.L. Bancroft",
      aliases: ["a.l. bancroft", "al bancroft", "brother"],
    },
    {
      id: "george-h-derby",
      label: "George H. Derby",
      aliases: ["derby", "george derby", "brother-in-law"],
    },
    {
      id: "emily-ketchum",
      label: "Emily Ketchum",
      aliases: ["emily bancroft", "first wife"],
    },
    {
      id: "matilda-griffing",
      label: "Matilda Coley Griffing",
      aliases: ["matilda bancroft", "matilda griffing", "second wife"],
    },
    {
      id: "kate-bancroft",
      label: "Kate Bancroft",
      aliases: ["kate", "daughter kate"],
    },
    {
      id: "frances-fuller-victor",
      label: "Frances Fuller Victor",
      aliases: ["victor", "frances victor", "fuller victor"],
    },
    {
      id: "mariano-vallejo",
      label: "Mariano Guadalupe Vallejo",
      aliases: ["vallejo", "general vallejo", "mariano vallejo"],
    },
    {
      id: "francis-parkman",
      label: "Francis Parkman",
      aliases: ["parkman"],
    },
  ],
  places: [
    {
      id: "granville-ohio",
      label: "Granville, Ohio",
      aliases: ["granville", "ohio"],
    },
    {
      id: "buffalo",
      label: "Buffalo",
      aliases: ["buffalo new york"],
    },
    {
      id: "san-francisco",
      label: "San Francisco",
      aliases: ["sf", "montgomery street", "market street"],
    },
    {
      id: "montgomery-street",
      label: "Montgomery Street",
      aliases: ["montgomery"],
    },
    {
      id: "spring-valley",
      label: "Spring Valley",
      aliases: ["spring valley ranch", "san diego county", "bancroft ranch"],
    },
    {
      id: "berkeley",
      label: "Berkeley",
      aliases: ["uc berkeley", "university of california"],
    },
    {
      id: "yale",
      label: "Yale",
      aliases: ["yale university", "new haven"],
    },
    {
      id: "mission-dolores",
      label: "Mission Dolores",
      aliases: [
        "mission san francisco",
        "mission san francisco de asis",
        "mission dolores",
      ],
    },
    {
      id: "golden-gate",
      label: "Golden Gate",
      aliases: ["golden gate strait", "san francisco bay", "the gate"],
    },
    {
      id: "telegraph-hill",
      label: "Telegraph Hill",
      aliases: ["telegraph hill"],
    },
    {
      id: "angel-island",
      label: "Angel Island",
      aliases: ["angel island"],
    },
    {
      id: "pacific-states",
      label: "Pacific States",
      aliases: ["pacific coast", "west", "alaska to panama"],
    },
    {
      id: "california",
      label: "California",
      aliases: ["the state", "alta california"],
    },
  ],
  organizations: [
    {
      id: "bancroft-publishing",
      label: "Bancroft publishing firm",
      aliases: [
        "bancroft company",
        "a.l. bancroft",
        "a.l. bancroft & company",
        "bookstore",
      ],
    },
    {
      id: "bancroft-library",
      label: "The Bancroft Library",
      aliases: ["bancroft library", "his library", "historical library"],
    },
    {
      id: "university-of-california",
      label: "University of California",
      aliases: ["uc", "uc berkeley", "university"],
    },
    {
      id: "yale-university",
      label: "Yale University",
      aliases: ["yale"],
    },
    {
      id: "american-antiquarian-society",
      label: "American Antiquarian Society",
      aliases: ["antiquarian society", "aas"],
    },
    {
      id: "doane-academy",
      label: "Doane Academy",
      aliases: ["doane"],
    },
    {
      id: "underground-railroad",
      label: "Underground Railroad",
      aliases: ["underground railroad", "abolition"],
    },
  ],
  events: [
    {
      id: "gold-rush",
      label: "Gold Rush",
      aliases: ["california gold rush", "forty-niners", "1849", "gold rush"],
    },
    {
      id: "library-sale-1905",
      label: "Library sale to UC",
      aliases: [
        "sold the library",
        "university purchase",
        "1905 sale",
        "250000",
      ],
    },
    {
      id: "literary-factory",
      label: "Literary factory",
      aliases: [
        "literary industries",
        "research assistants",
        "workshop",
        "compilation",
      ],
    },
    {
      id: "publishing-fire-1886",
      label: "1886 publishing fire",
      aliases: ["fire", "burned", "sheets destroyed"],
    },
    {
      id: "native-races-publication",
      label: "Native Races publication",
      aliases: ["native races", "ethnology volumes", "yale degree"],
    },
    {
      id: "mission-founding",
      label: "Mission founding",
      aliases: ["mission founded", "1776", "spanish missions"],
    },
    {
      id: "oral-dictations",
      label: "Oral dictations",
      aliases: ["dictations", "oral histories", "pioneer interviews"],
    },
  ],
  periods: [
    {
      id: "ohio-youth",
      label: "Ohio youth",
      yearStart: 1832,
      yearEnd: 1852,
      aliases: ["early life", "before california", "buffalo years"],
    },
    {
      id: "sf-bookselling",
      label: "San Francisco bookselling",
      yearStart: 1852,
      yearEnd: 1868,
      aliases: ["publishing years", "montgomery street years"],
    },
    {
      id: "history-workshop",
      label: "History workshop years",
      yearStart: 1868,
      yearEnd: 1890,
      aliases: ["literary factory era", "works years", "collecting era"],
    },
    {
      id: "spanish-mission",
      label: "Spanish mission era",
      yearStart: 1769,
      yearEnd: 1821,
      aliases: ["spanish period", "mission era", "spanish era"],
    },
    {
      id: "gold-rush-era",
      label: "Gold Rush era",
      yearStart: 1848,
      yearEnd: 1859,
      aliases: ["gold rush years", "forty-niner years"],
    },
    {
      id: "library-sale-era",
      label: "Library sale era",
      yearStart: 1900,
      yearEnd: 1905,
      aliases: ["1905", "uc sale years", "speaking year"],
    },
  ],
};

/** Hand tags for curated Bancroft sources. */
export const bancroftSourceAnnotations: SourceSemanticAnnotations = {
  "bio-birth": {
    people: [
      "hubert-howe-bancroft",
      "azariah-ashley-bancroft",
      "lucy-howe-bancroft",
    ],
    places: ["granville-ohio"],
    yearStart: 1832,
    yearEnd: 1832,
    period: "ohio-youth",
  },
  "bio-abolitionist-family": {
    people: [
      "hubert-howe-bancroft",
      "azariah-ashley-bancroft",
      "lucy-howe-bancroft",
    ],
    places: ["granville-ohio"],
    organizations: ["underground-railroad"],
    yearStart: 1830,
    yearEnd: 1849,
    period: "ohio-youth",
  },
  "bio-education-bookstore": {
    people: ["hubert-howe-bancroft", "george-h-derby"],
    places: ["granville-ohio", "buffalo"],
    organizations: ["doane-academy", "bancroft-publishing"],
    yearStart: 1840,
    yearEnd: 1852,
    period: "ohio-youth",
  },
  "bio-sf-1852": {
    people: ["hubert-howe-bancroft"],
    places: ["san-francisco", "buffalo"],
    organizations: ["bancroft-publishing"],
    events: ["gold-rush"],
    yearStart: 1852,
    yearEnd: 1852,
    period: "sf-bookselling",
  },
  "bio-publishing-firm": {
    people: ["hubert-howe-bancroft"],
    places: ["san-francisco", "montgomery-street"],
    organizations: ["bancroft-publishing"],
    yearStart: 1855,
    yearEnd: 1868,
    period: "sf-bookselling",
  },
  "bio-resign-1868": {
    people: ["hubert-howe-bancroft", "a-l-bancroft"],
    places: ["san-francisco"],
    organizations: ["bancroft-publishing", "bancroft-library"],
    yearStart: 1868,
    yearEnd: 1868,
    period: "history-workshop",
  },
  "bio-marriages": {
    people: [
      "hubert-howe-bancroft",
      "emily-ketchum",
      "matilda-griffing",
      "kate-bancroft",
    ],
    yearStart: 1859,
    yearEnd: 1879,
  },
  "bio-yale-ma": {
    people: ["hubert-howe-bancroft"],
    places: ["yale"],
    organizations: ["yale-university", "american-antiquarian-society"],
    events: ["native-races-publication"],
    yearStart: 1875,
    yearEnd: 1875,
    period: "history-workshop",
  },
  "bio-spring-valley-ranch": {
    people: ["hubert-howe-bancroft"],
    places: ["spring-valley"],
    yearStart: 1885,
    yearEnd: 1885,
  },
  "library-collecting-start": {
    people: ["hubert-howe-bancroft"],
    places: ["california", "pacific-states"],
    organizations: ["bancroft-library"],
    yearStart: 1859,
    yearEnd: 1859,
    period: "sf-bookselling",
  },
  "library-contents": {
    people: ["hubert-howe-bancroft"],
    organizations: ["bancroft-library"],
    events: ["oral-dictations"],
    yearStart: 1860,
    yearEnd: 1900,
    period: "history-workshop",
  },
  "library-fireproof-1881": {
    people: ["hubert-howe-bancroft"],
    places: ["san-francisco"],
    organizations: ["bancroft-library"],
    yearStart: 1881,
    yearEnd: 1905,
  },
  "library-sale-uc-1905": {
    people: ["hubert-howe-bancroft"],
    places: ["berkeley"],
    organizations: ["bancroft-library", "university-of-california"],
    events: ["library-sale-1905"],
    yearStart: 1905,
    yearEnd: 1905,
    period: "library-sale-era",
  },
  "works-39-volumes": {
    people: ["hubert-howe-bancroft"],
    places: ["pacific-states"],
    events: ["literary-factory"],
    yearStart: 1874,
    yearEnd: 1890,
    period: "history-workshop",
  },
  "works-native-races": {
    people: ["hubert-howe-bancroft", "francis-parkman"],
    places: ["pacific-states", "yale"],
    organizations: ["yale-university"],
    events: ["native-races-publication"],
    yearStart: 1875,
    yearEnd: 1876,
    period: "history-workshop",
  },
  "works-history-california": {
    people: ["hubert-howe-bancroft"],
    places: ["california", "san-francisco"],
    events: ["gold-rush"],
    yearStart: 1884,
    yearEnd: 1890,
    period: "history-workshop",
  },
  "works-pacific-scope": {
    people: ["hubert-howe-bancroft"],
    places: ["pacific-states", "california"],
    yearStart: 1874,
    yearEnd: 1890,
    period: "history-workshop",
  },
  "works-literary-industries": {
    people: ["hubert-howe-bancroft"],
    events: ["literary-factory"],
    yearStart: 1891,
    yearEnd: 1891,
    period: "history-workshop",
  },
  "works-fire-1886": {
    people: ["hubert-howe-bancroft", "a-l-bancroft"],
    places: ["san-francisco"],
    organizations: ["bancroft-publishing"],
    events: ["publishing-fire-1886"],
    yearStart: 1886,
    yearEnd: 1886,
  },
  "philosophy-literary-factory": {
    people: ["hubert-howe-bancroft", "frances-fuller-victor"],
    events: ["literary-factory"],
    yearStart: 1870,
    yearEnd: 1899,
    period: "history-workshop",
  },
  "philosophy-vallejo": {
    people: ["hubert-howe-bancroft", "mariano-vallejo"],
    places: ["california"],
    events: ["literary-factory", "gold-rush", "oral-dictations"],
    yearStart: 1870,
    yearEnd: 1889,
    period: "history-workshop",
  },
  "philosophy-criticism": {
    people: ["hubert-howe-bancroft"],
    events: ["literary-factory"],
    yearStart: 1890,
    yearEnd: 1899,
  },
  "philosophy-method": {
    people: ["hubert-howe-bancroft"],
    places: ["california", "pacific-states"],
    events: ["literary-factory", "oral-dictations"],
    yearStart: 1860,
    yearEnd: 1899,
    period: "history-workshop",
  },
  "sf-gold-rush-arrival": {
    people: ["hubert-howe-bancroft"],
    places: ["san-francisco"],
    organizations: ["bancroft-publishing"],
    events: ["gold-rush"],
    yearStart: 1852,
    yearEnd: 1852,
    period: "sf-bookselling",
  },
  "sf-mission-dolores": {
    places: ["mission-dolores", "san-francisco"],
    events: ["mission-founding"],
    yearStart: 1776,
    yearEnd: 1776,
    period: "spanish-mission",
  },
  "sf-golden-gate-strait": {
    places: ["golden-gate", "telegraph-hill", "angel-island", "san-francisco"],
  },
  "sf-pre-1906-city": {
    places: ["san-francisco"],
    yearStart: 1905,
    yearEnd: 1905,
    period: "library-sale-era",
  },
  "california-gold-rush-context": {
    people: ["hubert-howe-bancroft", "mariano-vallejo"],
    places: ["california", "san-francisco"],
    events: ["gold-rush"],
    yearStart: 1848,
    yearEnd: 1859,
    period: "gold-rush-era",
  },
  "collecting-oral-histories": {
    people: ["hubert-howe-bancroft"],
    places: ["pacific-states"],
    organizations: ["bancroft-library", "university-of-california"],
    events: ["oral-dictations"],
    yearStart: 1860,
    yearEnd: 1889,
    period: "history-workshop",
  },
  "subscription-publishing": {
    people: ["hubert-howe-bancroft"],
    organizations: ["bancroft-publishing"],
    yearStart: 1870,
    yearEnd: 1899,
    period: "history-workshop",
  },
};
