/**
 * Topic → buzzword → image map for Anita Loos.
 */

import type { ImageTopic } from "@/personas/types";

export const LOOS_IMAGE_TOPICS: ImageTopic[] = [
  {
    key: "identity",
    label: "Anita Loos — who she is (portrait)",
    buzzwords: [
      "anita loos",
      "who are you",
      "introduce yourself",
      "portrait",
      "likeness",
      "biography",
      "myself",
      "i am",
      "what do you look like",
      "appearance",
      "your face",
    ],
    imageIds: ["img-portrait", "img-loos-photoplay-1922"],
  },
  {
    key: "emerson-partnership",
    label: "John Emerson collaboration & marriage",
    buzzwords: [
      "john emerson",
      "emerson",
      "mr e",
      "husband",
      "marriage",
      "wedding",
      "collaboration",
      "partner",
    ],
    imageIds: ["img-loos-emerson-1918", "img-wedding-1919"],
  },
  {
    key: "griffith-triangle",
    label: "D. W. Griffith & Triangle",
    buzzwords: [
      "griffith",
      "d w griffith",
      "d.w. griffith",
      "triangle",
      "staff screenwriter",
      "payroll",
      "macbeth",
    ],
    imageIds: ["img-griffith-portrait", "img-triangle-studios", "img-intolerance-babylon"],
  },
  {
    key: "intolerance",
    label: "Intolerance & Babylon set",
    buzzwords: [
      "intolerance",
      "babylon",
      "intertitles",
      "titles",
      "epic",
      "frank woods",
      "sets",
    ],
    imageIds: ["img-intolerance-babylon", "img-intolerance-scene", "img-griffith-portrait"],
  },
  {
    key: "fairbanks",
    label: "Douglas Fairbanks pictures",
    buzzwords: [
      "fairbanks",
      "douglas fairbanks",
      "swashbuckler",
      "adventure",
      "picture in the papers",
      "acrobatics",
      "star",
      "musketeers",
    ],
    imageIds: ["img-fairbanks-1922", "img-fairbanks-zorro"],
  },
  {
    key: "hollywood-place",
    label: "Hollywood as a place (not portrait)",
    buzzwords: [
      "hollywood",
      "hollywood boulevard",
      "what did hollywood",
      "colony",
      "los angeles",
      "streetcar",
      "pacific electric",
      "boulevard",
    ],
    imageIds: [
      "img-hollywood-blvd-1922",
      "img-hollywood-streetcar-1922",
      "img-hollywoodland-sign",
      "img-triangle-studios",
    ],
  },
  {
    key: "studios",
    label: "Studios & Culver City / Triangle plant",
    buzzwords: [
      "studio",
      "studios",
      "culver city",
      "triangle studios",
      "back lot",
      "studio lot",
      "film lot",
      "film plant",
    ],
    imageIds: ["img-triangle-studios", "img-hollywood-blvd-1922"],
  },
  {
    key: "new-york-hat",
    label: "The New York Hat / early scenarios",
    buzzwords: [
      "new york hat",
      "pickford",
      "biograph",
      "first scenario",
      "first film",
      "college boy",
      "breaking into",
    ],
    imageIds: ["img-new-york-hat"],
  },
  {
    key: "blondes-novel",
    label: "Gentlemen Prefer Blondes (novel / satire)",
    buzzwords: [
      "gentlemen prefer blondes",
      "blondes",
      "lorelei",
      "novel",
      "satire",
      "harper's",
      "mencken",
    ],
    imageIds: ["img-blondes-illustration"],
  },
  {
    key: "hollywoodland-sign",
    label: "Hollywoodland sign",
    buzzwords: ["hollywoodland", "hollywood sign", "hollywoodland sign", "hills", "1923"],
    imageIds: ["img-hollywoodland-sign"],
  },
];
