import type {
  PersonaSemanticVocab,
  SourceSemanticAnnotations,
} from "@/lib/semantic";

/** Controlled vocabulary for Anita Loos. */
export const loosVocab: PersonaSemanticVocab = {
  people: [
    {
      id: "anita-loos",
      label: "Anita Loos",
      aliases: ["corinne anita loos", "miss loos", "anita"],
    },
    {
      id: "richard-beers-loos",
      label: "Richard Beers Loos",
      aliases: ["richard loos", "richard beers loos", "father loos"],
    },
    {
      id: "minnie-loos",
      label: "Minnie Loos",
      aliases: [
        "minerva ellen loos",
        "minerva smith",
        "minnie",
        "her mother",
      ],
    },
    {
      id: "gladys-loos",
      label: "Gladys Loos",
      aliases: ["gladys loos", "sister gladys"],
    },
    {
      id: "harry-clifford-loos",
      label: "Harry Clifford Loos",
      aliases: ["harry loos", "brother harry"],
    },
    {
      id: "frank-pallma",
      label: "Frank Pallma Jr.",
      aliases: ["pallma", "frank pallma", "first husband"],
    },
    {
      id: "john-emerson",
      label: "John Emerson",
      aliases: ["john emerson", "mr. e", "mr e"],
    },
    {
      id: "dw-griffith",
      label: "D. W. Griffith",
      aliases: ["d.w. griffith", "d. w. griffith", "david wark griffith"],
    },
    {
      id: "douglas-fairbanks",
      label: "Douglas Fairbanks",
      aliases: ["fairbanks", "doug fairbanks"],
    },
    {
      id: "mary-pickford",
      label: "Mary Pickford",
      aliases: ["pickford"],
    },
    {
      id: "lionel-barrymore",
      label: "Lionel Barrymore",
      aliases: ["barrymore"],
    },
    {
      id: "constance-talmadge",
      label: "Constance Talmadge",
      aliases: ["talmadge", "constance"],
    },
    {
      id: "joseph-schenck",
      label: "Joseph Schenck",
      aliases: ["schenck"],
    },
    {
      id: "marion-davies",
      label: "Marion Davies",
      aliases: ["davies"],
    },
    {
      id: "william-randolph-hearst",
      label: "William Randolph Hearst",
      aliases: ["hearst"],
    },
    {
      id: "frank-crowninshield",
      label: "Frank Crowninshield",
      aliases: ["crowninshield"],
    },
    {
      id: "hl-mencken",
      label: "H. L. Mencken",
      aliases: ["mencken", "h.l. mencken"],
    },
    {
      id: "frances-marion",
      label: "Frances Marion",
      aliases: ["frances marion"],
    },
    {
      id: "thomas-ince",
      label: "Thomas Ince",
      aliases: ["ince"],
    },
    {
      id: "mack-sennett",
      label: "Mack Sennett",
      aliases: ["sennett"],
    },
    {
      id: "edith-wharton",
      label: "Edith Wharton",
      aliases: ["wharton"],
    },
    {
      id: "william-faulkner",
      label: "William Faulkner",
      aliases: ["faulkner"],
    },
    {
      id: "aldous-huxley",
      label: "Aldous Huxley",
      aliases: ["huxley"],
    },
    {
      id: "ralph-barton",
      label: "Ralph Barton",
      aliases: ["ralph barton"],
    },
    {
      id: "frank-e-woods",
      label: "Frank E. Woods",
      aliases: ["frank woods", "frank e. woods"],
    },
    {
      id: "lorelei-lee",
      label: "Lorelei Lee",
      aliases: ["lorelei lee", "lorelei"],
    },
    {
      id: "marilyn-monroe",
      label: "Marilyn Monroe",
      aliases: ["monroe"],
    },
  ],
  places: [
    {
      id: "sisson",
      label: "Sisson",
      aliases: ["mount shasta", "sisson california"],
    },
    {
      id: "san-francisco",
      label: "San Francisco",
      aliases: [],
    },
    {
      id: "san-diego",
      label: "San Diego",
      aliases: ["san diego high school"],
    },
    {
      id: "hollywood",
      label: "Hollywood",
      aliases: ["hollywood colony", "film colony"],
    },
    {
      id: "los-angeles",
      label: "Los Angeles",
      aliases: ["los angeles", "l.a."],
    },
    {
      id: "new-york",
      label: "New York",
      aliases: ["new york city", "nyc", "broadway"],
    },
    {
      id: "long-island",
      label: "Long Island",
      aliases: [],
    },
    {
      id: "paris",
      label: "Paris",
      aliases: [],
    },
    {
      id: "chicago",
      label: "Chicago",
      aliases: [],
    },
    {
      id: "culver-city",
      label: "Culver City",
      aliases: [],
    },
    {
      id: "hollywood-boulevard",
      label: "Hollywood Boulevard",
      aliases: ["hollywood blvd"],
    },
    {
      id: "sunset-boulevard",
      label: "Sunset Boulevard",
      aliases: ["sunset and hollywood"],
    },
    {
      id: "los-feliz",
      label: "Los Feliz",
      aliases: ["babylon set site"],
    },
    {
      id: "bijou-theatre",
      label: "Bijou Theatre",
      aliases: ["bijou"],
    },
  ],
  organizations: [
    {
      id: "biograph",
      label: "Biograph",
      aliases: ["biograph company", "american biograph"],
    },
    {
      id: "lubin",
      label: "Lubin",
      aliases: ["lubin manufacturing"],
    },
    {
      id: "triangle-film",
      label: "Triangle Film Corporation",
      aliases: ["triangle", "triangle film"],
    },
    {
      id: "famous-players-lasky",
      label: "Famous Players–Lasky",
      aliases: ["famous players", "lasky"],
    },
    {
      id: "vanity-fair",
      label: "Vanity Fair",
      aliases: [],
    },
    {
      id: "harpers-bazaar",
      label: "Harper's Bazaar",
      aliases: ["harpers bazaar", "harper's"],
    },
    {
      id: "boni-liveright",
      label: "Boni & Liveright",
      aliases: ["boni and liveright"],
    },
    {
      id: "photoplay",
      label: "Photoplay",
      aliases: ["photoplay magazine"],
    },
    {
      id: "lucy-stone-league",
      label: "Lucy Stone League",
      aliases: ["lucy stone"],
    },
    {
      id: "dramatic-review",
      label: "The Dramatic Review",
      aliases: ["dramatic review"],
    },
    {
      id: "mgm",
      label: "MGM",
      aliases: ["metro-goldwyn-mayer"],
    },
    {
      id: "actors-equity",
      label: "Actors' Equity",
      aliases: ["equity", "actors equity"],
    },
    {
      id: "library-of-congress",
      label: "Library of Congress",
      aliases: ["loc", "name authority file"],
    },
  ],
  events: [
    {
      id: "new-york-hat",
      label: "The New York Hat",
      aliases: ["new york hat", "1912 screenplay"],
    },
    {
      id: "intolerance-1916",
      label: "Intolerance",
      aliases: ["intolerance", "babylon sets"],
    },
    {
      id: "gentlemen-prefer-blondes",
      label: "Gentlemen Prefer Blondes",
      aliases: ["blondes", "lorelei sketches", "prefer blondes"],
    },
    {
      id: "blondes-stage-adaptation",
      label: "Blondes stage adaptation",
      aliases: ["blondes on broadway", "stage blondes"],
    },
    {
      id: "hollywoodland-sign",
      label: "Hollywoodland sign",
      aliases: ["hollywood sign", "hollywoodland"],
    },
    {
      id: "jazz-singer-talkies",
      label: "Talkies / Jazz Singer era",
      aliases: ["talkies", "jazz singer", "sound pictures"],
    },
    {
      id: "san-francisco-fire",
      label: "San Francisco fire",
      aliases: ["1906 fire", "earthquake fire"],
    },
    {
      id: "whole-towns-talking",
      label: "The Whole Town's Talking",
      aliases: ["whole towns talking", "bijou play"],
    },
    {
      id: "actors-equity-strike-1919",
      label: "Actors' Equity strike 1919",
      aliases: ["equity strike", "1919 strike"],
    },
  ],
  periods: [
    {
      id: "california-childhood",
      label: "California childhood",
      yearStart: 1888,
      yearEnd: 1910,
      aliases: ["childhood", "san francisco childhood"],
    },
    {
      id: "silent-era-rise",
      label: "Silent-era screenwriting rise",
      yearStart: 1911,
      yearEnd: 1919,
      aliases: ["silent era", "scenario years", "triangle years"],
    },
    {
      id: "jazz-age-fame",
      label: "Jazz Age literary fame",
      yearStart: 1920,
      yearEnd: 1926,
      aliases: ["jazz age", "blondes years", "1920s fame"],
    },
    {
      id: "post-1926-out-of-scope",
      label: "Post-1926 career (out of scope)",
      yearStart: 1927,
      yearEnd: 1981,
      aliases: ["talkie years", "mgm years", "later career"],
    },
  ],
};

/** Hand tags for curated Anita Loos sources. */
export const loosSourceAnnotations: SourceSemanticAnnotations = {
  "bio-name-pronunciation": {
    people: ["anita-loos"],
    period: "silent-era-rise",
  },
  "bio-birth-contested": {
    people: ["anita-loos"],
    places: ["sisson"],
    organizations: ["library-of-congress"],
    events: ["san-francisco-fire"],
    yearStart: 1888,
    yearEnd: 1893,
    period: "california-childhood",
  },
  "bio-parents-family": {
    people: [
      "anita-loos",
      "richard-beers-loos",
      "minnie-loos",
      "gladys-loos",
      "harry-clifford-loos",
    ],
    yearStart: 1890,
    yearEnd: 1909,
    period: "california-childhood",
  },
  "bio-san-francisco-childhood": {
    people: ["anita-loos", "richard-beers-loos"],
    places: ["san-francisco"],
    organizations: ["dramatic-review"],
    yearStart: 1892,
    yearEnd: 1903,
    period: "california-childhood",
  },
  "bio-child-actress": {
    people: ["anita-loos", "gladys-loos"],
    places: ["san-francisco"],
    yearStart: 1897,
    yearEnd: 1909,
    period: "california-childhood",
  },
  "bio-san-diego": {
    people: ["anita-loos", "richard-beers-loos"],
    places: ["san-diego"],
    yearStart: 1903,
    yearEnd: 1911,
    period: "california-childhood",
  },
  "bio-first-scenarios": {
    people: [
      "anita-loos",
      "dw-griffith",
      "mary-pickford",
      "lionel-barrymore",
    ],
    places: ["san-diego"],
    organizations: ["biograph"],
    events: ["new-york-hat"],
    yearStart: 1911,
    yearEnd: 1912,
    period: "silent-era-rise",
  },
  "bio-prolific-mail": {
    people: ["anita-loos"],
    organizations: ["biograph", "lubin"],
    yearStart: 1912,
    yearEnd: 1915,
    period: "silent-era-rise",
  },
  "bio-pallma-marriage": {
    people: ["anita-loos", "frank-pallma", "minnie-loos"],
    places: ["hollywood"],
    yearStart: 1915,
    yearEnd: 1915,
    period: "silent-era-rise",
  },
  "bio-triangle-payroll": {
    people: ["anita-loos", "dw-griffith", "minnie-loos"],
    places: ["hollywood"],
    organizations: ["triangle-film"],
    yearStart: 1915,
    yearEnd: 1915,
    period: "silent-era-rise",
  },
  "bio-emerson-marriage": {
    people: ["anita-loos", "john-emerson"],
    places: ["long-island", "new-york"],
    organizations: ["lucy-stone-league"],
    yearStart: 1919,
    yearEnd: 1919,
    period: "silent-era-rise",
  },
  "bio-vanity-fair": {
    people: ["anita-loos", "frank-crowninshield"],
    places: ["new-york"],
    organizations: ["vanity-fair"],
    events: ["intolerance-1916"],
    yearStart: 1916,
    yearEnd: 1926,
    period: "jazz-age-fame",
  },
  "bio-speaking-1926": {
    people: ["anita-loos"],
    events: ["gentlemen-prefer-blondes", "blondes-stage-adaptation"],
    yearStart: 1926,
    yearEnd: 1926,
    period: "jazz-age-fame",
  },
  "bio-death-note": {
    people: ["anita-loos"],
    places: ["new-york"],
    organizations: ["library-of-congress"],
    yearStart: 1981,
    yearEnd: 1981,
    period: "post-1926-out-of-scope",
  },
  "film-griffith-staff": {
    people: ["anita-loos", "dw-griffith"],
    organizations: ["triangle-film"],
    yearStart: 1915,
    yearEnd: 1916,
    period: "silent-era-rise",
  },
  "film-intolerance-titles": {
    people: ["anita-loos", "dw-griffith", "frank-e-woods"],
    places: ["new-york"],
    events: ["intolerance-1916"],
    yearStart: 1916,
    yearEnd: 1916,
    period: "silent-era-rise",
  },
  "film-intolerance-epic": {
    people: ["anita-loos", "dw-griffith"],
    places: ["hollywood", "los-angeles", "sunset-boulevard", "hollywood-boulevard"],
    events: ["intolerance-1916"],
    yearStart: 1916,
    yearEnd: 1916,
    period: "silent-era-rise",
  },
  "film-triangle-company": {
    people: ["dw-griffith", "thomas-ince", "mack-sennett", "anita-loos"],
    places: ["culver-city", "los-angeles", "hollywood"],
    organizations: ["triangle-film"],
    yearStart: 1915,
    yearEnd: 1917,
    period: "silent-era-rise",
  },
  "film-griffith-director": {
    people: ["dw-griffith", "anita-loos"],
    places: ["hollywood"],
    organizations: ["biograph", "triangle-film"],
    events: ["intolerance-1916"],
    yearStart: 1910,
    yearEnd: 1919,
    period: "silent-era-rise",
  },
  "film-fairbanks-emerson": {
    people: ["anita-loos", "john-emerson", "douglas-fairbanks", "dw-griffith"],
    organizations: ["triangle-film"],
    yearStart: 1916,
    yearEnd: 1918,
    period: "silent-era-rise",
  },
  "film-picture-in-papers": {
    people: ["anita-loos", "douglas-fairbanks"],
    yearStart: 1916,
    yearEnd: 1916,
    period: "silent-era-rise",
  },
  "film-fairbanks-five": {
    people: ["anita-loos", "john-emerson", "douglas-fairbanks"],
    organizations: ["famous-players-lasky", "photoplay"],
    yearStart: 1916,
    yearEnd: 1918,
    period: "silent-era-rise",
  },
  "film-emerson-credit": {
    people: ["anita-loos", "john-emerson"],
    yearStart: 1910,
    yearEnd: 1929,
    period: "jazz-age-fame",
  },
  "film-breaking-into-movies": {
    people: ["anita-loos", "john-emerson"],
    yearStart: 1920,
    yearEnd: 1921,
    period: "jazz-age-fame",
  },
  "film-talmadge-schenck": {
    people: [
      "anita-loos",
      "john-emerson",
      "constance-talmadge",
      "joseph-schenck",
    ],
    places: ["new-york", "paris"],
    organizations: ["famous-players-lasky"],
    yearStart: 1919,
    yearEnd: 1920,
    period: "jazz-age-fame",
  },
  "film-davies-hears": {
    people: [
      "anita-loos",
      "john-emerson",
      "marion-davies",
      "william-randolph-hearst",
    ],
    yearStart: 1919,
    yearEnd: 1919,
    period: "silent-era-rise",
  },
  "film-whole-towns-talking": {
    people: ["anita-loos", "john-emerson"],
    places: ["new-york", "bijou-theatre"],
    organizations: ["actors-equity"],
    events: ["whole-towns-talking", "actors-equity-strike-1919"],
    yearStart: 1923,
    yearEnd: 1923,
    period: "jazz-age-fame",
  },
  "blondes-origin-mencken": {
    people: ["anita-loos", "hl-mencken", "lorelei-lee"],
    places: ["hollywood"],
    events: ["gentlemen-prefer-blondes"],
    yearStart: 1925,
    yearEnd: 1925,
    period: "jazz-age-fame",
  },
  "blondes-harpers-book": {
    people: ["anita-loos", "ralph-barton", "lorelei-lee"],
    organizations: ["harpers-bazaar", "boni-liveright"],
    events: ["gentlemen-prefer-blondes"],
    yearStart: 1925,
    yearEnd: 1925,
    period: "jazz-age-fame",
  },
  "blondes-lorelei-character": {
    people: ["anita-loos", "lorelei-lee", "constance-talmadge"],
    events: ["gentlemen-prefer-blondes"],
    yearStart: 1925,
    yearEnd: 1925,
    period: "jazz-age-fame",
  },
  "blondes-stage-1926": {
    people: ["anita-loos"],
    places: ["chicago", "new-york"],
    events: ["gentlemen-prefer-blondes", "blondes-stage-adaptation"],
    yearStart: 1926,
    yearEnd: 1926,
    period: "jazz-age-fame",
  },
  "blondes-not-autobiography": {
    people: ["anita-loos", "lorelei-lee"],
    events: ["gentlemen-prefer-blondes"],
    yearStart: 1925,
    yearEnd: 1926,
    period: "jazz-age-fame",
  },
  "blondes-fans-authors": {
    people: [
      "anita-loos",
      "john-emerson",
      "william-faulkner",
      "aldous-huxley",
      "edith-wharton",
    ],
    events: ["gentlemen-prefer-blondes"],
    yearStart: 1925,
    yearEnd: 1925,
    period: "jazz-age-fame",
  },
  "film-silent-craft-titles": {
    people: ["anita-loos", "douglas-fairbanks", "dw-griffith"],
    yearStart: 1910,
    yearEnd: 1929,
    period: "silent-era-rise",
  },
  "film-women-screenwriters": {
    people: ["anita-loos"],
    places: ["hollywood"],
    organizations: ["triangle-film", "photoplay"],
    yearStart: 1910,
    yearEnd: 1929,
    period: "silent-era-rise",
  },
  "film-frances-marion": {
    people: ["anita-loos", "john-emerson", "frances-marion"],
    places: ["new-york"],
    yearStart: 1918,
    yearEnd: 1918,
    period: "silent-era-rise",
  },
  "hollywood-colony-1910s": {
    people: ["anita-loos", "dw-griffith"],
    places: ["hollywood", "los-angeles"],
    organizations: ["triangle-film"],
    yearStart: 1910,
    yearEnd: 1919,
    period: "silent-era-rise",
  },
  "hollywood-blvd-era": {
    places: ["hollywood-boulevard", "hollywood", "los-angeles"],
    yearStart: 1920,
    yearEnd: 1925,
    period: "jazz-age-fame",
  },
  "la-intolerance-set-geography": {
    people: ["anita-loos", "dw-griffith"],
    places: [
      "sunset-boulevard",
      "hollywood-boulevard",
      "los-feliz",
      "los-angeles",
      "hollywood",
    ],
    events: ["intolerance-1916"],
    yearStart: 1916,
    yearEnd: 1919,
    period: "silent-era-rise",
  },
  "la-not-pueblo-chronicler": {
    people: ["anita-loos"],
    places: ["los-angeles"],
  },
  "hollywoodland-sign-1923": {
    people: ["anita-loos"],
    places: ["hollywood", "los-angeles"],
    events: ["hollywoodland-sign"],
    yearStart: 1923,
    yearEnd: 1923,
    period: "jazz-age-fame",
  },
  "temporal-talkies-out": {
    events: ["jazz-singer-talkies"],
    yearStart: 1927,
    yearEnd: 1929,
    period: "post-1926-out-of-scope",
  },
  "temporal-mgm-women-gigi": {
    people: ["anita-loos", "marilyn-monroe"],
    organizations: ["mgm"],
    events: ["gentlemen-prefer-blondes"],
    yearStart: 1930,
    yearEnd: 1959,
    period: "post-1926-out-of-scope",
  },
  "bio-loc-birth-note": {
    people: ["anita-loos"],
    organizations: ["library-of-congress"],
    yearStart: 1888,
    yearEnd: 1893,
    period: "california-childhood",
  },
};
