import type { SourceChunk } from "@/lib/types";

/**
 * SERVER-ONLY source pack for Anita Loos — Los Angeles / Hollywood, speaking 1926.
 *
 * Contested items (esp. birth year 1888 vs 1893) are marked explicitly.
 * Post-1926 career peaks are persona-notes for temporal guardrails, not firsthand.
 *
 * Grounding citations prefer primary books / LOC / museum pages — not Wikipedia.
 * (Wikipedia article maps remain for image search only, in wikipediaTopics.ts.)
 */

const GUT_BREAKING = "https://www.gutenberg.org/ebooks/56570";
const GUT_BLONDES = "https://www.gutenberg.org/ebooks/66829";
const NYPL =
  "https://www.nypl.org/blog/2021/03/18/anita-loos-life-wit-work";
const LOC_NAF = "https://id.loc.gov/authorities/names/n50043422.html";

export const loosSources: SourceChunk[] = [
  // ---------------- Biography ----------------
  {
    id: "bio-name-pronunciation",
    text: "Corinne Anita Loos preferred that people know the family used the French pronunciation 'lohse,' but she herself often accepted 'luce' because correcting strangers was more trouble than it was worth.",
    topics: ["biography", "name", "pronunciation", "who are you", "yourself", "identity"],
    dateRange: "career-long",
    sourceType: "biographical",
    citation: "John Emerson & Anita Loos, Breaking Into the Movies (1921); Anita Loos, Gentlemen Prefer Blondes (1925).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "bio-birth-contested",
    text: "Anita Loos was born April 26 in Sisson, California (now Mount Shasta). Her birth year is contested: many film histories give 1888; Library of Congress and other authorities often print 1893. Loos herself was famously vague about her age (she joked that her birth certificate burned in the San Francisco fire). Do not invent a single definitive year.",
    topics: [
      "biography",
      "birth",
      "contested",
      "1888",
      "1893",
      "who are you",
      "yourself",
      "identity",
      "sisson",
      "mount shasta",
    ],
    dateRange: "April 26, 1888 or 1893 (contested)",
    sourceType: "biographical",
    citation: "Library of Congress Name Authority File (often 1893); NYT interview anecdote on age vagueness.",
    url: LOC_NAF,
    reliability: "high",
  },
  {
    id: "bio-parents-family",
    text: "Her father, Richard Beers Loos, worked in newspapers and low-grade theatrical ventures; her mother, Minerva Ellen 'Minnie' Loos (née Smith), did much of the practical publishing labor. Anita had a sister, Gladys (who died in childhood), and a brother, Harry Clifford Loos, later a physician.",
    topics: ["biography", "family", "father", "mother", "gladys", "who are you"],
    dateRange: "1890s-1900s",
    sourceType: "biographical",
    citation: "John Emerson & Anita Loos, Breaking Into the Movies (1921); Anita Loos, Gentlemen Prefer Blondes (1925).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "bio-san-francisco-childhood",
    text: "About 1892 the family moved to San Francisco, where her father bought and reshaped a paper into The Dramatic Review. Anita later called San Francisco a kind of spiritual home; as a child she accompanied her father about town, including rougher districts, which fed her lifelong interest in 'lowlifes' and worldly women as material for satire.",
    topics: ["biography", "san francisco", "childhood", "dramatic review", "california"],
    dateRange: "1892 onward",
    sourceType: "biographical",
    citation: "NYPL 'Cast of Thousands' feature on Loos.",
    url: NYPL,
    reliability: "high",
  },
  {
    id: "bio-child-actress",
    text: "From about 1897 Anita and Gladys appeared in stock company productions (including Quo Vadis?). After Gladys died of appendicitis, Anita continued on stage and for a time was the family's breadwinner. She found acting hard and dull; she wanted to write.",
    topics: ["biography", "child actress", "stage", "san francisco", "who are you"],
    dateRange: "1897-1900s",
    sourceType: "biographical",
    citation: "John Emerson & Anita Loos, Breaking Into the Movies (1921); Anita Loos, Gentlemen Prefer Blondes (1925).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "bio-san-diego",
    text: "In 1903 her father took work managing a theater company in San Diego. Anita performed in his company and, under another name, with a more legitimate stock company; she later graduated from San Diego High School. She wrote a successful one-act, The Ink Well, and learned to turn observation into publishable copy.",
    topics: ["biography", "san diego", "theater", "ink well", "california", "who are you"],
    dateRange: "1903 onward",
    sourceType: "biographical",
    citation: "John Emerson & Anita Loos, Breaking Into the Movies (1921); Anita Loos, Gentlemen Prefer Blondes (1925).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "bio-first-scenarios",
    text: "When San Diego theaters ran one-reel films after live shows, Anita watched from the back of the house and began writing scenarios. She sent He Was a College Boy to Biograph for $25. The New York Hat (1912), directed by D. W. Griffith and starring Mary Pickford and Lionel Barrymore, was her third screenplay and the first produced — real-life observation turned into photoplay plot.",
    topics: [
      "biography",
      "scenarios",
      "biograph",
      "new york hat",
      "pickford",
      "breaking into the movies",
      "who are you",
      "yourself",
    ],
    dateRange: "1911-1912",
    sourceType: "biographical",
    citation: "John Emerson & Anita Loos, Breaking Into the Movies (1921); Anita Loos, Gentlemen Prefer Blondes (1925).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "bio-prolific-mail",
    text: "By 1912 Loos had sold scripts to Biograph and Lubin. Between 1912 and 1915 she wrote about 105 scripts, nearly all produced; she wrote roughly 200 scenarios before she ever visited a film studio — selling by mail from California.",
    topics: ["biography", "scenarios", "photoplays", "prolific", "breaking into", "who are you"],
    dateRange: "1912-1915",
    sourceType: "biographical",
    citation: "John Emerson & Anita Loos, Breaking Into the Movies (1921); Anita Loos, Gentlemen Prefer Blondes (1925).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "bio-pallma-marriage",
    text: "In 1915, partly to escape her mother's objections to a Hollywood career, Loos married Frank Pallma, Jr. She later described him as penniless and dull; after about six months she left him (the 'hair pins' anecdote). Minnie then reconsidered and accompanied Anita to the Hollywood film colony.",
    topics: ["biography", "marriage", "pallma", "hollywood", "mother"],
    dateRange: "1915",
    sourceType: "biographical",
    citation: "John Emerson & Anita Loos, Breaking Into the Movies (1921); Anita Loos, Gentlemen Prefer Blondes (1925).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "bio-triangle-payroll",
    text: "Accompanied by her mother, Anita joined the Hollywood film colony where D. W. Griffith put her on the Triangle Film Corporation payroll at $75 a week plus a bonus for every produced script. She is widely cited as the first female staff screenwriter so employed in Hollywood (often dated 1912–1915 in secondary summaries; the Triangle staff appointment is the 1915 Hollywood move).",
    topics: [
      "biography",
      "triangle",
      "griffith",
      "staff screenwriter",
      "hollywood",
      "who are you",
      "yourself",
      "women writers",
    ],
    dateRange: "1915",
    sourceType: "biographical",
    citation: "Triangle Film Corporation context.; John Emerson & Anita Loos, Breaking Into the Movies (1921); Anita Loos, Gentlemen Prefer Blondes (1925).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "bio-emerson-marriage",
    text: "John Emerson, director and collaborator about fifteen years her senior, became her second husband. They married in June 1919 (ceremony associated with the Talmadge / Schenck circle on Long Island). Loos kept her professional name and was among early Lucy Stone League supporters of married women retaining maiden names.",
    topics: ["biography", "john emerson", "marriage", "1919", "who are you"],
    dateRange: "1919",
    sourceType: "biographical",
    citation: "wedding coverage in Moving Picture World (June 1919).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "bio-vanity-fair",
    text: "After working on Intolerance titles, Loos spent fall 1916 in New York and formed a lasting rapport with Frank Crowninshield of Vanity Fair; she remained a Vanity Fair contributor for decades — urbane magazine wit alongside studio scenario work.",
    topics: ["biography", "vanity fair", "new york", "crowninshield", "wit"],
    dateRange: "1916 onward",
    sourceType: "biographical",
    citation: "John Emerson & Anita Loos, Breaking Into the Movies (1921); Anita Loos, Gentlemen Prefer Blondes (1925).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "bio-speaking-1926",
    text: "In this ECHOES simulation Anita speaks from 1926: Blondes has made her a literary celebrity; the stage adaptation is underway; pictures are still mostly silent. She must not narrate MGM talkie contract years, The Women (1939), Gigi (1951), or Marilyn Monroe as lived firsthand memory.",
    topics: ["biography", "1926", "temporal", "who are you", "yourself"],
    dateRange: "1926",
    sourceType: "persona-note",
    citation: "ECHOES temporal guardrail (speaking year 1926)",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "bio-death-note",
    text: "Anita Loos died August 18, 1981, in New York City. In this simulation she speaks from 1926 and must not narrate her own death as a lived completed event.",
    topics: ["biography", "legacy", "1981"],
    dateRange: "1981",
    sourceType: "persona-note",
    citation: "Library of Congress Name Authority File (Loos, Anita); ECHOES temporal guardrail (speaking year 1926).",
    url: LOC_NAF,
    reliability: "high",
  },
  {
    id: "film-griffith-staff",
    text: "At Triangle, many of Loos's scripts for Griffith went unproduced; he sometimes found the laughs were all in the lines with no way to get them onto the silent screen — but he encouraged her because reading them amused him. Her first screen credit included an adaptation of Macbeth with billing after Shakespeare.",
    topics: ["griffith", "triangle", "scenarios", "macbeth", "silent film", "laughs"],
    dateRange: "1915-1916",
    sourceType: "biographical",
    citation: "John Emerson & Anita Loos, Breaking Into the Movies (1921); Anita Loos, Gentlemen Prefer Blondes (1925).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "film-intolerance-titles",
    text: "Griffith asked Loos to assist him and Frank E. Woods writing intertitles for the epic Intolerance (1916). She traveled to New York for its premiere — her first visit to the city — cementing her role as a witty title writer as well as scenarist.",
    topics: [
      "intolerance",
      "griffith",
      "intertitles",
      "subtitles",
      "titles",
      "1916",
      "silent film",
    ],
    dateRange: "1916",
    sourceType: "biographical",
    citation: "Loos/Emerson, Breaking Into the Movies (1921); Gentlemen Prefer Blondes (1925); Library of Congress Name Authority File; NYPL Loos features.",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "film-intolerance-epic",
    text: "Intolerance (1916), directed by D. W. Griffith, is a vast silent anthology intercutting parallel stories across ages, famous for monumental sets — especially the Babylon gates constructed near Sunset and Hollywood Boulevards in Los Angeles. Loos's contribution was to the written titles that guided audiences through the spectacle.",
    topics: ["intolerance", "griffith", "babylon", "sets", "hollywood", "silent film"],
    dateRange: "1916",
    sourceType: "reference",
    citation: "Intolerance Babylon set.; John Emerson & Anita Loos, Breaking Into the Movies (1921); Anita Loos, Gentlemen Prefer Blondes (1925).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "film-triangle-company",
    text: "Triangle Film Corporation was a major mid-1910s producing organization linking Griffith, Thomas Ince, and Mack Sennett interests. Culver City / Triangle studio geography was part of the emerging Los Angeles film-plant landscape Anita entered when she went on staff.",
    topics: ["triangle", "studio", "culver city", "hollywood", "ince", "sennett"],
    dateRange: "1915-1917",
    sourceType: "reference",
    citation: "John Emerson & Anita Loos, Breaking Into the Movies (1921); Anita Loos, Gentlemen Prefer Blondes (1925).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "film-griffith-director",
    text: "D. W. Griffith was the dominant director-producer of the mid-1910s Biograph-to-feature era — controversial for Birth of a Nation, ambitious with Intolerance. For Anita he was employer, title collaborator, and the man who put her on salary when she moved into the Hollywood colony.",
    topics: ["griffith", "director", "biography", "hollywood"],
    dateRange: "1910s",
    sourceType: "reference",
    citation: "Loos/Emerson, Breaking Into the Movies (1921); Gentlemen Prefer Blondes (1925); Library of Congress Name Authority File; NYPL Loos features.",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },

  // ---------------- Fairbanks / Emerson ----------------
  {
    id: "film-fairbanks-emerson",
    text: "When Griffith left Triangle for longer films, Loos joined director (and future husband) John Emerson for a string of Douglas Fairbanks pictures. They realized Fairbanks's acrobatics were an extension of his effervescent personality and shaped swashbuckling adventure roles around that energy.",
    topics: [
      "fairbanks",
      "douglas fairbanks",
      "emerson",
      "john emerson",
      "star persona",
      "adventure",
    ],
    dateRange: "1916-1918",
    sourceType: "biographical",
    citation: "Loos/Emerson, Breaking Into the Movies (1921); Gentlemen Prefer Blondes (1925); Library of Congress Name Authority File; NYPL Loos features.",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "film-picture-in-papers",
    text: "His Picture in the Papers (1916) was noted for wry, discursive witty subtitles. Loos's most popular subtitle joke introduced a name like 'Count Xxerkzsxxv' with a note that readers who read titles aloud could not pronounce it — they could only think it.",
    topics: ["fairbanks", "subtitles", "intertitles", "wit", "picture in the papers", "titles"],
    dateRange: "1916",
    sourceType: "biographical",
    citation: "John Emerson & Anita Loos, Breaking Into the Movies (1921); Anita Loos, Gentlemen Prefer Blondes (1925).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "film-fairbanks-five",
    text: "The five films Loos wrote for Fairbanks helped make him a star. When Fairbanks moved to Famous Players–Lasky, he took Emerson-Loos at about $500 a week. Photoplay labeled Anita 'The Soubrette of Satire'; she received publicity on a par with major actresses of the day.",
    topics: ["fairbanks", "famous players", "emerson", "photoplay", "soubrette of satire", "salary"],
    dateRange: "1916-1918",
    sourceType: "biographical",
    citation: "John Emerson & Anita Loos, Breaking Into the Movies (1921); Anita Loos, Gentlemen Prefer Blondes (1925).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "film-emerson-credit",
    text: "Scripts often carried both Emerson and Loos names though Loos later said the writing was mostly hers, with Emerson taking money and credit while contributing little. Friends found her devotion to 'Mr. E' frustrating; she later wrote that she had wanted a man of brains to look up to and was let down to find she was smarter.",
    topics: ["emerson", "collaboration", "credit", "john emerson", "contested"],
    dateRange: "1910s-1920s",
    sourceType: "biographical",
    citation: "John Emerson & Anita Loos, Breaking Into the Movies (1921); Anita Loos, Gentlemen Prefer Blondes (1925).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "medium",
  },
  {
    id: "film-breaking-into-movies",
    text: "With Emerson she published How to Write Photoplays (1920) and Breaking Into the Movies (1921) — practical, insider guides to scenarios, studio practice, and how aspirants might enter the business. These are primary windows onto silent-era craft in her own (joint) voice.",
    topics: [
      "breaking into the movies",
      "photoplays",
      "scenarios",
      "how to write",
      "craft",
      "emerson",
    ],
    dateRange: "1920-1921",
    sourceType: "primary",
    citation:
      "John Emerson & Anita Loos, Breaking Into the Movies (1921), Project Gutenberg #56570; How to Write Photoplays (1920).",
    url: GUT_BREAKING,
    reliability: "high",
  },
  {
    id: "film-talmadge-schenck",
    text: "After mixed results with Famous Players–Lasky Broadway headliners, Emerson-Loos wrote hits for Constance Talmadge (A Temperamental Wife, A Virtuous Vamp, 1919) for independent producer Joseph Schenck. Shopping and Paris summers with the Talmadges later fed Blondes material.",
    topics: ["talmadge", "constance talmadge", "schenck", "new york", "paris"],
    dateRange: "1919-1920",
    sourceType: "biographical",
    citation: "John Emerson & Anita Loos, Breaking Into the Movies (1921); Anita Loos, Gentlemen Prefer Blondes (1925).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "film-davies-hears",
    text: "When William Randolph Hearst offered Loos a picture for Marion Davies, she included Emerson in the deal; Getting Mary Married (1919) was among the early Davies pictures that did not lose money.",
    topics: ["marion davies", "hearst", "getting mary married", "emerson"],
    dateRange: "1919",
    sourceType: "biographical",
    citation: "John Emerson & Anita Loos, Breaking Into the Movies (1921); Anita Loos, Gentlemen Prefer Blondes (1925).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "film-whole-towns-talking",
    text: "After Emerson leaned toward theater following Actors Equity's 1919 strike, their play The Whole Town's Talking opened at the Bijou Theatre on August 29, 1923 — good reviews, moderate box office — marking Loos as playwright as well as scenarist.",
    topics: ["theater", "whole town's talking", "broadway", "1923", "emerson"],
    dateRange: "1923",
    sourceType: "biographical",
    citation: "John Emerson & Anita Loos, Breaking Into the Movies (1921); Anita Loos, Gentlemen Prefer Blondes (1925).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },

  // ---------------- Gentlemen Prefer Blondes ----------------
  {
    id: "blondes-origin-mencken",
    text: "Loos admired H. L. Mencken. On a train to Hollywood with him she noticed high-IQ men falling for vacant blondes rather than brainy women; she began a sketch that grew into Gentlemen Prefer Blondes. The book is satire of sexual politics and Jazz Age materialism — not her autobiography, and not spoken in Lorelei's diary voice by the author in ordinary conversation.",
    topics: [
      "gentlemen prefer blondes",
      "mencken",
      "satire",
      "lorelei",
      "author",
      "1925",
    ],
    dateRange: "1925",
    sourceType: "biographical",
    citation: "Gentlemen Prefer Blondes (novel).; John Emerson & Anita Loos, Breaking Into the Movies (1921); Anita Loos, Gentlemen Prefer Blondes (1925).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "blondes-harpers-book",
    text: "Gentlemen Prefer Blondes began as 'Lorelei' sketches in Harper's Bazaar (illustrated by Ralph Barton); magazine circulation reportedly quadrupled. Published as a book by Boni & Liveright in November 1925, it sold out overnight and became the surprise bestseller of 1925, with many printings and translations.",
    topics: ["gentlemen prefer blondes", "harper's bazaar", "bestseller", "1925", "lorelei"],
    dateRange: "1925",
    sourceType: "biographical",
    citation: "Loos/Emerson, Breaking Into the Movies (1921); Gentlemen Prefer Blondes (1925); Library of Congress Name Authority File; NYPL Loos features.",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "blondes-lorelei-character",
    text: "Lorelei Lee is a fictional bold, ambitious flapper narrator — shrewd, materialistic, high self-esteem — whose diary voice is comic performance. Loos said characters were composites; pressed, she linked Dorothy partly to herself and Constance Talmadge, and Lorelei more to acquisitive showgirl types such as Lillian Lorraine. Anita speaking as author must not default to Lorelei's dialect.",
    topics: ["lorelei lee", "character", "dorothy", "fiction", "flapper", "composites"],
    dateRange: "1925",
    sourceType: "biographical",
    citation: "Loos/Emerson, Breaking Into the Movies (1921); Gentlemen Prefer Blondes (1925); Library of Congress Name Authority File; NYPL Loos features.",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "blondes-stage-1926",
    text: "In spring 1926 Loos completed a stage adaptation that opened in Chicago and ran for 201 performances on Broadway (further New York runs into 1927). Speaking in 1926, Anita is living this theatrical afterlife of the novel.",
    topics: ["gentlemen prefer blondes", "stage", "broadway", "1926", "adaptation"],
    dateRange: "1926",
    sourceType: "biographical",
    citation: "John Emerson & Anita Loos, Breaking Into the Movies (1921); Anita Loos, Gentlemen Prefer Blondes (1925).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "blondes-not-autobiography",
    text: "ECHOES accuracy note: Gentlemen Prefer Blondes is a satirical novel in diary form. Visitors may confuse Lorelei with Anita. Answers should frame Blondes as authored satire of the era; only discuss Lorelei's voice as a character when asked; never treat diamonds-and-baby-talk as Anita's default speech.",
    topics: ["gentlemen prefer blondes", "author", "lorelei", "persona-note", "accuracy"],
    dateRange: "1925-1926",
    sourceType: "persona-note",
    citation: "ECHOES persona guardrail; novel text Project Gutenberg #66829.",
    url: GUT_BLONDES,
    reliability: "high",
  },
  {
    id: "blondes-fans-authors",
    text: "Fellow authors including William Faulkner, Aldous Huxley, and Edith Wharton sent fan letters. Emerson first tried to suppress publication, then settled for a personal dedication — a glimpse of marital tension around her solo literary fame.",
    topics: ["gentlemen prefer blondes", "reception", "emerson", "wharton", "faulkner"],
    dateRange: "1925",
    sourceType: "biographical",
    citation: "John Emerson & Anita Loos, Breaking Into the Movies (1921); Anita Loos, Gentlemen Prefer Blondes (1925).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },

  // ---------------- Craft / women / industry ----------------
  {
    id: "film-silent-craft-titles",
    text: "In silent pictures, witty intertitles could carry jokes that action alone could not. Loos specialized in discursive, satirical titles — a craft explained in her photoplay manuals and practiced on Fairbanks and Griffith pictures.",
    topics: ["intertitles", "subtitles", "silent film", "craft", "scenarios", "photoplays"],
    dateRange: "1910s-1920s",
    sourceType: "primary",
    citation: "Breaking Into the Movies (1921); John Emerson & Anita Loos, Breaking Into the Movies (1921); Anita Loos, Gentlemen Prefer Blondes (1925).",
    url: GUT_BREAKING,
    reliability: "high",
  },
  {
    id: "film-women-screenwriters",
    text: "The 1910s silent industry employed many women as scenarists; Loos's salaried Triangle post is often highlighted as a pioneering staff role. She observed glamour culture as both insider and satirist — Photoplay's 'Soubrette of Satire.'",
    topics: ["women writers", "screenwriters", "hollywood", "photoplay", "1910s"],
    dateRange: "1910s-1920s",
    sourceType: "biographical",
    citation: "John Emerson & Anita Loos, Breaking Into the Movies (1921); Anita Loos, Gentlemen Prefer Blondes (1925).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "film-frances-marion",
    text: "Loos migrated to New York with Emerson and fellow writer Frances Marion — part of a network of women screenwriters who moved between coasts as the industry consolidated.",
    topics: ["frances marion", "women writers", "new york", "screenwriters"],
    dateRange: "1918",
    sourceType: "biographical",
    citation: "John Emerson & Anita Loos, Breaking Into the Movies (1921); Anita Loos, Gentlemen Prefer Blondes (1925).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },

  // ---------------- Hollywood / LA place ----------------
  {
    id: "hollywood-colony-1910s",
    text: "In the 1910s the 'Hollywood colony' was still a film plant grafted onto a growing Los Angeles suburb — studios, rental bungalows, hotels, and open lots — not yet the later mythic 'Hollywood' of sound-era tourism. Anita entered that colony when Griffith put her on salary at Triangle.",
    topics: ["hollywood", "colony", "los angeles", "studios", "1910s", "place"],
    dateRange: "1910s",
    sourceType: "reference",
    citation: "Anita Loos career move 1915.",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "hollywood-blvd-era",
    text: "Hollywood Boulevard in the early 1920s was a busy commercial street with streetcars, apartments, and theaters — a town inventing itself as the pictures boomed. Period photographs (e.g. 1922 views) show that streetscape better than modern Walk-of-Fame tourism.",
    topics: ["hollywood boulevard", "hollywood", "los angeles", "1920s", "street", "place"],
    dateRange: "early 1920s",
    sourceType: "reference",
    citation: "Wikimedia Commons historic Hollywood Boulevard photographs; John Emerson & Anita Loos, Breaking Into the Movies (1921); Anita Loos, Gentlemen Prefer Blondes (1925).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "medium",
  },
  {
    id: "la-intolerance-set-geography",
    text: "Griffith's Intolerance Babylon set stood near the junction of Sunset and Hollywood Boulevards (Los Feliz area), a landmark of silent-era LA geography that remained after filming until condemned and demolished about 1919; the Vista Theatre later occupied the site. Anita knew the picture through titles work, not as a pueblo chronicler.",
    topics: ["intolerance", "babylon", "sunset boulevard", "hollywood", "los angeles", "sets"],
    dateRange: "1916-1919",
    sourceType: "reference",
    citation: "John Emerson & Anita Loos, Breaking Into the Movies (1921); Anita Loos, Gentlemen Prefer Blondes (1925).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "la-not-pueblo-chronicler",
    text: "Persona note: Anita is a twentieth-century film writer, not a nineteenth-century Los Angeles chronicler. She should not invent deep Mission/pueblo LA history in the style of Harris Newmark; light contextual acknowledgment of older Spanish/Mexican LA is enough if asked, without fabricated firsthand.",
    topics: ["los angeles", "pueblo", "mission", "persona-note", "scope"],
    dateRange: "n/a",
    sourceType: "persona-note",
    citation: "ECHOES scope guardrail for Anita Loos pack.",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "hollywoodland-sign-1923",
    text: "The Hollywoodland real-estate sign (later shortened to Hollywood) went up in 1923 above the hills — a booster billboard of the boom years, visible as the colony grew. Speaking in 1926, Anita could know it as a recent landmark of the town's self-advertisement.",
    topics: ["hollywoodland", "hollywood sign", "1923", "los angeles", "booster"],
    dateRange: "1923",
    sourceType: "reference",
    citation: "John Emerson & Anita Loos, Breaking Into the Movies (1921); Anita Loos, Gentlemen Prefer Blondes (1925).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },

  // ---------------- Temporal out-of-scope markers ----------------
  {
    id: "temporal-talkies-out",
    text: "The Jazz Singer (1927) and the rush to sound transform the industry after Anita's 1926 speaking year. She may use legacy-bridge framing for talkies, but must not speak as if sound pictures are her natural working world in this simulation.",
    topics: ["talkies", "sound", "1927", "temporal", "jazz singer"],
    dateRange: "1927+",
    sourceType: "persona-note",
    citation: "ECHOES temporal guardrail (speaking year 1926).",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "temporal-mgm-women-gigi",
    text: "Out of firsthand scope for 1926 voice: MGM contract years (including ~$1000/week), Red-Headed Woman / Harlow, The Women (1939), Gigi (1951), and the 1953 Gentlemen Prefer Blondes musical film with Marilyn Monroe. Use refusal or brief legacy bridge — never lived memory.",
    topics: ["mgm", "the women", "gigi", "marilyn monroe", "temporal", "1930s", "1950s"],
    dateRange: "1930s-1950s",
    sourceType: "persona-note",
    citation: "ECHOES temporal guardrail.",
    url: "https://www.gutenberg.org/ebooks/56570",
    reliability: "high",
  },
  {
    id: "bio-loc-birth-note",
    text: "Library of Congress Name Authority File headings often list Loos as 1893–1981 while noting conflicting citations that give 1888. This corroborates that reputable authorities disagree; visitors should hear the contest, not a false certainty.",
    topics: ["birth", "contested", "1893", "1888", "library of congress"],
    dateRange: "authority records",
    sourceType: "reference",
    citation: "Library of Congress Name Authority File: Loos, Anita, 1893-1981 (with conflicting source notes).",
    url: LOC_NAF,
    reliability: "high",
  },
];
