import type { ImageAsset } from "@/lib/types";

/**
 * SERVER-ONLY image library for Myron Angel.
 *
 * Every image here was visually verified and is public domain. Prefer Wikimedia
 * Commons / Wikipedia gallery files; citations link to the Commons file page.
 */
export const myronAngelImages: ImageAsset[] = [
  {
    id: "img-portrait",
    src: "/images/myron-angel/myron-portrait.jpg",
    caption: "Myron Angel (1827–1911), journalist and historian of San Luis Obispo.",
    alt: "Engraved portrait of an older bearded man, Myron Angel",
    topics: ["myron angel", "portrait", "appearance", "biography", "yourself"],
    dateRange: "c. 1880s",
    citation: "Public-domain portrait of Myron Angel.",
    license: "Public domain",
  },
  {
    id: "img-slo-street-1905",
    src: "/images/myron-angel/slo-street-1905.jpg",
    caption:
      "A commercial street in San Luis Obispo about 1905 — storefronts, awnings, carriages, and townsfolk going about their business in our growing downtown.",
    alt: "Black-and-white photograph of a San Luis Obispo commercial street around 1905 with storefronts, horse-drawn carriages, and pedestrians",
    topics: [
      "downtown",
      "old town",
      "main street",
      "higuera street",
      "streets",
      "shops",
      "stores",
      "businesses",
      "buildings",
      "town",
      "city",
      "1905",
      "everyday life",
    ],
    dateRange: "c. 1905",
    citation:
      "“View of a commercial street in San Luis Obispo, ca.1905,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/2572c81f8c70aa16f400d697c504a5f8/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-slo-view-1900",
    src: "/images/myron-angel/slo-view-1900.jpg",
    caption:
      "A view of San Luis Obispo about the year 1900, the town spread out in its valley beneath our familiar volcanic peaks.",
    alt: "Black-and-white photograph of San Luis Obispo around 1900 showing the town below two mountain peaks",
    topics: [
      "town",
      "city",
      "view",
      "panorama",
      "landscape",
      "valley",
      "peaks",
      "morros",
      "hills",
      "san luis obispo",
      "1900",
    ],
    dateRange: "c. 1900",
    citation:
      "“View of San Luis Obispo, ca.1900,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/a1971025247e3761965bdd17e4ea5cf8/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-slo-late-1800s",
    src: "/images/myron-angel/slo-late-1800s.jpg",
    caption:
      "San Luis Obispo in the late nineteenth century — the mission church and town buildings clustered in the valley, much as I found them when I began my county history in 1883.",
    alt: "Late 19th century photograph of San Luis Obispo showing the mission and town",
    topics: [
      "town",
      "city",
      "view",
      "panorama",
      "san luis obispo",
      "late 1800s",
      "19th century",
      "mission",
      "valley",
    ],
    dateRange: "late 19th century",
    citation:
      "San Luis Obispo (late 19th century). Public domain via Wikimedia Commons (Wikipedia: San Luis Obispo, California).",
    url: "https://commons.wikimedia.org/wiki/File:San_Luis_Obispo_(late_19th_century).jpg",
    license: "Public domain",
  },
  {
    id: "img-slo-deakin-1899",
    src: "/images/myron-angel/slo-deakin-1899.jpg",
    caption:
      "San Luis Obispo as the artist Edwin Deakin painted it in 1899 — the mission and adobe town beneath the coastal hills, a faithful impression of the place I have chronicled.",
    alt: "1899 painting of San Luis Obispo by Edwin Deakin showing mission and town",
    topics: [
      "town",
      "city",
      "view",
      "panorama",
      "san luis obispo",
      "1899",
      "painting",
      "mission",
      "adobe",
      "valley",
    ],
    dateRange: "1899",
    citation:
      "Edwin Deakin, San Luis Obispo (1899). Public domain via Wikimedia Commons (Wikipedia: San Luis Obispo, California).",
    url: "https://commons.wikimedia.org/wiki/File:San_Luis_Obispo_(Edwin_Deakin,_1899).jpg",
    license: "Public domain",
  },
  {
    id: "img-morro-rock-1900",
    src: "/images/myron-angel/morro-rock-1900.jpg",
    caption:
      "Morro Rock and the bay, about 1900 — the great volcanic dome standing sentinel over the water, with small sailing boats drawn up on the shore.",
    alt: "Black-and-white photograph of Morro Rock around 1900 with sailboats on the shore",
    topics: [
      "morro rock",
      "morro bay",
      "coast",
      "ocean",
      "bay",
      "rock",
      "wilderness",
      "nature",
      "landscape",
      "boats",
      "seven sisters",
      "volcanic peaks",
    ],
    dateRange: "c. 1900",
    citation:
      "“View of Morro Rock, showing sailboats, ca.1900,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/c1f1f5a253b4a99a54b7990e2e0af6c8/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-avila-beach-1905",
    src: "/images/myron-angel/avila-beach-1905.jpg",
    caption:
      "Avila Beach, near San Luis Obispo, about 1905 — the rocky shore and hills of our coast, with a few houses set along the ridge.",
    alt: "Black-and-white photograph of Avila Beach around 1905 showing a rocky coastline and hills",
    topics: [
      "avila",
      "avila beach",
      "coast",
      "beach",
      "ocean",
      "seaside",
      "shore",
      "bay",
      "wilderness",
      "san luis obispo",
    ],
    dateRange: "c. 1905",
    citation:
      "“View of Avila Beach, near San Luis Obispo, ca.1905,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/d3d370747668a728278b64f1a98ce33c/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-port-harford-1905",
    src: "/images/myron-angel/port-harford-1905.jpg",
    caption:
      "The wharf at Port Harford, about 1905 — our county's great ocean landing, its railroad tracks running out to the steamships that carry our produce to market.",
    alt: "Black-and-white photograph of the long Port Harford wharf around 1905 with railroad tracks and steamships",
    topics: [
      "port harford",
      "port san luis",
      "avila",
      "wharf",
      "pier",
      "harbor",
      "shipping",
      "steamship",
      "railroad",
      "commerce",
      "trade",
      "ocean",
    ],
    dateRange: "c. 1905",
    citation:
      "“View of Port Harford wharf, San Luis Obispo County, ca.1905,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/b4c79a58ac9461ee99f330af59b0b2fe/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-chumash-musicians-1873",
    src: "/images/myron-angel/chumash-musicians-1873.jpg",
    caption:
      "Chumash musicians photographed in 1873 — the Chumash are the native people of this Central Coast, here at Mission San Buenaventura to the south, holding their instruments.",
    alt: "Sepia 1873 photograph of six seated Chumash men holding musical instruments",
    topics: [
      "chumash",
      "native",
      "indigenous",
      "music",
      "musicians",
      "instruments",
      "mission san buenaventura",
      "mission era",
      "post-contact",
      "1873",
    ],
    dateRange: "1873",
    citation:
      "Chumash musicians at Mission San Buenaventura, 1873. Public domain via Wikimedia Commons (File:Chmash musicians 1873.jpg).",
    url: "https://commons.wikimedia.org/wiki/File:Chmash_musicians_1873.jpg",
    license: "Public domain",
  },
  {
    id: "img-choris-tule-canoe-1822",
    src: "/images/myron-angel/choris-tule-canoe-1822.jpg",
    caption:
      "A tule-rush canoe on San Francisco Bay, about 1822 — Louis Choris's engraving from Kotzebue's voyage. These are Ohlone-area peoples at the Bay, not the Chumash of our Central Coast; the boat is a bundled-rush craft, not a plank tomol.",
    alt: "1822 Louis Choris engraving of a tule canoe with two paddlers on San Francisco Bay",
    topics: [
      "ohlone",
      "san francisco bay",
      "native",
      "indigenous",
      "canoe",
      "canoes",
      "tule",
      "rush boat",
      "paddle",
      "1822",
      "choris",
      "california indians",
      "pre-contact",
    ],
    dateRange: "1822",
    citation:
      "Louis Choris, “San-Francisco Bay boat,” Voyage pittoresque autour du monde (1822). Depicts Bay Area peoples (Ohlone region), not Chumash. Public domain via Wikimedia Commons.",
    url: "https://commons.wikimedia.org/wiki/File:Choris_1822_gri_33125010887327_0174.jpg",
    license: "Public domain",
  },
  {
    id: "img-choris-california-people-1822",
    src: "/images/myron-angel/choris-california-people-1822.jpg",
    caption:
      "California peoples as Louis Choris recorded them in 1822 on San Francisco Bay — Ohlone and related groups, not specifically the Chumash of San Luis Obispo County. Useful only as general context for indigenous life before missions.",
    alt: "1822 Louis Choris engraving of Native people in traditional dress at San Francisco Bay",
    topics: [
      "ohlone",
      "san francisco bay",
      "native",
      "indigenous",
      "california indians",
      "traditional dress",
      "1822",
      "choris",
      "pre-contact",
    ],
    dateRange: "1822",
    citation:
      "Louis Choris, “California People,” Voyage pittoresque autour du monde (1822). Bay Area peoples, not Chumash. Public domain via Wikimedia Commons.",
    url: "https://commons.wikimedia.org/wiki/File:Choris_1822_gri_33125010887327_0166.jpg",
    license: "Public domain",
  },
  {
    id: "img-choris-cholovones-hunting-1822",
    src: "/images/myron-angel/choris-cholovones-hunting-1822.jpg",
    caption:
      "Cholovones hunting from tule canoes in San Francisco Bay, about 1822 — Choris's engraving of Bay Area peoples. Not Chumash; shows rush boats, not plank tomols.",
    alt: "1822 Louis Choris engraving of Cholovones hunting from tule canoes on the bay",
    topics: [
      "cholovones",
      "ohlone",
      "san francisco bay",
      "native",
      "canoe",
      "tule",
      "hunting",
      "1822",
      "choris",
    ],
    dateRange: "1822",
    citation:
      "Louis Choris, “Cholovones hunting in San Francisco Bay,” Voyage pittoresque autour du monde (1822). Public domain via Wikimedia Commons.",
    url: "https://commons.wikimedia.org/wiki/File:Choris_1822_gri_33125010887327_0190.jpg",
    license: "Public domain",
  },
  {
    id: "img-chumash-painted-cave",
    src: "/images/myron-angel/chumash-painted-cave.jpg",
    caption:
      "Chumash pictographs at the Painted Cave, Santa Barbara County — rock paintings of the Chumash spiritual tradition, among the authentic visual records of their pre-contact culture in our region.",
    alt: "Photograph of Chumash pictograph rock paintings in a cave",
    topics: [
      "chumash",
      "native",
      "indigenous",
      "pictograph",
      "pictographs",
      "rock art",
      "cave painting",
      "painted cave",
      "ancient",
      "pre-contact",
      "spiritual",
      "heritage",
      "ancestors",
      "first peoples",
    ],
    dateRange: "pre-contact (centuries old)",
    citation:
      "Chumash pictographs, Chumash Painted Cave State Historic Park, Santa Barbara County. Photo via Wikimedia Commons.",
    url: "https://commons.wikimedia.org/wiki/File:PaintedCaveArtCA.jpg",
    license: "Public domain",
  },
  {
    id: "img-chumash-pictograph-oakbrook",
    src: "/images/myron-angel/chumash-pictograph-oakbrook.jpg",
    caption:
      "A Chumash pictograph at the Oakbrook archaeological site — this swordfish motif is associated with shaman traditions along our coast. Rock paintings like these in Ventura and Santa Barbara counties date back thousands of years and belong to the spiritual world of the Chumash before the missions.",
    alt: "Photograph of a red Chumash swordfish pictograph on rock at Oakbrook Regional Park",
    topics: [
      "chumash",
      "native",
      "indigenous",
      "pictograph",
      "pictographs",
      "rock art",
      "swordfish",
      "shaman",
      "spiritual",
      "ancient",
      "pre-contact",
      "oakbrook",
      "sap'wi",
    ],
    dateRange: "approx. 4000–6000 years old (archaeological estimate)",
    citation:
      "Chumash pictograph, Oakbrook Regional Park (Chumash Indian Museum). Photo via Wikimedia Commons. CC BY-SA 4.0.",
    url: "https://commons.wikimedia.org/wiki/File:Oakbrook_regional_park_chumash_indian_museum_thousand_oaks_cave_paintings_pictographs.jpg",
    license: "CC BY-SA 4.0",
  },
  {
    id: "img-chumash-mortars-exhibit",
    src: "/images/myron-angel/chumash-mortars-exhibit.jpg",
    caption:
      "Stone mortars and pestles of the kind the Chumash used to grind acorns — the staple of coastal village life. In my day one could still find old grinding stones at abandoned village sites; these examples are preserved at the Chumash Indian Museum for later generations.",
    alt: "Photograph of Chumash stone mortars and pestles on display at a museum",
    topics: [
      "chumash",
      "native",
      "indigenous",
      "acorn",
      "acorns",
      "grinding",
      "mortar",
      "mortars",
      "pestle",
      "food",
      "village",
      "daily life",
      "tools",
    ],
    dateRange: "traditional tools (modern museum exhibit photo)",
    citation:
      "Mortars and pestles, Chumash Indian Museum, Thousand Oaks. Photo via Wikimedia Commons. CC BY-SA 4.0.",
    url: "https://commons.wikimedia.org/wiki/File:Chumash_indian_museum_mortars_pestles.jpg",
    license: "CC BY-SA 4.0",
  },
  {
    id: "img-chumash-ap-replica",
    src: "/images/myron-angel/chumash-ap-replica.jpg",
    caption:
      "A reconstructed Chumash 'ap — the dome-shaped dwelling of willow frame and tule thatched over, sheltering families at village sites like Sap'wi along our creeks. By the mission era many such villages had been disrupted, though the old ways were remembered.",
    alt: "Photograph of a reconstructed Chumash ap dome house at an outdoor museum village",
    topics: [
      "chumash",
      "native",
      "indigenous",
      "ap",
      "house",
      "dwelling",
      "village",
      "tule",
      "willow",
      "home",
      "daily life",
      "pre-contact",
      "sap'wi",
    ],
    dateRange: "traditional dwelling (modern museum replica photo)",
    citation:
      "Replica Chumash 'ap, Chumash Indian Museum, Thousand Oaks. Photo via Wikimedia Commons. CC BY-SA 4.0.",
    url: "https://commons.wikimedia.org/wiki/File:Chumash_indian_museum_thousand_oaks.jpg",
    license: "CC BY-SA 4.0",
  },
  {
    id: "img-chumash-tomol-kihn",
    src: "/images/myron-angel/chumash-tomol-kihn.jpg",
    caption:
      "Artist W. Langdon Kihn's reconstruction of the traditional Chumash plank tomol — redwood planks sewn and caulked with tar and pitch, the \"House of the Sea\" that carried our coastal peoples to the Channel Islands. In my day few tomols still crossed those waters; this later illustration shows how boat-builders described the craft.",
    alt: "Illustration of a Chumash plank-built tomol canoe with paddlers on the ocean",
    topics: [
      "chumash",
      "tomol",
      "tomols",
      "plank canoe",
      "plank-built",
      "canoe",
      "channel islands",
      "boat",
      "watercraft",
      "indigenous",
      "native",
    ],
    dateRange: "artist reconstruction (1946)",
    citation:
      "W. Langdon Kihn, “Chumash Canoes,” artist's illustration. Public domain via Wikimedia Commons (File:Chumash Canoes.jpg).",
    url: "https://commons.wikimedia.org/wiki/File:Chumash_Canoes.jpg",
    license: "Public domain",
  },
  {
    id: "img-chumash-tomol-elyewun-2006",
    src: "/images/myron-angel/chumash-tomol-elyewun-2006.jpg",
    caption:
      "Paddlers aboard the reconstructed Chumash tomol Elye'wun during the annual crossing to Santa Cruz Island (Limuw), 2006 — a modern revival of the plank-canoe tradition that once linked our mainland to the islands. Photograph, NOAA Channel Islands National Marine Sanctuary.",
    alt: "Photograph of Chumash paddlers in a plank tomol canoe on open water near Santa Cruz Island",
    topics: [
      "chumash",
      "tomol",
      "tomols",
      "plank canoe",
      "elye'wun",
      "channel islands",
      "limuw",
      "santa cruz island",
      "crossing",
      "paddling",
      "indigenous",
      "native",
    ],
    dateRange: "2006 (modern revival)",
    citation:
      "Robert Schwemmer, Chumash Tomol 'Elye'wun paddlers, Channel Islands NMS, 2006. NOAA Photo Library sanc0157. Public domain via Wikimedia Commons.",
    url: "https://commons.wikimedia.org/wiki/File:Chumash_Tomol_%27Elye%27wun_paddlers,_CINMS.jpg",
    license: "Public domain",
  },
  {
    id: "img-chumash-tomol-crossing-2015",
    src: "/images/myron-angel/chumash-tomol-crossing-2015.jpg",
    caption:
      "A Chumash tomol at sunrise during the Channel crossing to Limuw (Santa Cruz Island), September 2015 — paddlers rotating through the six-person crew on the 17-mile journey their ancestors made for centuries in these plank-built boats.",
    alt: "Sunrise photograph of a Chumash tomol plank canoe on the ocean during the Channel Islands crossing",
    topics: [
      "chumash",
      "tomol",
      "tomols",
      "plank canoe",
      "channel islands",
      "limuw",
      "crossing",
      "paddling",
      "sunrise",
      "indigenous",
      "native",
    ],
    dateRange: "2015 (modern revival)",
    citation:
      "National Marine Sanctuaries, Tomol Crossing Sunrise, Channel Islands NMS, September 2015. Public domain via Wikimedia Commons.",
    url: "https://commons.wikimedia.org/wiki/File:CINMS_-_Tomol_Crossing_Sunrise_.jpg",
    license: "Public domain",
  },
  {
    id: "img-ah-louis-store",
    src: "/images/myron-angel/ah-louis-store.jpg",
    caption:
      "The Ah Louis Store on Palm Street — opened in 1874 as the first Chinese-owned business in San Luis Obispo, a landmark of the Chinese pioneers who helped build our railroads and our town.",
    alt: "Photograph of the historic Ah Louis Store building in San Luis Obispo",
    topics: [
      "ah louis",
      "chinese",
      "chinese-american",
      "chinese community",
      "chinese pioneer",
      "palm street",
      "store",
      "merchant",
      "san luis obispo",
    ],
    dateRange: "1874–1900s",
    citation:
      "Ah Louis Store, San Luis Obispo. Photo via Wikimedia Commons (CC BY-SA 2.0).",
    url: "https://commons.wikimedia.org/wiki/File:Ah_Louis_Store.jpg",
    license: "CC BY-SA 2.0",
  },
  {
    id: "img-chinese-railroad-laborers",
    src: "/images/myron-angel/chinese-railroad-laborers.jpg",
    caption:
      "Chinese laborers on the Central Pacific Railroad in the 1860s — an engraving representative of the Chinese workers whose skill built California's railroads, including the tunnels on the Cuesta Grade above our town.",
    alt: "Historical illustration of Chinese railroad laborers at work on the Central Pacific Railroad",
    topics: [
      "chinese",
      "chinese laborers",
      "chinese workers",
      "railroad",
      "central pacific",
      "cuesta grade",
      "tunnel",
      "ah louis",
      "immigrant",
      "construction",
    ],
    dateRange: "1860s",
    citation:
      "“Central Pacific Railroad — Chinese Laborers at Work,” public-domain illustration via Wikimedia Commons.",
    url: "https://commons.wikimedia.org/wiki/File:Chinese_Railroad_Laborers.jpg",
    license: "Public domain",
  },
  {
    id: "img-gold-rush-mining-1883",
    src: "/images/myron-angel/gold-rush-mining-1883.jpg",
    caption:
      "Hydraulic gold mining in California — a scene from the great Gold Rush era that drew so many of us young men westward in the 1850s, myself among them.",
    alt: "1883 engraving of hydraulic gold mining in California by Henry Sandham",
    topics: [
      "gold rush",
      "forty-niner",
      "49er",
      "mining",
      "miners",
      "hydraulic mining",
      "1849",
      "1850",
      "sacramento",
      "california",
    ],
    dateRange: "c. 1883 (depicts 1850s mining)",
    citation:
      "Henry Sandham, “The Cradle” (hydraulic mining), The Century illustrated monthly magazine, Jan. 1883. Public domain via Wikimedia Commons.",
    url: "https://commons.wikimedia.org/wiki/File:Henry_Sandham_-_The_Cradle.jpg",
    license: "Public domain",
  },
  {
    id: "img-vaqueros-1854",
    src: "/images/myron-angel/california-vaqueros-1854.jpg",
    caption:
      "“California Vaqueros, Returned from the Chase” — an 1854 engraving of Californio horsemen and their families in the rancho days, before the Americans came in great numbers.",
    alt: "1854 engraving titled California Vaqueros, Returned from the Chase, showing Californio men, women, and horses",
    topics: [
      "vaquero",
      "vaqueros",
      "californio",
      "californios",
      "mexican",
      "mexicans",
      "spanish",
      "rancho",
      "ranchero",
      "horsemen",
      "cowboys",
      "rancho era",
      "people",
    ],
    dateRange: "1854",
    citation:
      "“California Vaqueros, Returned from the Chase” (1854), engraving for The Pacific. Courtesy of UC Berkeley, Bancroft Library, via Wikimedia Commons. Public domain.",
    url: "https://commons.wikimedia.org/wiki/File:California_Vaqueros,_1854.jpg",
    license: "Public domain",
  },
  {
    id: "img-rancho-roundup",
    src: "/images/myron-angel/rancho-roundup.jpg",
    caption:
      "A painting of a rancho rodeo — the great cattle round-up that was the heart of ranching life in the Spanish and Mexican days, vaqueros on horseback working the herds.",
    alt: "Painting of a California rancho cattle round-up with vaqueros on horseback and cattle on open land",
    topics: [
      "ranching",
      "rancho",
      "rodeo",
      "round-up",
      "cattle",
      "cows",
      "livestock",
      "vaquero",
      "vaqueros",
      "ranchero",
      "agriculture",
      "spanish era",
      "mexican era",
    ],
    dateRange: "c. 1840–1880",
    citation:
      "“Painting of a Spanish Rancho cattle round-up,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/3460d549a830ef1092735174158b52eb/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-rancho-fandango-1873",
    src: "/images/myron-angel/rancho-fandango-1873.jpg",
    caption:
      "“The Fandango” (1873) by Charles Nahl — a lively painting of rancho life in the Mexican era: a fiesta with dancing, music, feasting, and vaqueros at their horses.",
    alt: "Colorful 1873 painting titled The Fandango showing Californios dancing and celebrating at a rancho fiesta",
    topics: [
      "fiesta",
      "fandango",
      "dancing",
      "dance",
      "music",
      "celebration",
      "food",
      "feast",
      "party",
      "rancho",
      "californio",
      "californios",
      "mexican era",
      "spanish",
      "daily life",
      "culture",
    ],
    dateRange: "1873",
    citation:
      "“The Fandango” (1873) by Charles Christian Nahl, Crocker Art Museum, E. B. Crocker Collection, via Wikimedia Commons. Public domain (CC0).",
    url: "https://commons.wikimedia.org/wiki/File:The_Fandango.JPG",
    license: "Public domain (CC0)",
  },
  {
    id: "img-slo-creek-1905",
    src: "/images/myron-angel/slo-creek-1905.jpg",
    caption:
      "San Luis Obispo Creek, about 1905 — the stream winding through a grove of old twisted trees, the wild country just beyond the town.",
    alt: "Black-and-white photograph of San Luis Obispo Creek around 1905 running through trees",
    topics: [
      "creek",
      "san luis obispo creek",
      "stream",
      "river",
      "water",
      "trees",
      "forest",
      "woods",
      "wilderness",
      "nature",
      "countryside",
      "landscape",
    ],
    dateRange: "c. 1905",
    citation:
      "“San Luis Obispo Creek running through a forest, ca.1905,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/95ffe674234bddbcbac3ef489820ddf5/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-cal-poly-1900",
    src: "/images/myron-angel/cal-poly-1900.jpg",
    caption:
      "The California Polytechnic School on its hill outside town, in its earliest days — the hard-won vocational school I fought to bring to San Luis Obispo, opened to its first students in 1903.",
    alt: "Black-and-white photograph of the early California Polytechnic School buildings on a grassy hillside",
    topics: [
      "polytechnic",
      "cal poly",
      "california polytechnic school",
      "school",
      "college",
      "education",
      "campus",
      "vocational",
      "learn by doing",
      "students",
      "buildings",
    ],
    dateRange: "c. 1903",
    citation:
      "“Exterior view of California Polytechnic and Agriculture College, San Luis Obispo, ca.1900,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/2ca859090a1324acee9b408616481a6e/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-mission-1883",
    src: "/images/myron-angel/mission-1883.jpg",
    caption:
      "“The Mission San Luis Obispo, 1883” — an engraving from my own History of San Luis Obispo County, showing the mission with carriages and townsfolk on the street.",
    alt: "1883 engraving of Mission San Luis Obispo de Tolosa with a horse carriage and people in Victorian dress",
    topics: [
      "mission",
      "san luis obispo de tolosa",
      "mission san luis obispo",
      "spanish era",
      "church",
      "engraving",
      "1883 history",
      "carriage",
      "founding 1772",
    ],
    dateRange: "1883",
    citation:
      "“The Mission San Luis Obispo” (1883), illustration from History of San Luis Obispo County by Myron Angel. Wikimedia Commons.",
    url: "https://commons.wikimedia.org/wiki/File:History_of_San_Luis_Obispo_County,_California;_with_illustrations_and_biographical_sketches_of_its_prominent_men_and_pioneers_(1883)_(14594368737).jpg",
    license: "Public domain",
  },
  {
    id: "img-mission-1900",
    src: "/images/myron-angel/mission-1900.jpg",
    caption:
      "Mission San Luis Obispo de Tolosa (founded 1772), in a color view from around the turn of the century.",
    alt: "Color postcard of Mission San Luis Obispo de Tolosa, around 1900, with a robed friar in front",
    topics: [
      "mission",
      "san luis obispo de tolosa",
      "mission san luis obispo",
      "spanish era",
      "padres",
      "friar",
      "church",
      "founding 1772",
      "postcard",
    ],
    dateRange: "c. 1900",
    citation:
      "Mission San Luis Obispo de Tolosa, c. 1900 postcard. The New York Public Library.",
    url: "https://commons.wikimedia.org/wiki/File:Mission_San_Luis_Obispo_De_Tolosa,_California_(NYPL_b12647398-74244).tiff",
    license: "Public domain",
  },
  {
    id: "img-courthouse-1900",
    src: "/images/myron-angel/courthouse-1900.jpg",
    caption:
      "The San Luis Obispo County Courthouse and Hall of Records, built in 1873 — the seat of county government in our growing town, about 1900.",
    alt: "Black-and-white photograph of the San Luis Obispo County Courthouse around 1900",
    topics: [
      "courthouse",
      "court house",
      "county government",
      "hall of records",
      "monterey street",
      "osos street",
      "government",
      "buildings",
    ],
    dateRange: "c. 1900",
    citation:
      "“Exterior view of the Court House, San Luis Obispo County, ca.1900,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/a745d5a0dd81f24265e35279fb851db0/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-monterey-street-1900",
    src: "/images/myron-angel/monterey-street-1900.jpg",
    caption:
      "Monterey Street looking east toward Chorro Street, about 1900 — a wide dirt road lined with trees and fences in the heart of town.",
    alt: "Black-and-white photograph of Monterey Street in San Luis Obispo around 1900 looking east",
    topics: [
      "monterey street",
      "chorro street",
      "downtown",
      "streets",
      "old town",
      "roadways",
    ],
    dateRange: "c. 1900",
    citation:
      "“Monterey Street looking east to where it meets Chorro Street, San Luis Obispo, ca.1900,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/2928cec9a23e7dff465eeafa86d1a93d/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-adobe-rancho-1900",
    src: "/images/myron-angel/adobe-rancho-1900.jpg",
    caption:
      "Ruins of an adobe ranch house at Rancho Santa Isabel, about 1900 — a reminder of the Mexican rancho era when great land grants shaped our county.",
    alt: "Black-and-white photograph of adobe ranch house ruins on a grassy hill around 1900",
    topics: [
      "adobe",
      "rancho",
      "ranch house",
      "mexican era",
      "spanish era",
      "ruins",
      "architecture",
      "land grant",
    ],
    dateRange: "c. 1900",
    citation:
      "“View of adobe ranch house ruins, Rancho Santa Isabel, San Luis Obispo County, ca.1900,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/a9e5aecd21aaed323f2da5b5eeba9739/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-railroad-slo-1906",
    src: "/images/myron-angel/railroad-slo-1906.jpg",
    caption:
      "San Luis Obispo looking north, about 1906 — Southern Pacific trains and tracks threading through the town, a symbol of the railroad age that transformed our valley.",
    alt: "Black-and-white panoramic photograph of San Luis Obispo around 1906 with railroad trains",
    topics: [
      "railroad",
      "southern pacific",
      "trains",
      "depot",
      "station",
      "tracks",
      "transportation",
      "commerce",
    ],
    dateRange: "c. 1905–1906",
    citation:
      "“Panoramic view of San Luis Obispo looking north, ca.1906,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/5fc53f0e4edaa907639dc6052e3d742f/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-mission-south-1888",
    src: "/images/myron-angel/mission-south-1888.jpg",
    caption:
      "The south wing of Mission San Luis Obispo de Tolosa, photographed in 1888 — the adobe mission church much as I knew it when compiling my county history.",
    alt: "1888 photograph of the south wing of Mission San Luis Obispo with mountains in the background",
    topics: [
      "mission",
      "san luis obispo de tolosa",
      "mission san luis obispo",
      "south wing",
      "adobe",
      "church",
      "spanish era",
      "founding 1772",
    ],
    dateRange: "1888",
    citation:
      "“Exterior view of the south wing of the Mission San Luis Obispo de Tolosa, 1888,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/4c803e2c3db4e05bcfadb0ec84766c44/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-mission-front-1880",
    src: "/images/myron-angel/mission-front-1880.jpg",
    caption:
      "The main front of Mission San Luis Obispo de Tolosa, about 1875–1880 — broad stairs rising to the entrance, a stone balustrade, and the great tree that shaded the faithful in my day.",
    alt: "1875–1880 photograph of the main facade and stairs of Mission San Luis Obispo de Tolosa",
    topics: [
      "mission",
      "san luis obispo de tolosa",
      "mission san luis obispo",
      "main front",
      "facade",
      "entrance",
      "stairs",
      "church",
      "spanish era",
      "founding 1772",
    ],
    dateRange: "c. 1875–1880",
    citation:
      "“Main front of Mission San Luis Obispo de Tolosa, ca.1875-1880,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/493b6fd44d59b64b5ce74126ac405efb/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-mission-arcade-1870",
    src: "/images/myron-angel/mission-arcade-1870.jpg",
    caption:
      "El portico of Mission San Luis Obispo de Tolosa, about 1865 — a long corridor of columns and balustrades along the adobe arcade, much as the fathers knew it in the rancho era.",
    alt: "1865 photograph of the columned portico and arcade at Mission San Luis Obispo de Tolosa",
    topics: [
      "mission",
      "san luis obispo de tolosa",
      "mission san luis obispo",
      "arcade",
      "portico",
      "columns",
      "corridor",
      "courtyard",
      "adobe",
      "church",
      "spanish era",
      "founding 1772",
    ],
    dateRange: "c. 1865",
    citation:
      "“El portico of the Mission San Luis Obispo de Tolosa, ca.1865,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/5f7cb9654cf37420b9f221553fa702fe/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-mission-exterior",
    src: "/images/myron-angel/mission-exterior.jpg",
    caption:
      "Mission San Luis Obispo de Tolosa — the arched entrance to the church, open bell tower, and adobe walls as the Franciscan fathers knew them.",
    alt: "Historic photograph of Mission San Luis Obispo exterior with arched church entrance and bell tower",
    topics: [
      "mission",
      "san luis obispo de tolosa",
      "mission san luis obispo",
      "bell tower",
      "arched entrance",
      "facade",
      "franciscan",
      "padres",
      "church",
      "spanish era",
      "founding 1772",
    ],
    dateRange: "19th century",
    citation:
      "“Exterior view of the Mission San Luis Obispo,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/2408407390142882fb02ba7bbb7613e2/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-mission-view-south-1904",
    src: "/images/myron-angel/mission-view-south-1904.jpg",
    caption:
      "Mission San Luis Obispo de Tolosa viewed from the south, about 1904 — the adobe walls, wooden bell tower, and the stone wall along the street as worshippers arrived for Mass.",
    alt: "1904 photograph of Mission San Luis Obispo de Tolosa viewed from the south with nuns on the sidewalk",
    topics: [
      "mission",
      "san luis obispo de tolosa",
      "mission san luis obispo",
      "south view",
      "bell tower",
      "adobe",
      "mass",
      "church",
      "spanish era",
      "founding 1772",
    ],
    dateRange: "c. 1904",
    citation:
      "“View from the south of Mission San Luis Obispo de Tolosa,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/8c3535bad51b86437c15b56e54657ab5/",
    license: "Public domain (CC BY)",
  },
];
