import type { ImageAsset } from "@/lib/types";

/**
 * SERVER-ONLY image library for Myron Angel.
 *
 * Every image here was visually verified and is public domain. Captions and
 * citations describe exactly what the image shows — never claim an image
 * depicts something it does not.
 *
 * To add more: drop a file in /public/images/myron-angel/, add an entry with an
 * accurate caption + citation + license, and it becomes retrievable.
 */
export const myronAngelImages: ImageAsset[] = [
  {
    id: "img-portrait",
    src: "/images/myron-angel/myron-portrait.jpg",
    caption: "Myron Angel (1827–1911), journalist and historian of San Luis Obispo.",
    alt: "Engraved portrait of an older bearded man, Myron Angel",
    topics: ["myron angel", "portrait", "appearance", "biography", "yourself"],
    dateRange: "c. 1880s",
    citation: "Public-domain portrait of Myron Angel.",
    license: "Public domain",
  },
  {
    id: "img-slo-street-1905",
    src: "/images/myron-angel/slo-street-1905.jpg",
    caption:
      "A commercial street in San Luis Obispo about 1905 — storefronts, awnings, carriages, and townsfolk going about their business in our growing downtown.",
    alt: "Black-and-white photograph of a San Luis Obispo commercial street around 1905 with storefronts, horse-drawn carriages, and pedestrians",
    topics: [
      "downtown",
      "old town",
      "main street",
      "higuera street",
      "streets",
      "shops",
      "stores",
      "businesses",
      "buildings",
      "town",
      "city",
      "1905",
      "everyday life",
    ],
    dateRange: "c. 1905",
    citation:
      "“View of a commercial street in San Luis Obispo, ca.1905,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/2572c81f8c70aa16f400d697c504a5f8/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-slo-view-1900",
    src: "/images/myron-angel/slo-view-1900.jpg",
    caption:
      "A view of San Luis Obispo about the year 1900, the town spread out in its valley beneath our familiar volcanic peaks.",
    alt: "Black-and-white photograph of San Luis Obispo around 1900 showing the town below two mountain peaks",
    topics: [
      "town",
      "city",
      "view",
      "panorama",
      "landscape",
      "valley",
      "peaks",
      "morros",
      "hills",
      "san luis obispo",
      "1900",
    ],
    dateRange: "c. 1900",
    citation:
      "“View of San Luis Obispo, ca.1900,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/a1971025247e3761965bdd17e4ea5cf8/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-morro-rock-1900",
    src: "/images/myron-angel/morro-rock-1900.jpg",
    caption:
      "Morro Rock and the bay, about 1900 — the great volcanic dome standing sentinel over the water, with small sailing boats drawn up on the shore.",
    alt: "Black-and-white photograph of Morro Rock around 1900 with sailboats on the shore",
    topics: [
      "morro rock",
      "morro bay",
      "coast",
      "ocean",
      "bay",
      "rock",
      "wilderness",
      "nature",
      "landscape",
      "boats",
      "seven sisters",
      "volcanic peaks",
    ],
    dateRange: "c. 1900",
    citation:
      "“View of Morro Rock, showing sailboats, ca.1900,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/c1f1f5a253b4a99a54b7990e2e0af6c8/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-avila-beach-1905",
    src: "/images/myron-angel/avila-beach-1905.jpg",
    caption:
      "Avila Beach, near San Luis Obispo, about 1905 — the rocky shore and hills of our coast, with a few houses set along the ridge.",
    alt: "Black-and-white photograph of Avila Beach around 1905 showing a rocky coastline and hills",
    topics: [
      "avila",
      "avila beach",
      "coast",
      "beach",
      "ocean",
      "seaside",
      "shore",
      "bay",
      "wilderness",
      "san luis obispo",
    ],
    dateRange: "c. 1905",
    citation:
      "“View of Avila Beach, near San Luis Obispo, ca.1905,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/d3d370747668a728278b64f1a98ce33c/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-port-harford-1905",
    src: "/images/myron-angel/port-harford-1905.jpg",
    caption:
      "The wharf at Port Harford, about 1905 — our county's great ocean landing, its railroad tracks running out to the steamships that carry our produce to market.",
    alt: "Black-and-white photograph of the long Port Harford wharf around 1905 with railroad tracks and steamships",
    topics: [
      "port harford",
      "port san luis",
      "avila",
      "wharf",
      "pier",
      "harbor",
      "shipping",
      "steamship",
      "railroad",
      "commerce",
      "trade",
      "ocean",
    ],
    dateRange: "c. 1905",
    citation:
      "“View of Port Harford wharf, San Luis Obispo County, ca.1905,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/b4c79a58ac9461ee99f330af59b0b2fe/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-chumash-musicians-1873",
    src: "/images/myron-angel/chumash-musicians-1873.jpg",
    caption:
      "Chumash musicians photographed in 1873 — the Chumash are the native people of this Central Coast, here at Mission San Buenaventura to the south, holding their instruments.",
    alt: "Sepia 1873 photograph of six seated Chumash men holding musical instruments",
    topics: [
      "chumash",
      "native",
      "natives",
      "indians",
      "indigenous",
      "first peoples",
      "native americans",
      "tribe",
      "music",
      "mission",
    ],
    dateRange: "1873",
    citation:
      "“Chumash musicians at Mission San Buenaventura,” 1873. Black Gold Cooperative Library System; image from the Santa Barbara Historical Society. Public domain.",
    url: "https://www.luna.blackgold.org/luna/servlet/detail/blackgold~3~3~217~1407",
    license: "Public domain",
  },
  {
    id: "img-vaqueros-1854",
    src: "/images/myron-angel/california-vaqueros-1854.jpg",
    caption:
      "“California Vaqueros, Returned from the Chase” — an 1854 engraving of Californio horsemen and their families in the rancho days, before the Americans came in great numbers.",
    alt: "1854 engraving titled California Vaqueros, Returned from the Chase, showing Californio men, women, and horses",
    topics: [
      "vaquero",
      "vaqueros",
      "californio",
      "californios",
      "mexican",
      "mexicans",
      "spanish",
      "rancho",
      "ranchero",
      "horsemen",
      "cowboys",
      "rancho era",
      "people",
    ],
    dateRange: "1854",
    citation:
      "“California Vaqueros, Returned from the Chase” (1854), engraving for The Pacific. Courtesy of UC Berkeley, Bancroft Library, via Wikimedia Commons. Public domain.",
    url: "https://commons.wikimedia.org/wiki/File:California_Vaqueros,_1854.jpg",
    license: "Public domain",
  },
  {
    id: "img-rancho-roundup",
    src: "/images/myron-angel/rancho-roundup.jpg",
    caption:
      "A painting of a rancho rodeo — the great cattle round-up that was the heart of ranching life in the Spanish and Mexican days, vaqueros on horseback working the herds.",
    alt: "Painting of a California rancho cattle round-up with vaqueros on horseback and cattle on open land",
    topics: [
      "ranching",
      "rancho",
      "rodeo",
      "round-up",
      "cattle",
      "cows",
      "livestock",
      "vaquero",
      "vaqueros",
      "ranchero",
      "agriculture",
      "spanish era",
      "mexican era",
    ],
    dateRange: "c. 1840–1880",
    citation:
      "“Painting of a Spanish Rancho cattle round-up,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/3460d549a830ef1092735174158b52eb/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-rancho-fandango-1873",
    src: "/images/myron-angel/rancho-fandango-1873.jpg",
    caption:
      "“The Fandango” (1873) by Charles Nahl — a lively painting of rancho life in the Mexican era: a fiesta with dancing, music, feasting, and vaqueros at their horses.",
    alt: "Colorful 1873 painting titled The Fandango showing Californios dancing and celebrating at a rancho fiesta",
    topics: [
      "fiesta",
      "fandango",
      "dancing",
      "dance",
      "music",
      "celebration",
      "food",
      "feast",
      "party",
      "rancho",
      "californio",
      "californios",
      "mexican era",
      "spanish",
      "daily life",
      "culture",
    ],
    dateRange: "1873",
    citation:
      "“The Fandango” (1873) by Charles Christian Nahl, Crocker Art Museum, E. B. Crocker Collection, via Wikimedia Commons. Public domain (CC0).",
    url: "https://commons.wikimedia.org/wiki/File:The_Fandango.JPG",
    license: "Public domain (CC0)",
  },
  {
    id: "img-slo-creek-1905",
    src: "/images/myron-angel/slo-creek-1905.jpg",
    caption:
      "San Luis Obispo Creek, about 1905 — the stream winding through a grove of old twisted trees, the wild country just beyond the town.",
    alt: "Black-and-white photograph of San Luis Obispo Creek around 1905 running through trees",
    topics: [
      "creek",
      "san luis obispo creek",
      "stream",
      "river",
      "water",
      "trees",
      "forest",
      "woods",
      "wilderness",
      "nature",
      "countryside",
      "landscape",
    ],
    dateRange: "c. 1905",
    citation:
      "“San Luis Obispo Creek running through a forest, ca.1905,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/95ffe674234bddbcbac3ef489820ddf5/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-cal-poly-1900",
    src: "/images/myron-angel/cal-poly-1900.jpg",
    caption:
      "The California Polytechnic School on its hill outside town, in its earliest days — the hard-won vocational school I fought to bring to San Luis Obispo, opened to its first students in 1903.",
    alt: "Black-and-white photograph of the early California Polytechnic School buildings on a grassy hillside",
    topics: [
      "polytechnic",
      "cal poly",
      "california polytechnic school",
      "school",
      "college",
      "education",
      "campus",
      "vocational",
      "learn by doing",
      "students",
      "buildings",
    ],
    dateRange: "c. 1903",
    citation:
      "“Exterior view of California Polytechnic and Agriculture College, San Luis Obispo, ca.1900,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/2ca859090a1324acee9b408616481a6e/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-mission-1883",
    src: "/images/myron-angel/mission-1883.jpg",
    caption:
      "“The Mission San Luis Obispo, 1883” — an engraving from my own History of San Luis Obispo County, showing the mission with carriages and townsfolk on the street.",
    alt: "1883 engraving of Mission San Luis Obispo de Tolosa with a horse carriage and people in Victorian dress",
    topics: [
      "mission",
      "san luis obispo de tolosa",
      "mission san luis obispo",
      "spanish era",
      "church",
      "engraving",
      "1883 history",
      "carriage",
      "founding 1772",
    ],
    dateRange: "1883",
    citation:
      "“The Mission San Luis Obispo” (1883), illustration from History of San Luis Obispo County by Myron Angel. Wikimedia Commons.",
    url: "https://commons.wikimedia.org/wiki/File:History_of_San_Luis_Obispo_County,_California;_with_illustrations_and_biographical_sketches_of_its_prominent_men_and_pioneers_(1883)_(14594368737).jpg",
    license: "Public domain",
  },
  {
    id: "img-mission-1900",
    src: "/images/myron-angel/mission-1900.jpg",
    caption:
      "Mission San Luis Obispo de Tolosa (founded 1772), in a color view from around the turn of the century.",
    alt: "Color postcard of Mission San Luis Obispo de Tolosa, around 1900, with a robed friar in front",
    topics: [
      "mission",
      "san luis obispo de tolosa",
      "mission san luis obispo",
      "spanish era",
      "padres",
      "friar",
      "church",
      "founding 1772",
      "postcard",
    ],
    dateRange: "c. 1900",
    citation:
      "Mission San Luis Obispo de Tolosa, c. 1900 postcard. The New York Public Library.",
    url: "https://commons.wikimedia.org/wiki/File:Mission_San_Luis_Obispo_De_Tolosa,_California_(NYPL_b12647398-74244).tiff",
    license: "Public domain",
  },
  {
    id: "img-courthouse-1900",
    src: "/images/myron-angel/courthouse-1900.jpg",
    caption:
      "The San Luis Obispo County Courthouse and Hall of Records, built in 1873 — the seat of county government in our growing town, about 1900.",
    alt: "Black-and-white photograph of the San Luis Obispo County Courthouse around 1900",
    topics: [
      "courthouse",
      "court house",
      "county government",
      "hall of records",
      "monterey street",
      "osos street",
      "government",
      "buildings",
    ],
    dateRange: "c. 1900",
    citation:
      "“Exterior view of the Court House, San Luis Obispo County, ca.1900,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/a745d5a0dd81f24265e35279fb851db0/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-monterey-street-1900",
    src: "/images/myron-angel/monterey-street-1900.jpg",
    caption:
      "Monterey Street looking east toward Chorro Street, about 1900 — a wide dirt road lined with trees and fences in the heart of town.",
    alt: "Black-and-white photograph of Monterey Street in San Luis Obispo around 1900 looking east",
    topics: [
      "monterey street",
      "chorro street",
      "downtown",
      "streets",
      "old town",
      "roadways",
    ],
    dateRange: "c. 1900",
    citation:
      "“Monterey Street looking east to where it meets Chorro Street, San Luis Obispo, ca.1900,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/2928cec9a23e7dff465eeafa86d1a93d/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-adobe-rancho-1900",
    src: "/images/myron-angel/adobe-rancho-1900.jpg",
    caption:
      "Ruins of an adobe ranch house at Rancho Santa Isabel, about 1900 — a reminder of the Mexican rancho era when great land grants shaped our county.",
    alt: "Black-and-white photograph of adobe ranch house ruins on a grassy hill around 1900",
    topics: [
      "adobe",
      "rancho",
      "ranch house",
      "mexican era",
      "spanish era",
      "ruins",
      "architecture",
      "land grant",
    ],
    dateRange: "c. 1900",
    citation:
      "“View of adobe ranch house ruins, Rancho Santa Isabel, San Luis Obispo County, ca.1900,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/a9e5aecd21aaed323f2da5b5eeba9739/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-railroad-slo-1906",
    src: "/images/myron-angel/railroad-slo-1906.jpg",
    caption:
      "San Luis Obispo looking north, about 1906 — Southern Pacific trains and tracks threading through the town, a symbol of the railroad age that transformed our valley.",
    alt: "Black-and-white panoramic photograph of San Luis Obispo around 1906 with railroad trains",
    topics: [
      "railroad",
      "southern pacific",
      "trains",
      "depot",
      "station",
      "tracks",
      "transportation",
      "commerce",
    ],
    dateRange: "c. 1905–1906",
    citation:
      "“Panoramic view of San Luis Obispo looking north, ca.1906,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/5fc53f0e4edaa907639dc6052e3d742f/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-mission-south-1888",
    src: "/images/myron-angel/mission-south-1888.jpg",
    caption:
      "The south wing of Mission San Luis Obispo de Tolosa, photographed in 1888 — the adobe mission church much as I knew it when compiling my county history.",
    alt: "1888 photograph of the south wing of Mission San Luis Obispo with mountains in the background",
    topics: [
      "mission",
      "san luis obispo de tolosa",
      "mission san luis obispo",
      "south wing",
      "adobe",
      "church",
      "spanish era",
      "founding 1772",
    ],
    dateRange: "1888",
    citation:
      "“Exterior view of the south wing of the Mission San Luis Obispo de Tolosa, 1888,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/4c803e2c3db4e05bcfadb0ec84766c44/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-mission-front-1880",
    src: "/images/myron-angel/mission-front-1880.jpg",
    caption:
      "The main front of Mission San Luis Obispo de Tolosa, about 1875–1880 — broad stairs rising to the entrance, a stone balustrade, and the great tree that shaded the faithful in my day.",
    alt: "1875–1880 photograph of the main facade and stairs of Mission San Luis Obispo de Tolosa",
    topics: [
      "mission",
      "san luis obispo de tolosa",
      "mission san luis obispo",
      "main front",
      "facade",
      "entrance",
      "stairs",
      "church",
      "spanish era",
      "founding 1772",
    ],
    dateRange: "c. 1875–1880",
    citation:
      "“Main front of Mission San Luis Obispo de Tolosa, ca.1875-1880,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/493b6fd44d59b64b5ce74126ac405efb/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-mission-arcade-1870",
    src: "/images/myron-angel/mission-arcade-1870.jpg",
    caption:
      "El portico of Mission San Luis Obispo de Tolosa, about 1865 — a long corridor of columns and balustrades along the adobe arcade, much as the fathers knew it in the rancho era.",
    alt: "1865 photograph of the columned portico and arcade at Mission San Luis Obispo de Tolosa",
    topics: [
      "mission",
      "san luis obispo de tolosa",
      "mission san luis obispo",
      "arcade",
      "portico",
      "columns",
      "corridor",
      "courtyard",
      "adobe",
      "church",
      "spanish era",
      "founding 1772",
    ],
    dateRange: "c. 1865",
    citation:
      "“El portico of the Mission San Luis Obispo de Tolosa, ca.1865,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/5f7cb9654cf37420b9f221553fa702fe/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-mission-exterior",
    src: "/images/myron-angel/mission-exterior.jpg",
    caption:
      "Mission San Luis Obispo de Tolosa — the arched entrance to the church, open bell tower, and adobe walls as the Franciscan fathers knew them.",
    alt: "Historic photograph of Mission San Luis Obispo exterior with arched church entrance and bell tower",
    topics: [
      "mission",
      "san luis obispo de tolosa",
      "mission san luis obispo",
      "bell tower",
      "arched entrance",
      "facade",
      "franciscan",
      "padres",
      "church",
      "spanish era",
      "founding 1772",
    ],
    dateRange: "19th century",
    citation:
      "“Exterior view of the Mission San Luis Obispo,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/2408407390142882fb02ba7bbb7613e2/",
    license: "Public domain (CC BY)",
  },
  {
    id: "img-mission-view-south-1904",
    src: "/images/myron-angel/mission-view-south-1904.jpg",
    caption:
      "Mission San Luis Obispo de Tolosa viewed from the south, about 1904 — the adobe walls, wooden bell tower, and the stone wall along the street as worshippers arrived for Mass.",
    alt: "1904 photograph of Mission San Luis Obispo de Tolosa viewed from the south with nuns on the sidewalk",
    topics: [
      "mission",
      "san luis obispo de tolosa",
      "mission san luis obispo",
      "south view",
      "bell tower",
      "adobe",
      "mass",
      "church",
      "spanish era",
      "founding 1772",
    ],
    dateRange: "c. 1904",
    citation:
      "“View from the south of Mission San Luis Obispo de Tolosa,” California Historical Society Collection. Courtesy of USC Libraries and the California Historical Society. Public domain (CC BY).",
    url: "https://calisphere.org/item/8c3535bad51b86437c15b56e54657ab5/",
    license: "Public domain (CC BY)",
  },
];
