/**
 * Topic → buzzword → image map for Jesse D. Mason.
 */

import type { ImageTopic } from "@/personas/types";

export const MASON_IMAGE_TOPICS: ImageTopic[] = [
  {
    key: "identity",
    label: "Jesse D. Mason — who he is (illustrative likeness)",
    buzzwords: [
      "jesse d mason",
      "who are you",
      "introduce yourself",
      "historian",
      "chronicler",
      "portrait",
      "likeness",
      "biography",
      "myself",
      "i am",
    ],
    imageIds: ["img-portrait"],
  },
  {
    key: "mission-founding",
    label: "Mission Santa Barbara founding & Queen of the Missions",
    buzzwords: [
      "mission santa barbara",
      "queen of the missions",
      "founded 1786",
      "1786",
      "fermín lasuén",
      "lasuen",
      "franciscan",
      "padres",
      "tenth mission",
    ],
    imageIds: [
      "img-mission-watkins-1876",
      "img-mission-facade",
    ],
  },
  {
    key: "mission-facade",
    label: "Mission facade, towers, bells",
    buzzwords: [
      "facade",
      "towers",
      "twin towers",
      "bell",
      "bells",
      "chapel",
      "arcade",
      "convento",
      "church",
      "stone church",
    ],
    imageIds: [
      "img-mission-facade",
      "img-mission-chapel",
      "img-mission-bell-1904",
      "img-mission-watkins-1876",
    ],
  },
  {
    key: "franciscans",
    label: "Franciscan friars at the mission",
    buzzwords: [
      "franciscan",
      "friars",
      "friars minor",
      "monks",
      "padres",
      "fathers",
      "continuous guidance",
    ],
    imageIds: ["img-franciscans-1904", "img-mission-chapel"],
  },
  {
    key: "chumash-verified",
    label: "Chumash people (verified images)",
    buzzwords: [
      "chumash",
      "indigenous",
      "native peoples",
      "first peoples",
      "barbareño",
      "canalino",
      "village",
      "acorn",
    ],
    imageIds: [
      "img-chumash-painted-cave",
      "img-chumash-musicians-1873",
      "img-chumash-tomol-kihn",
    ],
  },
  {
    key: "chumash-rock-art",
    label: "Chumash rock art",
    buzzwords: [
      "pictograph",
      "pictographs",
      "rock art",
      "painted cave",
      "cave painting",
      "spiritual",
    ],
    imageIds: ["img-chumash-painted-cave"],
  },
  {
    key: "chumash-tomol",
    label: "Chumash tomols & Channel Islands",
    buzzwords: [
      "tomol",
      "tomols",
      "plank canoe",
      "channel islands",
      "canoe",
      "seafaring",
      "asphaltum",
    ],
    imageIds: ["img-chumash-tomol-kihn"],
  },
  {
    key: "chumash-mission-era",
    label: "Chumash in the mission / post-contact period",
    buzzwords: [
      "mission san buenaventura",
      "musicians",
      "neophyte",
      "1873",
      "ventura",
      "post-contact",
    ],
    imageIds: ["img-chumash-musicians-1873"],
  },
  {
    key: "rancho-cattle",
    label: "Vaqueros, ranchos, cattle era",
    buzzwords: [
      "rancho",
      "ranchos",
      "vaquero",
      "vaqueros",
      "cattle",
      "californio",
      "californios",
      "mexican era",
      "hides",
      "tallow",
    ],
    imageIds: ["img-vaqueros-1854", "img-fandango-1873"],
  },
  {
    key: "rancho-fiesta",
    label: "Rancho fiesta & fandango",
    buzzwords: [
      "fandango",
      "fiesta",
      "dancing",
      "celebration",
      "feast",
      "social life",
    ],
    imageIds: ["img-fandango-1873"],
  },
  {
    key: "american-period",
    label: "American period & county settlement",
    buzzwords: [
      "american period",
      "american settlers",
      "pioneers",
      "statehood",
      "1850",
      "land act",
      "county seat",
    ],
    imageIds: ["img-mission-watkins-1876", "img-vaqueros-1854"],
  },
  {
    key: "ventura",
    label: "Ventura linked in the 1883 volume",
    buzzwords: [
      "ventura",
      "ventura county",
      "san buenaventura",
      "bound with santa barbara",
      "1872",
    ],
    imageIds: ["img-chumash-musicians-1873", "img-mission-watkins-1876"],
  },
];
