import type {
  PersonaSemanticVocab,
  SourceSemanticAnnotations,
} from "@/lib/semantic";

/** Controlled vocabulary for Jesse D. Mason. */
export const masonVocab: PersonaSemanticVocab = {
  people: [
    {
      id: "jesse-d-mason",
      label: "Jesse D. Mason",
      aliases: [
        "mason",
        "jesse mason",
        "jesse dimon mason",
        "j.d. mason",
        "j. d. mason",
      ],
    },
    {
      id: "junipero-serra",
      label: "Junípero Serra",
      aliases: ["father serra", "junipero serra", "fray junipero"],
    },
    {
      id: "fermin-lasuen",
      label: "Fermín Lasuén",
      aliases: ["lasuen", "lasuén", "father lasuen", "fermin lasuen"],
    },
  ],
  places: [
    {
      id: "santa-barbara",
      label: "Santa Barbara",
      aliases: ["santa barbara county", "sb", "the county"],
    },
    {
      id: "mission-santa-barbara",
      label: "Mission Santa Barbara",
      aliases: [
        "the mission",
        "queen of the missions",
        "santa barbara mission",
      ],
    },
    {
      id: "presidio-santa-barbara",
      label: "Santa Barbara Presidio",
      aliases: ["presidio", "el presidio", "presidio real"],
    },
    {
      id: "ventura",
      label: "Ventura",
      aliases: ["ventura county", "san buenaventura"],
    },
    {
      id: "channel-islands",
      label: "Channel Islands",
      aliases: ["santa barbara channel", "the islands", "channel coast"],
    },
    {
      id: "painted-cave",
      label: "Painted Cave",
      aliases: ["pictographs", "rock art sites"],
    },
    {
      id: "new-hampshire",
      label: "New Hampshire",
      aliases: ["new hampshire schoolteacher"],
    },
    {
      id: "amador-county",
      label: "Amador County",
      aliases: ["amador", "jackson valley", "ione"],
    },
    {
      id: "buena-vista",
      label: "Buena Vista",
      aliases: ["buena vista school district"],
    },
    {
      id: "oakland",
      label: "Oakland",
      aliases: ["oakland california"],
    },
    {
      id: "san-jose",
      label: "San Jose",
      aliases: ["san jose herald", "san jose mercury"],
    },
    {
      id: "los-gatos",
      label: "Los Gatos",
      aliases: ["los gatos mail"],
    },
    {
      id: "san-luis-obispo",
      label: "San Luis Obispo",
      aliases: ["slo", "san luis obispo tribune"],
    },
    {
      id: "california",
      label: "California",
      aliases: ["alta california", "the state"],
    },
  ],
  organizations: [
    {
      id: "thompson-west",
      label: "Thompson & West",
      aliases: ["thompson and west", "thompson & west"],
    },
    {
      id: "franciscan-order",
      label: "Franciscan order",
      aliases: ["franciscans", "franciscan", "padres"],
    },
    {
      id: "catholic-church",
      label: "Catholic Church",
      aliases: ["catholic", "the church"],
    },
    {
      id: "republican-party",
      label: "Republican Party",
      aliases: ["republican", "republican ticket"],
    },
    {
      id: "san-luis-obispo-tribune",
      label: "San Luis Obispo Tribune",
      aliases: ["tribune", "slo tribune"],
    },
    {
      id: "los-gatos-mail",
      label: "Los Gatos Mail",
      aliases: ["the mail", "los gatos mail"],
    },
    {
      id: "amador-county-archives",
      label: "Amador County Archives",
      aliases: ["amador archives"],
    },
  ],
  events: [
    {
      id: "mission-founding",
      label: "Mission founding",
      aliases: [
        "founded the mission",
        "mission founded",
        "1786",
        "queen of the missions",
      ],
    },
    {
      id: "presidio-founding",
      label: "Presidio founding",
      aliases: ["presidio established", "1782", "raised the cross"],
    },
    {
      id: "earthquake-1812",
      label: "1812 earthquake",
      aliases: ["great earthquake", "1812 quake", "church destroyed"],
    },
    {
      id: "secularization",
      label: "Mission secularization",
      aliases: ["secularization", "mexican rule", "1834"],
    },
    {
      id: "mission-returned-1865",
      label: "Mission returned 1865",
      aliases: ["returned to the church", "1865 return", "property restored"],
    },
    {
      id: "ventura-county-created",
      label: "Ventura County created",
      aliases: ["ventura organized", "1872", "county split"],
    },
    {
      id: "droughts-1860s",
      label: "1860s droughts",
      aliases: ["drought", "droughts", "1862", "1864"],
    },
    {
      id: "mexican-american-war",
      label: "Mexican–American War",
      aliases: ["american conquest", "mexican war", "1846"],
    },
    {
      id: "california-statehood",
      label: "California statehood",
      aliases: ["statehood", "1850", "became a state"],
    },
    {
      id: "treaty-guadalupe-hidalgo",
      label: "Treaty of Guadalupe Hidalgo",
      aliases: ["guadalupe hidalgo", "1848 treaty", "land act"],
    },
    {
      id: "county-history-1883",
      label: "1883 county history",
      aliases: [
        "history of santa barbara",
        "thompson west volume",
        "mug book",
        "1883 history",
      ],
    },
  ],
  periods: [
    {
      id: "pre-contact",
      label: "Pre-contact Chumash era",
      yearStart: 1,
      yearEnd: 1769,
      aliases: ["pre-contact", "before the spanish", "chumash homeland"],
    },
    {
      id: "spanish-mission",
      label: "Spanish mission era",
      yearStart: 1769,
      yearEnd: 1821,
      aliases: ["spanish period", "mission era", "spanish era"],
    },
    {
      id: "mexican-period",
      label: "Mexican period",
      yearStart: 1821,
      yearEnd: 1848,
      aliases: ["mexican era", "rancho era", "secularization era"],
    },
    {
      id: "early-statehood",
      label: "Early statehood",
      yearStart: 1850,
      yearEnd: 1880,
      aliases: ["american period", "early california", "after statehood"],
    },
    {
      id: "county-historian-years",
      label: "County historian years",
      yearStart: 1879,
      yearEnd: 1885,
      aliases: ["oakland years", "editor years", "thompson west years"],
    },
  ],
};

/** Hand tags for curated Mason sources. */
export const masonSourceAnnotations: SourceSemanticAnnotations = {
  "bio-identity": {
    people: ["jesse-d-mason"],
    places: ["santa-barbara", "oakland"],
    organizations: ["thompson-west"],
    events: ["county-history-1883"],
    yearStart: 1883,
    yearEnd: 1883,
    period: "county-historian-years",
  },
  "bio-new-hampshire": {
    people: ["jesse-d-mason"],
    places: ["new-hampshire", "california"],
    yearStart: 1840,
    yearEnd: 1859,
  },
  "bio-amador-farm": {
    people: ["jesse-d-mason"],
    places: ["amador-county"],
    yearStart: 1859,
    yearEnd: 1879,
    period: "early-statehood",
  },
  "bio-amador-civic": {
    people: ["jesse-d-mason"],
    places: ["amador-county", "buena-vista"],
    organizations: ["republican-party", "amador-county-archives"],
    yearStart: 1861,
    yearEnd: 1879,
    period: "early-statehood",
  },
  "bio-oakland-editor": {
    people: ["jesse-d-mason"],
    places: ["oakland", "san-jose", "los-gatos", "san-luis-obispo"],
    organizations: [
      "san-luis-obispo-tribune",
      "los-gatos-mail",
    ],
    yearStart: 1879,
    yearEnd: 1885,
    period: "county-historian-years",
  },
  "bio-amador-history": {
    people: ["jesse-d-mason"],
    places: ["amador-county", "santa-barbara", "ventura"],
    organizations: ["thompson-west"],
    events: ["county-history-1883"],
    yearStart: 1881,
    yearEnd: 1883,
    period: "county-historian-years",
  },
  "bio-no-portrait": {
    people: ["jesse-d-mason"],
    yearStart: 1885,
    yearEnd: 1885,
  },
  "philosophy-county-history": {
    people: ["jesse-d-mason"],
    organizations: ["thompson-west"],
    events: ["county-history-1883"],
    yearStart: 1883,
    yearEnd: 1883,
    period: "county-historian-years",
  },
  "county-book-1883": {
    people: ["jesse-d-mason"],
    places: ["santa-barbara", "oakland"],
    organizations: ["thompson-west"],
    events: ["county-history-1883"],
    yearStart: 1883,
    yearEnd: 1883,
    period: "county-historian-years",
  },
  "county-ventura-linked": {
    people: ["jesse-d-mason"],
    places: ["santa-barbara", "ventura"],
    organizations: ["thompson-west"],
    events: ["county-history-1883", "ventura-county-created"],
    yearStart: 1872,
    yearEnd: 1883,
  },
  "county-ventura-created": {
    places: ["ventura", "santa-barbara"],
    events: ["ventura-county-created"],
    yearStart: 1872,
    yearEnd: 1873,
    period: "early-statehood",
  },
  "county-mission-founding": {
    people: ["fermin-lasuen"],
    places: ["mission-santa-barbara", "santa-barbara"],
    organizations: ["franciscan-order"],
    events: ["mission-founding"],
    yearStart: 1786,
    yearEnd: 1786,
    period: "spanish-mission",
  },
  "county-mission-serra-lasuen": {
    people: ["junipero-serra", "fermin-lasuen"],
    places: ["mission-santa-barbara", "presidio-santa-barbara"],
    organizations: ["franciscan-order"],
    events: ["mission-founding", "presidio-founding"],
    yearStart: 1782,
    yearEnd: 1786,
    period: "spanish-mission",
  },
  "county-mission-church-1812": {
    places: ["mission-santa-barbara"],
    events: ["earthquake-1812"],
    yearStart: 1812,
    yearEnd: 1820,
    period: "spanish-mission",
  },
  "county-mission-chumash-labor": {
    places: ["mission-santa-barbara"],
    events: ["mission-founding"],
    yearStart: 1786,
    yearEnd: 1839,
    period: "spanish-mission",
  },
  "county-mission-contested": {
    places: ["mission-santa-barbara", "santa-barbara"],
    events: ["mission-founding"],
    yearStart: 1786,
    yearEnd: 1834,
    period: "spanish-mission",
  },
  "county-mission-secularization": {
    places: ["mission-santa-barbara"],
    organizations: ["franciscan-order"],
    events: ["secularization"],
    yearStart: 1834,
    yearEnd: 1846,
    period: "mexican-period",
  },
  "county-mission-returned-1865": {
    places: ["mission-santa-barbara"],
    organizations: ["catholic-church", "franciscan-order"],
    events: ["mission-returned-1865"],
    yearStart: 1865,
    yearEnd: 1865,
    period: "early-statehood",
  },
  "county-presidio-1782": {
    places: ["presidio-santa-barbara", "santa-barbara", "channel-islands"],
    events: ["presidio-founding"],
    yearStart: 1782,
    yearEnd: 1782,
    period: "spanish-mission",
  },
  "county-town-growth": {
    places: ["santa-barbara", "presidio-santa-barbara", "mission-santa-barbara"],
    yearStart: 1782,
    yearEnd: 1885,
  },
  "county-chumash-homeland": {
    places: ["santa-barbara", "channel-islands", "san-luis-obispo"],
    period: "pre-contact",
  },
  "county-chumash-villages": {
    places: ["santa-barbara", "channel-islands"],
    period: "pre-contact",
  },
  "county-chumash-tomol": {
    places: ["channel-islands", "santa-barbara"],
    period: "pre-contact",
  },
  "county-chumash-acorn": {
    places: ["santa-barbara"],
    period: "pre-contact",
  },
  "county-chumash-rock-art": {
    places: ["painted-cave", "santa-barbara", "ventura"],
    period: "pre-contact",
  },
  "county-chumash-mason-caution": {
    people: ["jesse-d-mason"],
    places: ["santa-barbara"],
    events: ["county-history-1883"],
    yearStart: 1883,
    yearEnd: 1883,
  },
  "county-ranchos-grants": {
    places: ["santa-barbara"],
    events: ["secularization"],
    yearStart: 1830,
    yearEnd: 1849,
    period: "mexican-period",
  },
  "county-ranchos-drought": {
    places: ["santa-barbara", "california"],
    events: ["droughts-1860s"],
    yearStart: 1862,
    yearEnd: 1864,
    period: "early-statehood",
  },
  "county-ranchos-american-title": {
    places: ["santa-barbara", "california"],
    events: ["treaty-guadalupe-hidalgo"],
    yearStart: 1848,
    yearEnd: 1869,
    period: "early-statehood",
  },
  "county-american-conquest": {
    places: ["santa-barbara", "california"],
    events: ["mexican-american-war", "california-statehood"],
    yearStart: 1846,
    yearEnd: 1850,
    period: "early-statehood",
  },
  "county-american-settlement": {
    people: ["jesse-d-mason"],
    places: ["santa-barbara"],
    events: ["county-history-1883"],
    yearStart: 1850,
    yearEnd: 1885,
    period: "early-statehood",
  },
  "county-channel-coast": {
    places: ["santa-barbara", "channel-islands"],
    yearStart: 1782,
    yearEnd: 1885,
  },
  "county-mission-nickname": {
    places: ["mission-santa-barbara", "santa-barbara"],
    organizations: ["franciscan-order"],
    events: ["mission-founding"],
    yearStart: 1786,
    yearEnd: 1885,
    period: "spanish-mission",
  },
  "county-illustrations": {
    people: ["jesse-d-mason"],
    organizations: ["thompson-west"],
    events: ["county-history-1883"],
    yearStart: 1883,
    yearEnd: 1883,
    period: "county-historian-years",
  },
};
