import type { SourceChunk } from "@/lib/types";

/**
 * SERVER-ONLY source pack for Mark Twain — Lake Tahoe / Roughing It focus.
 */

const WIKI_TWAIN = "https://en.wikipedia.org/wiki/Mark_Twain";
const WIKI_ROUGHING = "https://en.wikipedia.org/wiki/Roughing_It";
const WIKI_TAHOE = "https://en.wikipedia.org/wiki/Lake_Tahoe";
const GUTENBERG_RI =
  "https://www.gutenberg.org/ebooks/3177";

export const twainSources: SourceChunk[] = [
  // ---------------- Biography (brief) ----------------
  {
    id: "bio-birth",
    text: "Samuel Langhorne Clemens was born November 30, 1835, in Florida, Missouri, and grew up in Hannibal. He later became famous under the pen name Mark Twain.",
    topics: ["biography", "who are you", "yourself", "identity", "missouri"],
    dateRange: "1835",
    sourceType: "biographical",
    citation: "Wikipedia: Mark Twain.",
    url: WIKI_TWAIN,
    reliability: "high",
  },
  {
    id: "bio-pen-name",
    text: "Clemens began using the pen name Mark Twain in 1863 while writing for Nevada and California newspapers. By 1905 he was world-famous as a humorist, novelist, and lecturer.",
    topics: ["biography", "mark twain", "pen name", "who are you", "yourself"],
    dateRange: "1863-1905",
    sourceType: "biographical",
    citation: "Wikipedia: Mark Twain.",
    url: WIKI_TWAIN,
    reliability: "high",
  },
  {
    id: "bio-nevada-1861",
    text: "In 1861 Samuel Clemens went west to Nevada Territory with his brother Orion Clemens, who had been appointed secretary to the territorial governor. Sam expected possible clerical work; pay for an assistant was lacking, and he looked for other schemes — including timber.",
    topics: ["biography", "nevada", "orion", "1861", "who are you", "territory"],
    dateRange: "1861",
    sourceType: "biographical",
    citation:
      "Wikipedia: Mark Twain; Twain letters and Roughing It background; Tahoe Daily Tribune historical feature.",
    url: WIKI_TWAIN,
    reliability: "high",
  },
  {
    id: "bio-death-note",
    text: "Mark Twain died April 21, 1910. In this ECHOES simulation he speaks from 1905 and must not narrate his own death as a lived completed event.",
    topics: ["biography", "legacy", "1910"],
    dateRange: "1910",
    sourceType: "persona-note",
    citation: "Wikipedia: Mark Twain; ECHOES temporal guardrail (speaking year 1905).",
    url: WIKI_TWAIN,
    reliability: "high",
  },
  {
    id: "bio-elderly-1905",
    text: "By 1905 Twain was an elderly, internationally known author and lecturer, looking back across decades to the Nevada Territory of his youth when recounting Lake Tahoe.",
    topics: ["biography", "1905", "who are you", "yourself", "appearance"],
    dateRange: "1905",
    sourceType: "biographical",
    citation: "Wikipedia: Mark Twain.",
    url: WIKI_TWAIN,
    reliability: "high",
  },

  // ---------------- Tahoe 1861 ----------------
  {
    id: "tahoe-hike-kinney",
    text: "In September 1861, Clemens hiked from the Carson City area to Lake Tahoe (then often called Lake Bigler) with acquaintance John Kinney (John D. Kinney) to explore the lake and stake a timber claim.",
    topics: ["lake tahoe", "john kinney", "1861", "timber", "hike", "bigler"],
    dateRange: "September 1861",
    sourceType: "primary",
    citation:
      "Mark Twain, Roughing It (1872), ch. XXII–XXIII; Mark Twain Project letter notes; Antonucci, Mark Twain's Route to Lake Tahoe.",
    url: WIKI_ROUGHING,
    reliability: "high",
  },
  {
    id: "tahoe-name-bigler",
    text: "In Twain's Nevada years the lake was commonly called Lake Bigler (after California governor John Bigler); the name Tahoe — from a Washoe word — later prevailed. Twain's published accounts use the lake's beauty more than consistent naming politics.",
    topics: ["lake tahoe", "bigler", "name", "washoe"],
    dateRange: "1861-1872",
    sourceType: "reference",
    citation: "Wikipedia: Lake Tahoe; period Nevada usage in Twain scholarship.",
    url: WIKI_TAHOE,
    reliability: "high",
  },
  {
    id: "tahoe-timber-claim",
    text: "Clemens and Kinney claimed roughly three hundred acres of yellow-pine timberland near the shore, posting notices on a tree, hoping to profit from mining-country demand for lumber and cordwood.",
    topics: ["timber", "claim", "300 acres", "pine", "lake tahoe", "1861"],
    dateRange: "1861",
    sourceType: "primary",
    citation: "Mark Twain, Roughing It (1872), Tahoe chapters.",
    url: GUTENBERG_RI,
    reliability: "high",
  },
  {
    id: "tahoe-brush-shelter",
    text: "To hold the claim they built a brush shelter or lean-to 'house' and began fencing by felling trees to fall as a rough enclosure. After cutting three trees apiece they quit, joking that six trees would have to 'hold' the property.",
    topics: ["brush shelter", "cabin", "fence", "timber claim", "kinney"],
    dateRange: "1861",
    sourceType: "primary",
    citation: "Mark Twain, Roughing It (1872).",
    url: GUTENBERG_RI,
    reliability: "high",
  },
  {
    id: "tahoe-no-cabin-myth",
    text: "Twain describes a temporary brush shelter, not a lasting framed cabin. Later tourist lore sometimes invents an exact cabin still standing; that is not supported as a firsthand Twain fact and should not be asserted.",
    topics: ["cabin", "brush shelter", "myth", "contested", "lake tahoe"],
    dateRange: "1861 / later lore",
    sourceType: "persona-note",
    citation:
      "Roughing It text (brush house); ECHOES accuracy note against surviving-cabin myths.",
    url: GUTENBERG_RI,
    reliability: "high",
  },
  {
    id: "tahoe-wildfire",
    text: "While cooking supper, Clemens lit a fire, went back to the boat for the frying-pan, and the fire escaped into dry needles and brush. Kinney shouted; within minutes the fire destroyed their shelter, provisions, and much of the timber they had hoped to claim. They watched from the water.",
    topics: ["wildfire", "fire", "campfire", "timber claim", "lake tahoe", "1861"],
    dateRange: "1861",
    sourceType: "primary",
    citation: "Mark Twain, Roughing It (1872); retold in Tahoe historical features.",
    url: GUTENBERG_RI,
    reliability: "high",
  },
  {
    id: "tahoe-claim-abandoned",
    text: "After the fire, the timber-baron scheme ended. They never sold logs and, in the usual telling, never perfected the claim at a recorder's office; Clemens and Kinney returned toward Carson City.",
    topics: ["timber claim", "abandoned", "carson city", "1861"],
    dateRange: "1861",
    sourceType: "secondary",
    citation:
      "Roughing It; secondary summaries (e.g. Cassinelli / Tahoe press features).",
    url: GUTENBERG_RI,
    reliability: "medium",
  },
  {
    id: "tahoe-fairest-picture",
    text: "Twain's famous first sight of the lake in Roughing It includes the line that as it lay with mountain shadows on its still surface he thought it 'must surely be the fairest picture the whole earth affords.'",
    topics: ["lake tahoe", "description", "fairest picture", "roughing it", "quote"],
    dateRange: "1861 / published 1872",
    sourceType: "primary",
    citation: "Mark Twain, Roughing It (1872), Lake Tahoe chapter.",
    url: GUTENBERG_RI,
    reliability: "high",
  },
  {
    id: "tahoe-water-clarity",
    text: "Roughing It praises Tahoe's clarity and color — Twain's comic-scientific asides about seeing crags far under the surface and the lake's intense blues and greens — literary description rather than modern limnology.",
    topics: ["lake tahoe", "water", "clarity", "description", "roughing it"],
    dateRange: "1872",
    sourceType: "primary",
    citation: "Mark Twain, Roughing It (1872).",
    url: GUTENBERG_RI,
    reliability: "high",
  },
  {
    id: "tahoe-location-contested",
    text: "Later researchers disagree about the exact 1861 campsite and timber-claim shore location. Arguments have pointed toward north-shore / Agate Bay–Tahoe Vista areas versus other northeast or east-shore readings of Twain's composite itinerary. The question remains contested.",
    topics: ["campsite", "location", "contested", "north shore", "east shore", "agate bay"],
    dateRange: "1861 / modern scholarship",
    sourceType: "secondary",
    citation:
      "David C. Antonucci, Mark Twain's Route to Lake Tahoe (Nevada Historical Society Quarterly); Schmidt and related NHSQ debates.",
    reliability: "medium",
  },
  {
    id: "tahoe-composite-memory",
    text: "Roughing It's Tahoe chapters, written about a decade later, compress and embellish two timber-scouting visits and letter memories — characteristic Twain hyperbole. Treat vivid comic detail as literature grounded in real visits, not a surveyor's log.",
    topics: ["roughing it", "memory", "contested", "letters", "1861"],
    dateRange: "1861-1872",
    sourceType: "secondary",
    citation: "Antonucci, Mark Twain's Route to Lake Tahoe; Mark Twain Project notes.",
    reliability: "medium",
  },

  // ---------------- Roughing It ----------------
  {
    id: "books-roughing-it",
    text: "Roughing It, published in 1872, is Twain's semi-autobiographical travel book about the West — overland stage, Nevada Territory, mining, and California — including the Lake Tahoe timber-claim episode in chapters commonly numbered XXII–XXIII.",
    topics: ["roughing it", "books", "1872", "nevada", "who are you"],
    dateRange: "1872",
    sourceType: "reference",
    citation: "Wikipedia: Roughing It; Project Gutenberg text.",
    url: WIKI_ROUGHING,
    reliability: "high",
  },
  {
    id: "books-letters-mother",
    text: "Clemens also wrote home about Tahoe in letters to his family in 1861; scholars use those letters alongside Roughing It to reconstruct timing and route, noting differences between letter report and later comic memoir.",
    topics: ["letters", "1861", "family", "sources", "lake tahoe"],
    dateRange: "1861",
    sourceType: "primary",
    citation:
      "Mark Twain's Letters (Mark Twain Project); cited in Antonucci and MTP notes.",
    reliability: "high",
  },

  // ---------------- Place context ----------------
  {
    id: "tahoe-geography",
    text: "Lake Tahoe is a large alpine lake in the Sierra Nevada on the California–Nevada border, renowned for depth, clarity, and mountain setting. In 1861 it lay near routes serving the Comstock mining boom.",
    topics: ["lake tahoe", "sierra", "nevada", "california", "geography"],
    dateRange: "geological / 1861",
    sourceType: "reference",
    citation: "Wikipedia: Lake Tahoe.",
    url: WIKI_TAHOE,
    reliability: "high",
  },
  {
    id: "tahoe-washoe",
    text: "The Washoe (Washo) people are the Indigenous people of the Lake Tahoe basin. Period photographs and ethnography document Washoe presence; Twain's comic memoir centers his own misadventures more than Washoe history, which should be treated respectfully from separate sources.",
    topics: ["washoe", "washo", "native", "indigenous", "lake tahoe"],
    dateRange: "pre-contact–1860s",
    sourceType: "reference",
    citation: "Wikipedia: Washoe people; historic Lake Tahoe context.",
    url: "https://en.wikipedia.org/wiki/Washoe_people",
    reliability: "high",
  },
  {
    id: "tahoe-comstock-timber",
    text: "The Comstock Lode mining boom around Virginia City created huge demand for timber and cordwood, which is why a young Clemens imagined a fortune in Tahoe pines — a scheme the wildfire abruptly ended.",
    topics: ["comstock", "timber", "virginia city", "mining", "1861"],
    dateRange: "1860s",
    sourceType: "reference",
    citation: "Nevada mining / Tahoe timber history; Roughing It context.",
    url: "https://en.wikipedia.org/wiki/Comstock_Lode",
    reliability: "high",
  },
  {
    id: "tahoe-carson-distance",
    text: "Twain portrays the tramp from Carson toward the lake as a hard hike of roughly a dozen miles into high country — accounts vary slightly on miles and exact road; the point is a foot journey into timber, not a resort carriage ride.",
    topics: ["carson city", "hike", "distance", "1861", "lake tahoe"],
    dateRange: "1861",
    sourceType: "secondary",
    citation: "Roughing It; Antonucci route estimates (~11–12 miles discussions).",
    reliability: "medium",
  },
  {
    id: "tahoe-irish-brigade",
    text: "In Roughing It, Twain jokes about raiding provisions from a neighboring camp he calls the 'Irish Brigade' and later settling damages — comic memoir detail tied to the claim episode, not a sober quartermaster's report.",
    topics: ["irish brigade", "provisions", "roughing it", "comic"],
    dateRange: "1861 / 1872",
    sourceType: "primary",
    citation: "Mark Twain, Roughing It (1872).",
    url: GUTENBERG_RI,
    reliability: "medium",
  },
  {
    id: "tahoe-steamer-era",
    text: "Later nineteenth-century Tahoe saw hotels, cottages, and steamers (such as the steamer Tahoe) serving tourists and locals — a busier lake than the 'uninhabited wilderness' sometimes implied in comic memoir. Twain's 1861 visits caught an earlier moment on the brink of heavier use.",
    topics: ["steamer", "tourism", "tallac", "lake tahoe", "nineteenth century"],
    dateRange: "1870s-1905",
    sourceType: "reference",
    citation:
      "Historic Tahoe steamer and Tallac photography; Antonucci on 1861 context vs later traffic.",
    reliability: "medium",
  },
  {
    id: "bio-orion-secretary",
    text: "Orion Clemens served as secretary of Nevada Territory under Territorial Governor James W. Nye — the appointment that brought Sam west in 1861.",
    topics: ["orion", "nevada territory", "nye", "biography", "1861"],
    dateRange: "1861",
    sourceType: "biographical",
    citation: "Wikipedia: Orion Clemens; Mark Twain biography.",
    url: "https://en.wikipedia.org/wiki/Orion_Clemens",
    reliability: "high",
  },
  {
    id: "books-other-brief",
    text: "Besides Roughing It, Twain's major books by 1905 included The Adventures of Tom Sawyer, Adventures of Huckleberry Finn, and The Innocents Abroad. In this conversation those titles are background; Tahoe remains the focus.",
    topics: ["books", "tom sawyer", "huckleberry finn", "biography"],
    dateRange: "1869-1905",
    sourceType: "reference",
    citation: "Wikipedia: Mark Twain.",
    url: WIKI_TWAIN,
    reliability: "high",
  },
  {
    id: "tahoe-second-visit",
    text: "Scholarship often treats Twain's Tahoe experience as more than one short visit — timber scouting across several days or trips — later fused in Roughing It. Exact day-by-day reconstruction remains partly contested.",
    topics: ["visits", "contested", "1861", "roughing it", "chronology"],
    dateRange: "1861",
    sourceType: "secondary",
    citation: "Antonucci; Mark Twain Project chronology notes.",
    reliability: "medium",
  },
  {
    id: "tahoe-yellow-pine",
    text: "Twain describes dense yellow-pine forest — trees roughly a hundred feet high and one to five feet through at the butt — as the timber they meant to claim before the fire.",
    topics: ["pine", "forest", "timber", "description", "roughing it"],
    dateRange: "1861 / 1872",
    sourceType: "primary",
    citation: "Mark Twain, Roughing It (1872).",
    url: GUTENBERG_RI,
    reliability: "high",
  },
];
