import type {
  PersonaSemanticVocab,
  SourceSemanticAnnotations,
} from "@/lib/semantic";

/** Controlled vocabulary for August Hemme. */
export const hemmeVocab: PersonaSemanticVocab = {
  people: [
    {
      id: "august-hemme",
      label: "August Hemme",
      aliases: ["august hemme", "a. hemme", "a hemme"],
    },
    {
      id: "minerva-ish-hemme",
      label: "Minerva Elizabeth Ish",
      aliases: ["minerva ish", "minerva hemme", "minerva elizabeth ish"],
    },
    {
      id: "charles-riehn",
      label: "Charles Reihn",
      aliases: ["charles riehn", "charles reihn"],
    },
    {
      id: "ro-baldwin",
      label: "R. O. Baldwin",
      aliases: ["r.o. baldwin", "r. o. baldwin"],
    },
    {
      id: "ja-shuey",
      label: "J. A. Shuey",
      aliases: ["j.a. shuey", "j. a. shuey"],
    },
    {
      id: "james-m-stow",
      label: "James M. Stow",
      aliases: ["james m. stow", "james stow"],
    },
    {
      id: "albert-glass",
      label: "Albert Glass",
      aliases: ["albert glass"],
    },
    {
      id: "charles-wood",
      label: "Charles Wood",
      aliases: ["wood of sycamore"],
    },
    {
      id: "george-mccamley",
      label: "George McCamley",
      aliases: ["george mccamley"],
    },
    {
      id: "john-hartz",
      label: "John Hartz",
      aliases: ["john hartz"],
    },
    {
      id: "jp-munro-fraser",
      label: "J. P. Munro-Fraser",
      aliases: ["munro-fraser", "munro fraser"],
    },
  ],
  places: [
    {
      id: "prussia",
      label: "Prussia",
      aliases: ["hanover", "germany"],
    },
    {
      id: "new-york",
      label: "New York",
      aliases: ["new york city"],
    },
    {
      id: "santa-clara-valley",
      label: "Santa Clara Valley",
      aliases: ["santa clara"],
    },
    {
      id: "san-ramon-valley",
      label: "San Ramon Valley",
      aliases: ["san ramon valley"],
    },
    {
      id: "alamo",
      label: "Alamo",
      aliases: ["alamo village", "hemme avenue"],
    },
    {
      id: "danville",
      label: "Danville",
      aliases: [],
    },
    {
      id: "san-ramon",
      label: "San Ramon",
      aliases: [],
    },
    {
      id: "walnut-creek",
      label: "Walnut Creek",
      aliases: [],
    },
    {
      id: "concord",
      label: "Concord",
      aliases: [],
    },
    {
      id: "martinez",
      label: "Martinez",
      aliases: ["avon"],
    },
    {
      id: "san-francisco",
      label: "San Francisco",
      aliases: [],
    },
    {
      id: "berkeley",
      label: "Berkeley",
      aliases: ["college avenue"],
    },
    {
      id: "contra-costa",
      label: "Contra Costa County",
      aliases: ["contra costa"],
    },
    {
      id: "hemme-station",
      label: "Hemme Station",
      aliases: ["alamo station", "hemme depot"],
    },
    {
      id: "sycamore-valley",
      label: "Sycamore Valley",
      aliases: ["sycamore"],
    },
    {
      id: "pleasanton",
      label: "Pleasanton",
      aliases: ["radum"],
    },
    {
      id: "danville-depot",
      label: "Danville depot",
      aliases: ["danville station", "main street depot"],
    },
  ],
  organizations: [
    {
      id: "southern-pacific",
      label: "Southern Pacific",
      aliases: ["sp", "southern pacific railroad", "s.p."],
    },
    {
      id: "riehn-hemme-co",
      label: "Riehn, Hemme & Co.",
      aliases: ["riehn hemme", "assay firm", "gold assay"],
    },
    {
      id: "san-ramon-branch-line",
      label: "San Ramon Branch Line",
      aliases: ["branch line", "san ramon branch", "valley railroad"],
    },
    {
      id: "contra-costa-gazette",
      label: "Contra Costa Gazette",
      aliases: ["gazette"],
    },
    {
      id: "hanover-military-academy",
      label: "Hanover Military Academy",
      aliases: ["hanover academy"],
    },
    {
      id: "iron-horse-trail",
      label: "Iron Horse Regional Trail",
      aliases: ["iron horse trail", "iron horse"],
    },
  ],
  events: [
    {
      id: "gold-rush",
      label: "Gold Rush",
      aliases: ["california gold rush", "forty-niners", "1849"],
    },
    {
      id: "comstock-era",
      label: "Comstock-era assay wealth",
      aliases: ["comstock", "bullion", "assay business"],
    },
    {
      id: "branch-line-right-of-way",
      label: "Branch-line right-of-way campaign",
      aliases: [
        "right-of-way",
        "1890 railroad fight",
        "deed the land",
        "fifteen thousand",
        "15,000",
        "holdouts",
        "holdout",
      ],
    },
    {
      id: "first-train-1891",
      label: "First San Ramon Branch train 1891",
      aliases: ["june 7 1891", "first excursion", "first passenger trip"],
    },
    {
      id: "panic-1893-bankruptcy",
      label: "1890s hardship and bankruptcy",
      aliases: ["1893 crash", "bankruptcy 1898", "loan defaults"],
    },
    {
      id: "1909-extension",
      label: "1909 Pleasanton extension",
      aliases: ["1909 extension", "radum extension"],
    },
    {
      id: "line-abandonment",
      label: "Branch-line abandonment",
      aliases: ["1934 passenger end", "1978 abandonment"],
    },
  ],
  periods: [
    {
      id: "emigration-gold-rush",
      label: "Emigration and Gold Rush",
      yearStart: 1833,
      yearEnd: 1851,
      aliases: ["early years", "to california"],
    },
    {
      id: "ranch-building",
      label: "Ranch-building years",
      yearStart: 1852,
      yearEnd: 1862,
      aliases: ["alamo ranch", "early valley years"],
    },
    {
      id: "sf-assay-wealth",
      label: "San Francisco assay wealth",
      yearStart: 1863,
      yearEnd: 1889,
      aliases: ["assay years", "philanthropy years", "return to ranch"],
    },
    {
      id: "railroad-era",
      label: "Railroad era",
      yearStart: 1890,
      yearEnd: 1900,
      aliases: ["branch line years", "speaking year 1900"],
    },
  ],
};

/** Hand tags for curated August Hemme sources. */
export const hemmeSourceAnnotations: SourceSemanticAnnotations = {
  "bio-birth": {
    people: ["august-hemme"],
    places: ["prussia"],
    organizations: ["hanover-military-academy"],
    yearStart: 1833,
    yearEnd: 1846,
    period: "emigration-gold-rush",
  },
  "bio-brother-store": {
    people: ["august-hemme"],
    places: ["new-york"],
    events: ["gold-rush"],
    yearStart: 1846,
    yearEnd: 1849,
    period: "emigration-gold-rush",
  },
  "bio-california-1849": {
    people: ["august-hemme"],
    places: ["santa-clara-valley"],
    events: ["gold-rush"],
    yearStart: 1849,
    yearEnd: 1852,
    period: "emigration-gold-rush",
  },
  "bio-ranch-1852": {
    people: ["august-hemme"],
    places: ["san-ramon-valley", "alamo"],
    yearStart: 1852,
    yearEnd: 1852,
    period: "ranch-building",
  },
  "bio-marriage": {
    people: ["august-hemme", "minerva-ish-hemme"],
    places: ["san-ramon-valley", "alamo"],
    yearStart: 1856,
    yearEnd: 1856,
    period: "ranch-building",
  },
  "bio-san-francisco-assay": {
    people: ["august-hemme", "charles-riehn"],
    places: ["san-francisco", "san-ramon-valley"],
    organizations: ["riehn-hemme-co"],
    events: ["comstock-era"],
    yearStart: 1863,
    yearEnd: 1879,
    period: "sf-assay-wealth",
  },
  "bio-philanthropy": {
    people: ["august-hemme"],
    places: ["san-francisco"],
    yearStart: 1860,
    yearEnd: 1879,
    period: "sf-assay-wealth",
  },
  "bio-return-ranch": {
    people: ["august-hemme", "jp-munro-fraser"],
    places: ["san-ramon-valley", "alamo", "contra-costa"],
    yearStart: 1870,
    yearEnd: 1889,
    period: "sf-assay-wealth",
  },
  "bio-hardship-1890s": {
    people: ["august-hemme", "minerva-ish-hemme"],
    places: ["berkeley", "san-ramon-valley"],
    events: ["panic-1893-bankruptcy"],
    yearStart: 1892,
    yearEnd: 1898,
    period: "railroad-era",
  },
  "bio-death-editor-note": {
    people: ["august-hemme"],
    places: ["berkeley"],
    yearStart: 1904,
    yearEnd: 1904,
  },
  "bio-land-gifts": {
    people: ["august-hemme"],
    places: ["alamo", "san-ramon-valley"],
    yearStart: 1850,
    yearEnd: 1899,
    period: "ranch-building",
  },
  "rail-sp-condition": {
    people: ["august-hemme"],
    places: ["san-ramon-valley"],
    organizations: ["southern-pacific", "san-ramon-branch-line"],
    events: ["branch-line-right-of-way"],
    yearStart: 1890,
    yearEnd: 1890,
    period: "railroad-era",
  },
  "rail-committee": {
    people: [
      "august-hemme",
      "ro-baldwin",
      "ja-shuey",
      "james-m-stow",
      "albert-glass",
    ],
    places: ["danville", "alamo", "walnut-creek", "san-ramon"],
    organizations: ["southern-pacific", "san-ramon-branch-line"],
    events: ["branch-line-right-of-way"],
    yearStart: 1890,
    yearEnd: 1890,
    period: "railroad-era",
  },
  "rail-fifteen-thousand": {
    people: ["charles-wood", "george-mccamley", "august-hemme"],
    places: ["sycamore-valley", "san-ramon", "san-ramon-valley"],
    organizations: ["san-ramon-branch-line"],
    events: ["branch-line-right-of-way"],
    yearStart: 1890,
    yearEnd: 1890,
    period: "railroad-era",
  },
  "rail-first-excursion": {
    people: ["august-hemme"],
    places: ["hemme-station", "danville", "san-ramon", "san-ramon-valley"],
    organizations: ["san-ramon-branch-line", "contra-costa-gazette"],
    events: ["first-train-1891"],
    yearStart: 1891,
    yearEnd: 1891,
    period: "railroad-era",
  },
  "rail-route-1891": {
    places: ["san-ramon", "martinez", "san-ramon-valley"],
    organizations: ["southern-pacific", "san-ramon-branch-line"],
    events: ["first-train-1891"],
    yearStart: 1891,
    yearEnd: 1891,
    period: "railroad-era",
  },
  "rail-1909-after-death": {
    people: ["august-hemme"],
    places: ["pleasanton"],
    organizations: ["southern-pacific", "san-ramon-branch-line"],
    events: ["1909-extension"],
    yearStart: 1909,
    yearEnd: 1909,
  },
  "rail-hemme-station": {
    people: ["august-hemme"],
    places: ["hemme-station", "alamo"],
    organizations: ["san-ramon-branch-line"],
    yearStart: 1891,
    yearEnd: 1891,
    period: "railroad-era",
  },
  "rail-danville-growth": {
    places: ["danville", "danville-depot"],
    organizations: ["southern-pacific", "san-ramon-branch-line"],
    events: ["first-train-1891"],
    yearStart: 1891,
    yearEnd: 1900,
    period: "railroad-era",
  },
  "rail-danville-depot-built": {
    people: ["john-hartz"],
    places: ["danville", "danville-depot", "concord", "walnut-creek", "san-ramon"],
    organizations: ["southern-pacific", "san-ramon-branch-line"],
    yearStart: 1891,
    yearEnd: 1891,
    period: "railroad-era",
  },
  "rail-freight-produce": {
    places: ["san-ramon-valley", "martinez"],
    organizations: ["san-ramon-branch-line"],
    yearStart: 1891,
    yearEnd: 1900,
    period: "railroad-era",
  },
  "rail-iron-horse-modern": {
    people: ["august-hemme"],
    places: ["san-ramon-valley"],
    organizations: ["southern-pacific", "iron-horse-trail", "san-ramon-branch-line"],
    yearStart: 1970,
    yearEnd: 2020,
  },
  "rail-abandonment-note": {
    organizations: ["southern-pacific", "san-ramon-branch-line"],
    events: ["line-abandonment"],
    yearStart: 1934,
    yearEnd: 1978,
  },
  "valley-agriculture": {
    places: [
      "san-ramon-valley",
      "concord",
      "alamo",
      "danville",
      "san-ramon",
    ],
    organizations: ["san-ramon-branch-line"],
    yearStart: 1850,
    yearEnd: 1900,
    period: "railroad-era",
  },
  "valley-alamo": {
    people: ["august-hemme"],
    places: ["alamo", "hemme-station"],
    yearStart: 1850,
    yearEnd: 1900,
    period: "ranch-building",
  },
  "valley-danville-hartz": {
    people: ["john-hartz"],
    places: ["danville", "danville-depot"],
    organizations: ["southern-pacific"],
    yearStart: 1891,
    yearEnd: 1891,
    period: "railroad-era",
  },
  "valley-san-ramon-depot-distance": {
    places: ["san-ramon"],
    organizations: ["san-ramon-branch-line", "contra-costa-gazette"],
    yearStart: 1891,
    yearEnd: 1897,
    period: "railroad-era",
  },
  "rail-depots-four": {
    people: ["august-hemme"],
    places: ["concord", "walnut-creek", "danville", "san-ramon"],
    organizations: ["southern-pacific", "san-ramon-branch-line"],
    yearStart: 1891,
    yearEnd: 1891,
    period: "railroad-era",
  },
  "bio-identity-summary": {
    people: ["august-hemme", "minerva-ish-hemme"],
    places: [
      "prussia",
      "san-ramon-valley",
      "alamo",
      "san-francisco",
      "hemme-station",
    ],
    organizations: ["san-ramon-branch-line"],
    events: ["gold-rush", "branch-line-right-of-way", "first-train-1891"],
    yearStart: 1833,
    yearEnd: 1900,
    period: "railroad-era",
  },
  "valley-contra-costa": {
    places: [
      "contra-costa",
      "san-ramon-valley",
      "alamo",
      "danville",
      "san-ramon",
      "martinez",
    ],
    organizations: ["san-ramon-branch-line"],
    yearStart: 1891,
    yearEnd: 1900,
    period: "railroad-era",
  },
};
