import type { SourceChunk } from "@/lib/types";

/**
 * SERVER-ONLY source pack for August Hemme (San Ramon Valley / branch line).
 *
 * Verified against Museum of the San Ramon Valley, East Bay Times (Nilda Rego),
 * San Francisco Call obituary (Nov. 2, 1904 — for editors; persona speaks 1900),
 * City/museum branch-line histories.
 */

const MSRV_HEMME = "https://museumsrv.org/hemme-srbl/";
const MSRV_TRAIL = "https://museumsrv.org/history-of-the-iron-horse-trail/";
const EBT =
  "https://www.eastbaytimes.com/2013/05/26/days-gone-by-hemme-avenue-honors-a-prussian-who-bought-3000-acres-in-san-ramon-valley/";
const SF_CALL_OBIT =
  "http://files.usgwarchives.net/ca/alameda/obits/h/hemme4009gob.txt";
const WIKI_DANVILLE_DEPOT =
  "https://en.wikipedia.org/wiki/Danville_station_(California)";
const WIKI_IRON_HORSE =
  "https://en.wikipedia.org/wiki/Iron_Horse_Regional_Trail";

export const hemmeSources: SourceChunk[] = [
  // ---------------- Biography ----------------
  {
    id: "bio-birth",
    text: "August Hemme was born January 10, 1833, in Prussia. He came to the United States in 1846 at about age thirteen after failing to enter the Hanover Military Academy.",
    topics: ["biography", "prussia", "1846", "who are you", "yourself", "identity"],
    dateRange: "1833-1846",
    sourceType: "biographical",
    citation:
      "East Bay Times, Nilda Rego, 'Hemme Avenue honors a Prussian…' (May 26, 2013); SF Call obituary notes.",
    url: EBT,
    reliability: "high",
  },
  {
    id: "bio-brother-store",
    text: "Hemme's older brother had preceded him to New York and kept a store; August worked in that store for about three years before California gold news drew him west.",
    topics: ["biography", "early life", "new york", "gold rush"],
    dateRange: "1846-1849",
    sourceType: "biographical",
    citation: "East Bay Times, Rego (2013).",
    url: EBT,
    reliability: "medium",
  },
  {
    id: "bio-california-1849",
    text: "Still a teenager, Hemme came to California in 1849 during the Gold Rush. Mining proved harder than expected; he made more money buying cattle in the Santa Clara Valley and driving them to the mining country to sell.",
    topics: ["biography", "gold rush", "1849", "cattle", "who are you", "yourself"],
    dateRange: "1849-1852",
    sourceType: "biographical",
    citation: "East Bay Times, Rego (2013); SF Call called him a pioneer of '49.",
    url: EBT,
    reliability: "high",
  },
  {
    id: "bio-ranch-1852",
    text: "By about 1852 Hemme bought roughly 3,000 acres in the San Ramon Valley (Alamo area), while still under twenty — the ranch that made him a major valley landholder.",
    topics: ["biography", "ranch", "alamo", "san ramon valley", "3000 acres", "who are you"],
    dateRange: "1852",
    sourceType: "biographical",
    citation: "East Bay Times, Rego (2013); Museum of the San Ramon Valley materials.",
    url: EBT,
    reliability: "high",
  },
  {
    id: "bio-marriage",
    text: "In 1856 Hemme married neighbor Minerva Elizabeth Ish. The couple worked the farm and prospered in the following years.",
    topics: ["biography", "marriage", "minerva", "ish", "family"],
    dateRange: "1856",
    sourceType: "biographical",
    citation: "East Bay Times, Rego (2013); SF Call / genealogical notes.",
    url: EBT,
    reliability: "high",
  },
  {
    id: "bio-san-francisco-assay",
    text: "Hemme sold the San Ramon Valley ranch in 1863 and entered business in San Francisco with Charles Reihn (Riehn, Hemme & Co.), a prominent gold-assaying and bullion firm during Comstock-era excitement. Period accounts rate him very wealthy in those years.",
    topics: ["biography", "san francisco", "assay", "riehn", "comstock"],
    dateRange: "1863-1870s",
    sourceType: "biographical",
    citation: "East Bay Times, Rego (2013); Riehn, Hemme & Co. historical notes.",
    url: EBT,
    reliability: "medium",
  },
  {
    id: "bio-philanthropy",
    text: "Hemme was known for large church gifts in San Francisco — accounts mention contributions on the order of $100,000–$150,000 toward tabernacle / Presbyterian church building and related causes.",
    topics: ["biography", "philanthropy", "church", "san francisco"],
    dateRange: "1860s-1870s",
    sourceType: "biographical",
    citation: "East Bay Times, Rego (2013); San Francisco Call obituary (1904).",
    url: EBT,
    reliability: "medium",
  },
  {
    id: "bio-return-ranch",
    text: "After retiring from the gold/assay business, Hemme returned to the San Ramon Valley and bought back his old ranch home — praised in Munro-Fraser's 1882 History of Contra Costa County as a gem of architectural beauty amid verdure.",
    topics: ["biography", "ranch", "alamo", "1882", "contra costa"],
    dateRange: "1870s-1880s",
    sourceType: "biographical",
    citation:
      "East Bay Times, Rego (2013), quoting J.P. Munro-Fraser, History of Contra Costa County (1882).",
    url: EBT,
    reliability: "high",
  },
  {
    id: "bio-hardship-1890s",
    text: "From about 1892 Hemme faced loan defaults amid hard times for farmers; after the 1893 crash and suits by creditors, he declared bankruptcy in 1898. He and Minerva moved to Berkeley to live with their children.",
    topics: ["biography", "bankruptcy", "1898", "berkeley", "hardship"],
    dateRange: "1892-1898",
    sourceType: "biographical",
    citation: "East Bay Times, Rego (2013).",
    url: EBT,
    reliability: "high",
  },
  {
    id: "bio-death-editor-note",
    text: "August Hemme died suddenly of heart failure on October 31, 1904, at his home at 2216 College Avenue, Berkeley, age 71. The San Francisco Call published an obituary November 2, 1904. ECHOES speaking year is 1900 — the persona must not narrate this death as firsthand memory.",
    topics: ["biography", "death", "1904", "berkeley", "obituary"],
    dateRange: "1904",
    sourceType: "persona-note",
    citation:
      "San Francisco Call, Nov. 2, 1904, p. 4 (USGenWeb transcript); ECHOES temporalYear 1900.",
    url: SF_CALL_OBIT,
    reliability: "high",
  },
  {
    id: "bio-land-gifts",
    text: "Local memory credits Hemme with donating land for the community's church and its first school in the Alamo / valley area — part of why Hemme Avenue still commemorates his name.",
    topics: ["biography", "school", "church", "hemme avenue", "alamo", "legacy"],
    dateRange: "1850s-1890s",
    sourceType: "secondary",
    citation: "East Bay Times, Rego (2013).",
    url: EBT,
    reliability: "medium",
  },

  // ---------------- Railroad ----------------
  {
    id: "rail-sp-condition",
    text: "Southern Pacific agreed to build the San Ramon Branch Line if the right-of-way was deeded to the company. Local leaders organized to secure that land in 1890.",
    topics: ["railroad", "southern pacific", "right-of-way", "1890", "branch line"],
    dateRange: "1890",
    sourceType: "secondary",
    citation: "Museum of the San Ramon Valley, Beverly Lane, Hemme & San Ramon Branch Line.",
    url: MSRV_HEMME,
    reliability: "high",
  },
  {
    id: "rail-committee",
    text: "A committee including R. O. Baldwin and J. A. Shuey of Danville, James M. Stow of Walnut Creek, August Hemme of Alamo, and Albert Glass of San Ramon contacted landowners along the proposed right-of-way in 1890. Hemme led the successful local effort.",
    topics: ["railroad", "committee", "hemme", "danville", "alamo", "1890"],
    dateRange: "1890",
    sourceType: "secondary",
    citation: "Museum of the San Ramon Valley, Lane, Hemme & San Ramon Branch Line.",
    url: MSRV_HEMME,
    reliability: "high",
  },
  {
    id: "rail-fifteen-thousand",
    text: "Charles Wood of Sycamore Valley, George McCamley of San Ramon, and others helped raise about $15,000 to pay landowners who resisted donating land for the right-of-way.",
    topics: ["railroad", "right-of-way", "15000", "fundraising", "1890"],
    dateRange: "1890",
    sourceType: "secondary",
    citation: "Museum of the San Ramon Valley, Lane; History of the Iron Horse Trail page.",
    url: MSRV_HEMME,
    reliability: "high",
  },
  {
    id: "rail-first-excursion",
    text: "The first regular passenger trip over the San Ramon Branch Line took place on June 7, 1891. The Contra Costa Gazette described the beauty of the valley as the train approached Hemme's, orchards brushing the cars, then Danville and the San Ramon terminus.",
    topics: ["railroad", "june 7 1891", "excursion", "first train", "danville", "san ramon"],
    dateRange: "1891-06-07",
    sourceType: "primary",
    citation:
      "Contra Costa Gazette account quoted by Museum of the San Ramon Valley (Lane, 2006).",
    url: MSRV_HEMME,
    reliability: "high",
  },
  {
    id: "rail-route-1891",
    text: "When opened in 1891 the branch extended about twenty miles from San Ramon to Avon (about three miles east of Martinez), connecting on the north with the Oakland/Stockton line. San Ramon was the southern terminus until a later extension Hemme would not live to see.",
    topics: ["railroad", "route", "avon", "martinez", "san ramon", "1891"],
    dateRange: "1891",
    sourceType: "secondary",
    citation: "Museum of the San Ramon Valley, Lane, Hemme & San Ramon Branch Line.",
    url: MSRV_HEMME,
    reliability: "high",
  },
  {
    id: "rail-1909-after-death",
    text: "In 1909 Southern Pacific extended the line toward Radum near Pleasanton to connect with the Oakland/Tracy line. August Hemme died in 1904 — he must not claim firsthand knowledge of the 1909 extension.",
    topics: ["railroad", "1909", "extension", "pleasanton", "contested timeline"],
    dateRange: "1909",
    sourceType: "persona-note",
    citation:
      "Museum of the San Ramon Valley branch-line history; ECHOES temporal guardrail (1900).",
    url: MSRV_HEMME,
    reliability: "high",
  },
  {
    id: "rail-hemme-station",
    text: "A small freight depot was built on Hemme's ranch south of Alamo village — known as Hemme Station and later renamed Alamo Station. It had less town-shaping impact than Danville's depot, which sat next to Main Street.",
    topics: ["hemme station", "alamo station", "depot", "alamo", "freight"],
    dateRange: "1891",
    sourceType: "secondary",
    citation:
      "Museum of the San Ramon Valley; Alamo short history (SRV Historical Society).",
    url: MSRV_HEMME,
    reliability: "high",
  },
  {
    id: "rail-danville-growth",
    text: "Danville's downtown lay directly beside the Southern Pacific station, so the railroad spurred houses, hotels, businesses, warehouses, and boardwalks. Newspapers complained of congestion; Danville became the valley's major town.",
    topics: ["danville", "depot", "growth", "downtown", "railroad", "1891"],
    dateRange: "1891-1900",
    sourceType: "secondary",
    citation: "Museum of the San Ramon Valley, Lane Part II; Wikipedia: Danville station.",
    url: MSRV_HEMME,
    reliability: "high",
  },
  {
    id: "rail-danville-depot-built",
    text: "In 1891 Southern Pacific built combination passenger-freight depots to standard plan No. 18 (gold trimmed with brown) at Concord, Walnut Creek, Danville, and San Ramon. Danville's depot land came from John Hartz's station parcel.",
    topics: ["danville depot", "southern pacific", "1891", "architecture", "hartz"],
    dateRange: "1891",
    sourceType: "reference",
    citation:
      "Museum of the San Ramon Valley, Southern Pacific Danville Depot history; NRHP nomination; Wikipedia: Danville station (California).",
    url: WIKI_DANVILLE_DEPOT,
    reliability: "high",
  },
  {
    id: "rail-freight-produce",
    text: "The branch line carried valley hay, grain, nuts, fruit, cattle, and horses toward Martinez and beyond — the market access Hemme and neighbors had sought for San Ramon Valley produce.",
    topics: ["freight", "agriculture", "produce", "hay", "grain", "railroad"],
    dateRange: "1891-1900",
    sourceType: "secondary",
    citation: "Museum of the San Ramon Valley, History of the Iron Horse Trail.",
    url: MSRV_TRAIL,
    reliability: "high",
  },

  // ---------------- Iron Horse Trail (modern — beyond Hemme) ----------------
  {
    id: "rail-iron-horse-modern",
    text: "Decades after Hemme's lifetime, the abandoned Southern Pacific right-of-way became the Iron Horse Regional Trail, a multi-use path named for the train. Hemme (speaking 1900) knows the railroad corridor and depot life, not the late-20th-century trail as firsthand experience.",
    topics: [
      "iron horse trail",
      "iron horse",
      "trail",
      "modern",
      "right-of-way",
      "persona-note",
    ],
    dateRange: "1970s-present (after Hemme)",
    sourceType: "persona-note",
    citation:
      "Museum of the San Ramon Valley, History of the Iron Horse Trail; Wikipedia: Iron Horse Regional Trail.",
    url: MSRV_TRAIL,
    reliability: "high",
  },
  {
    id: "rail-abandonment-note",
    text: "Passenger service on the San Ramon Branch dwindled and ended in 1934; freight continued until Southern Pacific abandoned the line in 1978 — all after Hemme's 1904 death. Useful only as editor context for the later trail.",
    topics: ["abandonment", "1978", "passenger", "1934", "persona-note"],
    dateRange: "1934-1978",
    sourceType: "persona-note",
    citation: "Museum of the San Ramon Valley; Wikipedia: Danville station / Iron Horse Trail.",
    url: WIKI_IRON_HORSE,
    reliability: "high",
  },

  // ---------------- Valley agriculture & place ----------------
  {
    id: "valley-agriculture",
    text: "San Ramon Valley ranches began with cattle and grain (wheat, hay); by the railroad era walnuts and fruits were increasingly planted. Warehouses for hay and grain rose beside the tracks at Concord, Alamo, Danville, and San Ramon.",
    topics: ["agriculture", "walnuts", "fruit", "hay", "grain", "san ramon valley"],
    dateRange: "1850s-1900",
    sourceType: "secondary",
    citation: "Museum of the San Ramon Valley branch-line and trail histories.",
    url: MSRV_HEMME,
    reliability: "high",
  },
  {
    id: "valley-alamo",
    text: "Alamo was a small village north of Hemme's ranch lands; Hemme Avenue remembers the family ranch south of the village. The freight stop on the ranch was more important to shipping than to reshaping Alamo's street grid.",
    topics: ["alamo", "hemme avenue", "village", "ranch"],
    dateRange: "1850s-1900",
    sourceType: "secondary",
    citation: "SRV Historical Society Alamo short history; East Bay Times, Rego.",
    url: EBT,
    reliability: "high",
  },
  {
    id: "valley-danville-hartz",
    text: "John Hartz sold acreage for the Danville station and subdivided west of Front Street, helping shift Danville's orientation toward Hartz and Railroad Avenues around the depot.",
    topics: ["danville", "hartz", "railroad avenue", "downtown", "1891"],
    dateRange: "1891",
    sourceType: "secondary",
    citation: "Museum of the San Ramon Valley, Southern Pacific Danville Depot history.",
    url: "https://museumsrv.org/the-southern-pacific-danville-depot/",
    reliability: "high",
  },
  {
    id: "valley-san-ramon-depot-distance",
    text: "In San Ramon the village center was nearly a mile from the new depot in 1891; the Gazette called the site inconvenient until a better public road was discussed. The station even closed briefly in 1894–1895 before warehouses returned.",
    topics: ["san ramon", "depot", "1891", "warehouse"],
    dateRange: "1891-1897",
    sourceType: "secondary",
    citation: "Museum of the San Ramon Valley, Lane Part II (quoting Contra Costa Gazette).",
    url: MSRV_HEMME,
    reliability: "medium",
  },
  {
    id: "rail-depots-four",
    text: "Four main gold-and-brown SP plan No. 18 depots served Concord, Walnut Creek, Danville, and San Ramon when the branch opened — the architectural face of the line Hemme helped secure.",
    topics: ["depot", "concord", "walnut creek", "danville", "san ramon", "architecture"],
    dateRange: "1891",
    sourceType: "secondary",
    citation: "Museum of the San Ramon Valley, Lane Part I.",
    url: MSRV_HEMME,
    reliability: "high",
  },
  {
    id: "bio-identity-summary",
    text: "In short: Prussian-born 1833; to America 1846; California 1849; ~3,000-acre San Ramon Valley ranch by ~1852; married Minerva Ish 1856; later San Francisco assay wealth and philanthropy; returned to the valley; led 1890–91 railroad right-of-way fight; Hemme Station on his ranch; financial collapse late 1890s; speaking here from 1900.",
    topics: ["biography", "who are you", "yourself", "identity", "summary"],
    dateRange: "1833-1900",
    sourceType: "biographical",
    citation: "Composite of East Bay Times (Rego 2013) and Museum of the San Ramon Valley.",
    url: EBT,
    reliability: "high",
  },
  {
    id: "valley-contra-costa",
    text: "The San Ramon Valley lies in Contra Costa County — Alamo, Danville, and San Ramon linked by the branch line north toward Martinez and the bay shipping points.",
    topics: ["contra costa", "geography", "san ramon valley", "martinez"],
    dateRange: "1891-1900",
    sourceType: "reference",
    citation: "Museum of the San Ramon Valley railroad histories.",
    url: MSRV_HEMME,
    reliability: "high",
  },
];
