import type {
  PersonaSemanticVocab,
  SourceSemanticAnnotations,
} from "@/lib/semantic";

/** Controlled vocabulary for Alonzo Horton. */
export const hortonVocab: PersonaSemanticVocab = {
  people: [
    {
      id: "alonzo-horton",
      label: "Alonzo Horton",
      aliases: [
        "horton",
        "alonzo e. horton",
        "alonzo erastus horton",
        "a.e. horton",
        "a. e. horton",
      ],
    },
    {
      id: "william-heath-davis",
      label: "William Heath Davis",
      aliases: ["davis", "william heath davis", "w.h. davis"],
    },
  ],
  places: [
    {
      id: "san-diego",
      label: "San Diego",
      aliases: ["new san diego", "new town san diego", "san diego bay"],
    },
    {
      id: "new-town",
      label: "New Town",
      aliases: ["new town", "horton's addition", "hortons addition"],
    },
    {
      id: "old-town",
      label: "Old Town",
      aliases: ["old town san diego", "old town"],
    },
    {
      id: "san-diego-bay",
      label: "San Diego Bay",
      aliases: ["the bay", "harbor", "san diego harbor"],
    },
    {
      id: "city-park",
      label: "City Park",
      aliases: ["balboa park", "city park", "pueblo park"],
    },
    {
      id: "horton-plaza",
      label: "Horton Plaza",
      aliases: ["plaza", "broadway fountain", "horton plaza"],
    },
    {
      id: "union-connecticut",
      label: "Union, Connecticut",
      aliases: ["union connecticut", "connecticut"],
    },
    {
      id: "onondaga-county",
      label: "Onondaga County",
      aliases: ["onondaga", "onondaga county new york"],
    },
    {
      id: "oswego",
      label: "Oswego",
      aliases: ["oswego new york", "lake ontario"],
    },
    {
      id: "hortonville",
      label: "Hortonville",
      aliases: ["hortonville wisconsin", "outagamie county"],
    },
    {
      id: "wisconsin",
      label: "Wisconsin",
      aliases: ["wisconsin territory"],
    },
    {
      id: "el-dorado-county",
      label: "El Dorado County",
      aliases: ["el dorado", "mining towns"],
    },
    {
      id: "san-francisco",
      label: "San Francisco",
      aliases: ["sf", "market street", "sixth and market"],
    },
    {
      id: "panama",
      label: "Panama",
      aliases: ["via panama", "isthmus"],
    },
    {
      id: "presidio-san-diego",
      label: "San Diego Presidio",
      aliases: ["presidio", "san diego river"],
    },
  ],
  organizations: [
    {
      id: "san-diego-chamber-of-commerce",
      label: "San Diego Chamber of Commerce",
      aliases: ["chamber of commerce", "chamber"],
    },
    {
      id: "texas-pacific-railroad",
      label: "Texas Pacific Railroad",
      aliases: ["texas pacific", "texas and pacific"],
    },
    {
      id: "california-southern-railroad",
      label: "California Southern Railroad",
      aliases: ["california southern", "santa fe", "at&sf", "bnsf"],
    },
    {
      id: "unitarian-church",
      label: "Unitarian Church",
      aliases: ["unitarian", "unitarians", "first unitarian"],
    },
    {
      id: "republican-party",
      label: "Republican Party",
      aliases: ["republican", "whig", "copperhead"],
    },
    {
      id: "horton-house",
      label: "Horton House",
      aliases: ["horton house hotel", "horton hall"],
    },
  ],
  events: [
    {
      id: "gold-rush",
      label: "Gold Rush",
      aliases: ["california gold rush", "forty-niners", "1849", "gold rush"],
    },
    {
      id: "hortons-addition-purchase",
      label: "Horton's Addition purchase",
      aliases: [
        "bought the land",
        "960 acres",
        "horton's addition",
        "new town purchase",
      ],
    },
    {
      id: "city-park-reservation",
      label: "City Park reservation",
      aliases: ["city park", "1400 acres", "public park", "1868 park"],
    },
    {
      id: "texas-pacific-setback",
      label: "Texas Pacific setback",
      aliases: ["railroad aid withdrawn", "congress withdrew", "contracts canceled"],
    },
    {
      id: "california-southern-arrival",
      label: "California Southern arrival",
      aliases: ["railroad arrived", "1885 railroad", "rail connection"],
    },
    {
      id: "1880s-boom-bust",
      label: "1880s boom and bust",
      aliases: ["land boom", "land bust", "real estate crash", "boom"],
    },
    {
      id: "panama-gold-loss",
      label: "Panama gold loss",
      aliases: ["lost gold dust", "panama attack", "10000 gold"],
    },
    {
      id: "happiness-philosophy",
      label: "Philosophy of happiness and giving",
      aliases: [
        "happiness",
        "giving",
        "generous",
        "generosity",
        "philosophy about happiness",
      ],
    },
  ],
  periods: [
    {
      id: "early-life-east",
      label: "Early life in the East",
      yearStart: 1813,
      yearEnd: 1836,
      aliases: ["connecticut youth", "new york youth", "before wisconsin"],
    },
    {
      id: "wisconsin-years",
      label: "Wisconsin years",
      yearStart: 1836,
      yearEnd: 1851,
      aliases: ["hortonville years", "wisconsin period"],
    },
    {
      id: "gold-rush-era",
      label: "Gold Rush era",
      yearStart: 1848,
      yearEnd: 1859,
      aliases: ["gold rush years", "mining country"],
    },
    {
      id: "new-town-founding",
      label: "New Town founding",
      yearStart: 1867,
      yearEnd: 1880,
      aliases: ["founding new town", "new town era", "early san diego"],
    },
    {
      id: "boom-era",
      label: "Boom era",
      yearStart: 1880,
      yearEnd: 1905,
      aliases: ["1880s boom", "railroad era", "late career"],
    },
  ],
};

/** Hand tags for curated Horton sources. */
export const hortonSourceAnnotations: SourceSemanticAnnotations = {
  "bio-birth": {
    people: ["alonzo-horton"],
    places: ["union-connecticut", "onondaga-county"],
    yearStart: 1813,
    yearEnd: 1813,
    period: "early-life-east",
  },
  "bio-oswego-youth": {
    people: ["alonzo-horton"],
    places: ["oswego"],
    organizations: ["republican-party"],
    yearStart: 1834,
    yearEnd: 1834,
    period: "early-life-east",
  },
  "bio-wisconsin-hortonville": {
    people: ["alonzo-horton"],
    places: ["wisconsin", "hortonville"],
    yearStart: 1836,
    yearEnd: 1851,
    period: "wisconsin-years",
  },
  "bio-california-gold-ice": {
    people: ["alonzo-horton"],
    places: ["el-dorado-county", "wisconsin"],
    events: ["gold-rush"],
    yearStart: 1851,
    yearEnd: 1857,
    period: "gold-rush-era",
  },
  "bio-sf-furniture": {
    people: ["alonzo-horton"],
    places: ["san-francisco", "san-diego"],
    yearStart: 1862,
    yearEnd: 1867,
  },
  "bio-decide-san-diego": {
    people: ["alonzo-horton"],
    places: ["san-francisco", "san-diego"],
    yearStart: 1867,
    yearEnd: 1867,
    period: "new-town-founding",
  },
  "bio-unitarian-republican": {
    people: ["alonzo-horton"],
    places: ["san-diego"],
    organizations: ["unitarian-church", "republican-party"],
    yearStart: 1860,
    yearEnd: 1879,
    period: "new-town-founding",
  },
  "bio-healthiest-spot": {
    people: ["alonzo-horton"],
    places: ["san-diego", "san-diego-bay", "new-town"],
    yearStart: 1867,
    yearEnd: 1867,
    period: "new-town-founding",
  },
  "newtown-purchase-1867": {
    people: ["alonzo-horton"],
    places: ["new-town", "san-diego-bay", "san-diego"],
    events: ["hortons-addition-purchase"],
    yearStart: 1867,
    yearEnd: 1867,
    period: "new-town-founding",
  },
  "newtown-vs-old-town": {
    people: ["alonzo-horton"],
    places: ["old-town", "new-town", "san-diego-bay", "presidio-san-diego"],
    yearStart: 1867,
    yearEnd: 1889,
    period: "new-town-founding",
  },
  "newtown-davis-prior": {
    people: ["alonzo-horton", "william-heath-davis"],
    places: ["new-town", "san-diego-bay", "san-francisco"],
    yearStart: 1850,
    yearEnd: 1867,
  },
  "newtown-development": {
    people: ["alonzo-horton"],
    places: ["new-town", "san-diego"],
    organizations: ["horton-house"],
    events: ["hortons-addition-purchase"],
    yearStart: 1867,
    yearEnd: 1879,
    period: "new-town-founding",
  },
  "newtown-father-title": {
    people: ["alonzo-horton"],
    places: ["san-diego", "new-town"],
    events: ["hortons-addition-purchase"],
    yearStart: 1867,
    yearEnd: 1867,
    period: "new-town-founding",
  },
  "park-city-park-1868": {
    people: ["alonzo-horton"],
    places: ["city-park", "san-diego"],
    events: ["city-park-reservation"],
    yearStart: 1868,
    yearEnd: 1868,
    period: "new-town-founding",
  },
  "chamber-of-commerce": {
    people: ["alonzo-horton"],
    places: ["san-diego"],
    organizations: ["san-diego-chamber-of-commerce"],
    yearStart: 1870,
    yearEnd: 1879,
    period: "new-town-founding",
  },
  "railroad-texas-pacific-setback": {
    people: ["alonzo-horton"],
    places: ["san-diego"],
    organizations: ["texas-pacific-railroad"],
    events: ["texas-pacific-setback"],
    yearStart: 1870,
    yearEnd: 1879,
  },
  "railroad-california-southern-1885": {
    places: ["san-diego", "new-town"],
    organizations: ["california-southern-railroad"],
    events: ["california-southern-arrival"],
    yearStart: 1885,
    yearEnd: 1885,
    period: "boom-era",
  },
  "boom-bust-1880s": {
    people: ["alonzo-horton"],
    places: ["san-diego"],
    events: ["1880s-boom-bust"],
    yearStart: 1880,
    yearEnd: 1905,
    period: "boom-era",
  },
  "plaza-horton-plaza": {
    people: ["alonzo-horton"],
    places: ["horton-plaza", "new-town", "san-diego"],
    yearStart: 1870,
    yearEnd: 1905,
    period: "boom-era",
  },
  "plaza-horton-house": {
    people: ["alonzo-horton"],
    places: ["new-town", "old-town", "san-diego-bay"],
    organizations: ["horton-house"],
    yearStart: 1870,
    yearEnd: 1879,
    period: "new-town-founding",
  },
  "philosophy-happiness": {
    people: ["alonzo-horton"],
    events: ["happiness-philosophy"],
    yearStart: 1867,
    yearEnd: 1905,
  },
  "philosophy-booster": {
    people: ["alonzo-horton"],
    places: ["hortonville", "san-diego", "new-town"],
    yearStart: 1867,
    yearEnd: 1905,
    period: "new-town-founding",
  },
  "sd-bay-harbor": {
    people: ["alonzo-horton"],
    places: ["san-diego-bay", "new-town", "old-town"],
    yearStart: 1867,
    yearEnd: 1867,
    period: "new-town-founding",
  },
  "sd-arrival-1867": {
    people: ["alonzo-horton"],
    places: ["san-diego", "new-town", "san-diego-bay"],
    events: ["hortons-addition-purchase"],
    yearStart: 1867,
    yearEnd: 1867,
    period: "new-town-founding",
  },
  "sd-marriages": {
    people: ["alonzo-horton"],
    places: ["wisconsin"],
    yearStart: 1840,
    yearEnd: 1869,
  },
  "sd-1905-present": {
    people: ["alonzo-horton"],
    places: ["san-diego", "new-town", "city-park"],
    events: ["california-southern-arrival", "1880s-boom-bust"],
    yearStart: 1905,
    yearEnd: 1905,
    period: "boom-era",
  },
  "sd-courthouse-1880s": {
    places: ["new-town", "old-town", "san-diego"],
    yearStart: 1880,
    yearEnd: 1889,
    period: "boom-era",
  },
  "wisconsin-sale-to-california": {
    people: ["alonzo-horton"],
    places: ["wisconsin", "hortonville"],
    events: ["gold-rush"],
    yearStart: 1851,
    yearEnd: 1851,
    period: "wisconsin-years",
  },
  "panama-return": {
    people: ["alonzo-horton"],
    places: ["panama", "el-dorado-county"],
    events: ["panama-gold-loss", "gold-rush"],
    yearStart: 1857,
    yearEnd: 1857,
    period: "gold-rush-era",
  },
};
